### ISSUE TITLE
crash regarding Thaumacraft

### ISSUE THREAD

**Issue by nightstalker6669** [OpenModularTurretsTeam/OpenModularTurrets#102]
i'm getting this crash when my test server loads, and when i place any turret base down. i don't have TC installed, so i find it quite odd.

http://pastebin.com/2ThmignD

this is being built from latest github commits.

**Comment by Keridos** [comment]
Try this please, don't know but it should fix that crash, missed that when I made stuff optional.

**Comment by nightstalker6669** [comment]
yep fixed
