### ISSUE TITLE
Ranged attack on turrets

### ISSUE THREAD

**Issue by bbgott** [OpenModularTurretsTeam/OpenModularTurrets#104]
I love the idea if turrets and am currently playing with them on my server. My players are complaining that the turrets are OP'd in PvP. I've enabled the option that anyone can break them, but that still requires attempting a melee attack on a high powered ranged weapon. It would be nice if they could be damaged or destroyed with a ranged attack.

**Comment by bbgott** [comment]
A melee attack on a high powered ranged weapon. It works be nice it they could be damaged or destroyed with a ranged attack.

**Comment by Keridos** [comment]
I'd suggest a warfare mod that enables to remotely kill structures via rockets etc. This mod should in my opinion just provide turrets. We can make their hardness values configurable if it is what the players want. But killing them remotely is nothing that this mod should be about. Maybe add in some kind of temporary disabler, but nothing more.

**Comment by Poenjabiesous** [comment]
The idea behind this mod is defense- keeping entities out of a specific area through the mechanism of an automated turret system. Keeping the turrets operational is not cheap, they require a power source and ammo. If people are complaining that the turrets are too overpowered, then the mod is doing it's job correctly as per the above stated definition; keeping entities out of a certain area, and the argument is rendered moot.

We will incorporate admin tools, such as to only allow a set number of turret bases per player, in the next release. This might address the concern of the players if turrets cant be spammed, and turret bases must then be deployed strategically.
