### ISSUE TITLE
Turret projectile overloading the server

### ISSUE THREAD

**Issue by tossaponk** [OpenModularTurretsTeam/OpenModularTurrets#107]
Refer to the recent issue by me #97. 

After playing for a while, I found out that the code did prevent projectiles from saving to disk. But there's the case where the projectile is still remaining in server memory when the server is left running for a long time without restarting the server and will cause overloading when their number stacked up.

Adding the call to ```setDead()``` into writeToNBTOptional will cause the projectile to be removed from the server immediately when they're moving into unloaded chunks.
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/6ccf5b29f777c4e972c958d60cbf1a006c2ca90f/src/main/java/openmodularturrets/entity/projectiles/TurretProjectile.java#L45-48

**Comment by Keridos** [comment]
Thank you again!
