### ISSUE TITLE
Feature Request: Config option to allow being destroyed 

### ISSUE THREAD

**Issue by Simbaholic** [OpenModularTurretsTeam/OpenModularTurrets#108]
Hi there, I've been considering to use this mod for base defences for some PvP fun with a friend, but it sucks have invulnerable base defences. Is it possible to add a config option to allow it being destroyed by explosions or something? Maybe an optional health system?

**Comment by Poenjabiesous** [comment]
Please see #104.

**Comment by Poenjabiesous** [comment]
There is already a config option to allow anyone to break turrets/bases.
