### ISSUE TITLE
Turret owners and trusted players should use UUIDs instead of names

### ISSUE THREAD

**Issue by smbarbour** [OpenModularTurretsTeam/OpenModularTurrets#109]
A player on my server changed his Minecraft name and can no longer access his own turrets.

 - [x] TurretBase, NBT, Owner etc. changed to UUID
 - [x] backwards compatability
 - [x] fix the configure GUI (crashes and incompatability with the UUID system)
 - [x] test this is SMP extensively

**Comment by Poenjabiesous** [comment]
Thanks for the feedback. Will look into this.

**Comment by Keridos** [comment]
I think I actually coded that in correctly for the advanced players, it should look for the name of the game profile, not the player itself.

**Comment by Poenjabiesous** [comment]
I think the NBT stores the getDisplayName()

**Comment by Keridos** [comment]
Thing is we need UUID to name conversion to work with this for the trusted players, but how can we get the UUID of offline players?

**Comment by Poenjabiesous** [comment]
Yeah, the issue lies here:

 if (!world.isRemote) {
            EntityPlayerMP player = (EntityPlayerMP) elb;
            TurretBase base = (TurretBase) world.getTileEntity(x, y, z);
            *base.setOwner(player.getDisplayName());*
            if (world.isBlockIndirectlyGettingPowered(x, y, z)) {
                base.setRedstone(true);
            } else if (!world.isBlockIndirectlyGettingPowered(x, y, z)) {
                base.setRedstone(false);
            }
        }

**Comment by Poenjabiesous** [comment]
That was what I was thinking as well. We cant ask players to specify the UUID of the trusted players. However, I think this specific issue only relates to the owner of the base losing ownership after changing his/her name.

**Comment by Poenjabiesous** [comment]
Here's what I propose:

1. New field in turretBase: ownerUUID
2. Change fields to match UUID of interacting entity, as opposed to displayName.
3. setOwner(player.getDisplayName) will then still be an issue, as that will then need to dynamically change.

**Comment by Keridos** [comment]
Changing this might be very very annoying for the players, I think we would have to do it how Applied Energistics does it, each player must shift rightclick some item that then stores his/her UUID and name on it and give it to the players who then uses that item to add them to the trusted players.

**Comment by Poenjabiesous** [comment]
Whatever we do, it will impact compatibility with current versions of the mod. Going from player name to UUID is a big change.

**Comment by Keridos** [comment]
Why not just scrap the player.getDisplayName and just store the UUID?

**Comment by Poenjabiesous** [comment]
Backwards compatibility. Upgrading to v2.0.X, turrets will attack their (not anymore) owners.

**Comment by Keridos** [comment]
It cannot be done unless we find a way to get the UUID from just the name. At least bukkit had something to do that. So I assume it is possible in forge somehow, too.

**Comment by Poenjabiesous** [comment]
Agreed.

**Comment by Keridos** [comment]
But: There is no getPlayerByUUID currently, but you can write one on for your own easily. Just loop through all players (ServerConfigurationManager has them) and check each one for the correct UUID (of course only do this on the server). We could maybe do something like that.

**Comment by Poenjabiesous** [comment]
Porting 1.6.4 to 1.7.X blues.

**Comment by Poenjabiesous** [comment]
I think the best and easiest solution for this, is simply adding in a new field to turretBase, "ownerUUID", which will be used to identify the owner. If he/shes changes display names later, they wont lose ownership of the base. We can then dynamically update the "owner" string based on your previous message.

Trusted players will, in this case, only be addable to a turret base if he/she is online (to get the UUID of that player)

**Comment by Keridos** [comment]
Well I think that the system I proposed makes much more sense since it works with ALL the players on that server and actually is fully backwards compatible.

**Comment by Poenjabiesous** [comment]
Won't that change the way trusted players are currently add/removed/changed?

**Comment by Keridos** [comment]
No, it would not since you can get the UUID from the name as string.

**Comment by Poenjabiesous** [comment]
So, the current "configure" gui, where you change targeting params/add+remove trusteds, will stay the same?

**Comment by Poenjabiesous** [comment]
"Loop through the players, compare names, if name does not exist, delete it from the trusted players list. If owner does not exist, try to check if we can get player profile and see it the original name was the same for every player, then update. if that fails, just delete the turretbase block."

^^

**Comment by smbarbour** [comment]
As a last ditch measure, there is a file stored on the server that contains a list of player names and their UUIDs. It's not ideal, but it could be read if needed.

**Comment by Keridos** [comment]
@Poenjabiesous Yes the UI can be exactly the same.

**Comment by smbarbour** [comment]
If anyone runs into this issue before a fix is implemented, I wrote a small server-side mod that will allow an op (or the server console) to change the owner of a turret base:
http://mods.mcupdater.com/strangetoolkit/
source: https://github.com/smbarbour/StrangeToolkit

**Comment by Keridos** [comment]
@Poenjabiesous can you please explain to me what the IsCurrentPlayerAdmin and the whole copying of trusted players in the configure GUI does? I have literally no clue after reading through it and I think we might be able to vastly simplify this.

**Comment by Poenjabiesous** [comment]
Ah, that is the index of the currently viewed trusted player in the config GUI. When clicking << or >>, the current gui sceen gets closed, and a new one gets opened with the new index number. I did this because background text can not be dynamically changed; the drawing method only gets called once.

**Comment by Keridos** [comment]
Ah ok, then I see the problem, I made it so that when you enter a username, that is not found on the server, it does not create the trusted player entry at all. We need to respect that in the GUI as well. Maybe change the addTrustedPlayer(name) function to be boolean and give back false if no player was added.

**Comment by Keridos** [comment]
@nightstalker6669 Can you maybe do us a little favor and test the next build in SMP somehow? I pretty much rewrote most of the UI Code and and I need someone to check if permissions work fine in SMP now and if there is any bugs with the UI atm.

**Comment by nightstalker6669** [comment]
@keridos yea no problem, gimme a few to compile it and throw it on my test server and i'll get some of my guys to play with it.

**Comment by Keridos** [comment]
no need to compile, just fetch it from here: https://www.ironhide.de/jenkins/job/OpenModularTurrets/103/

**Comment by nightstalker6669** [comment]
alrighty i'll get on it now
