### ISSUE TITLE
GUI control to toggle OC/CC Access

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#110]
We should consider adding in a GUI for enabling CC/OC function access. I will add the required variable soon, @Poenjabiesous  can you think of a way how we can toggle it in the GUI?

 - [x] TileEntity code ready
 - [ ] new upgrade

**Comment by Poenjabiesous** [comment]
Instead of a new GUI toggle, why don't we just add in a new addon of that (like I did for thaumcraft)?

**Comment by nightstalker6669** [comment]
just out of curiosity, why does this need to be implemented in the first place? if neither CC or OC is connected to the turret base then nothing should happen, and if both are connected (why you would have both connected at the same time is beyond me) then it should still work together. even tho its 2 separate mods they are still pulling from the same pool of information.

**Comment by Keridos** [comment]
@nightstalker6669 this is not about switching them, it is about turning both of them off to prevent turrets from being hackable.

@Poenjabiesous we might make this an additional addon, but I do not know which type exactly

**Comment by Poenjabiesous** [comment]
No worries, I'll add that in. Will be a new item.

**Comment by Keridos** [comment]
The variable for it is in the TurretBase already, called computerAccess.

**Comment by Poenjabiesous** [comment]
Looking at it now. I think the check should be TurretHeadUtil.hasSerialPortAddon(), instead of setting a local variable on each tick, since that method needs to be run anyway.
