### ISSUE TITLE
issues with jenkins build 103

### ISSUE THREAD

**Issue by nightstalker6669** [OpenModularTurretsTeam/OpenModularTurrets#112]
- [x] adding player as trusted doesn't immediately update, you have to leave the turret and then go back to configure for it to show up.

- [x] when a player is in creative and NOT on the trust list, and they leave creative, it starts attacking them, when they go back into creative it continues to attack them.

- [x] when you deactivate attack players when its attacking someone, it still continues to attack them until they go out of range.

- [x] also you still take damage from turrets if you are between the turret and its target while you are the owner. idk if thats in regards to the owner showing up as null. but it still hits you even when your on the trust list.

- [x] teleporter turret "looks" like it teleports someone, but it doesn't actually affect the player. this is sporadic. sometimes it works, sometimes it doesn't. it doesn't matter if your in creative or not.

- [x] zombies are catching potatoes from the potato cannon. (LOL)

- [x] when right clicking on to another persons turret that i am on the trust list for and have all permissions, it still gives me the message that i don't own this turret and don't have permission to do that. but i can still modify it.   http://puu.sh/icB9s/80fa04794b.jpg

**Comment by Poenjabiesous** [comment]
Added checkboxes to keep track of bugs, thanks for the testing!

**Comment by Poenjabiesous** [comment]
"zombies are catching potatoes from the potato cannon."

This one is unfixable, I think. The bound item that gets spawned is set with:

itemBound.delayBeforeCanPickup = 100;

But, the item still gets picked up by them. This tells me that the zombie code ignores the fact that an Item can not be picked up.

**Comment by Poenjabiesous** [comment]
"also you still take damage from turrets if you are between the turret and its target while you are the owner. idk if thats in regards to the owner showing up as null. but it still hits you even when your on the trust list"

I think this is configurable (Keridos added it), but I am not 100% sure.

**Comment by Poenjabiesous** [comment]
I think the teleporter turret is fixed now, changed to the correct server side teleportation code.

**Comment by Poenjabiesous** [comment]
Can I close this ticket?

**Comment by nightstalker6669** [comment]
i'm setting up my testserver for an update for my mains server, i'll give it another go and make sure, but as far as I know everything has been fixed.

**Comment by Keridos** [comment]
Did not see any more issue either, so I am gonna close this to prevent further confusion.
