### ISSUE TITLE
Disable SFX

### ISSUE THREAD

**Issue by DPxKnightxZero** [OpenModularTurretsTeam/OpenModularTurrets#114]
I am really not a fan of how annoying the sound is can you enable a way to disable sfx for firing?

**Comment by Keridos** [comment]
We can do that, we already have reduced the sounds volume by I think 40%, but this might be a added in the config later in 2.0.0. @Poenjabiesous you agree on making this a config setting?

**Comment by Poenjabiesous** [comment]
Agreed. I dont agree on no sound whatsoever; in my opinion it adds a new dimension of security when you are able to hear where there may be hostile entities, what this mod is all about. But, I can also understand that there may be players that might dont want to hear the forced feedback.

**Comment by Keridos** [comment]
Config setting for sound effects and default it to true?

**Comment by Keridos** [comment]
We could as well do this via a percentage settings for turret sounds.

**Comment by DPxKnightxZero** [comment]
Actually that would make more sense anyways.

**Comment by DPxKnightxZero** [comment]
Thank you for your hard work.
