### ISSUE TITLE
Mod-expanding brainstorm

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#122]
I made this new thread to discuss ideas around mod expanding items and blocks. Currently testing 2.0.0 on a local server, there was interest shown toward static defenses - like electric fences - to be added into the mod. My feeling is that it keeps the general theme of defense the mod provides, so adding it does seem like a good idea. This will not form part of the critical path of the 2.0.0 milestone, but be added into a later release.

Thoughts?

**Comment by Keridos** [comment]
This sounds nice. We can also maybe add armored blocks and such.

**Comment by Poenjabiesous** [comment]
My thoughts exactly.

**Comment by Beelzaboss** [comment]
Would love if this could be implemented :D

**Comment by Keridos** [comment]
Implementing it should be no problem. Will be released later though, 2.0.0 is next and almost ready.

**Comment by teamMK** [comment]
A Point Defense System (like Iron dome)would be nice, wich can shoot down Projectiles like Arrows, MFR Missiles, Nukes drop from a stealth jet of Rival rebels (and by the way that the turrets auto target these bombers :D) and so on...

Maybe two tiers, a projectile based like isreals iron dome and a second like the american T.H.E.L.

**Comment by jmc666** [comment]
Glad to see this wonderful mod gathering even more momentum. :D (Please excuse the length - I love me some castles and turrets!) [I have no idea how difficult any of these suggestions would be to implement - I shall assume very and prepare to be called a giant idiot ;P ] 

I do have several(!) possible suggestions:

- The idea I would most want to see is some form of camouflage/retracting & extending turret so they can be more of a surprise in sieges against other players and just look cool. The idea of letting your walls and the turrets on them absorb the first attack before springing the turrets from behind/beside/beneath/above sounds like lots of fun.

- For the to be implemented walls - camouflaged/retractable (several blocks high) options that could trap enemies within - I know there's already Pistons and Drawbridges[Tinkers], but they're pretty clunky. Besides the idea of vertical wall columns rising out of the ground and then slats extending out horizontally to fill the gaps in between seems like it would be visually spectacular. Would gatehouses be to much to ask for as well? Basically a castle please?

- Mines, Fire/Gas/Liquid traps and Spikes/Dragons Teeth (Tank Traps) (Retractable Spikes [I seem to have a retractable theme going on]) would no doubt be amazingly done by you guys.

- I saw a mention in another post of an Teleport/Ender Turret - If you could choose where the target got teleported to it would be hilarious (and useful for grinders/farms)

- Some form of block/turret that causes a sounds to discourage/troll attackers - I'm thinking creeper hiss, TNT fuse, Wither Boss Alarm.

- In a similar vein a block/turret that causes illusion/hologram(ish) versions of mobs - can't attack the enemy and a killed with the slightest punch - mostly just a distraction though combined with below for better results

- As above but the ability to spawn/throw that mob (zombie/creeper/chicken?/whatever) at the enemy, the projectile should probably be the spawn egg --> Please can I fire chickens at my enemies! Pretty Please!

- FINALLY (again sorry for the length), Anything Mortar-ish that would let Pyrotheum Florbs be rained down upon enemies a great range, I suppose maybe other florbs as well ->but I really want to bombard people with chickens and as a polite and kind host to then cook them all. Mwuhaha. 

Whatever you guys end up doing will not doubt be great - am very much looking forward to the future updates. Cheers. Joe.

**Comment by Keridos** [comment]
I think the teleport turret already is in and it ports the entitities 1 block above it, so just build a room over it and they should land in there. Then you can do what you want from that room on.

For quite some things you mention I do believe that minecraft is not the game to implement such things as it partially requires much more advanced stuff, for example the movable turrets is a lot of more work than most people realize. And fancy animations are possible but I personally do not really think they are worth the effort (its a couple dozen times more work to implement those, by my guess).

The Mines, Traps and Spikes should be fairly easy, even making them piston movable or implementing an own block for that should be possible and in my opinion would fit the theme of the mod. 

We can also make a dispenser like turret that does not use the item to damange but rather "uses" it when it hits something. That should not be hard to implement as well, too. Same goes for the "sound" turret.
Not that sure about the mortar as we might need to hardcode what which ammo does in it, but we can consider that.

@Poenjabiesous what do you think about that?

**Comment by Poenjabiesous** [comment]
Enough new functionality in right now, we can polish what we have added.
