### ISSUE TITLE
Drop turrets, Drop base and Configure buttons not showing when playing on server, shows fine in single player.

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#123]
Like the top statement tells, in multiplayer it looks like this:

![image](https://cloud.githubusercontent.com/assets/8829214/8236777/d1c9e970-15ea-11e5-8552-208563ade12e.png)

And in single player:

![image](https://cloud.githubusercontent.com/assets/8829214/8236799/f91f0a8c-15ea-11e5-8892-6627d892f0f6.png)

**Comment by Poenjabiesous** [comment]
Hmmm.... this seems to be something on the server itself. Hang on...

**Comment by Poenjabiesous** [comment]
False alarm, the server seems to bypass player UUID's somehow.

**Comment by Wolftein** [comment]
I'm having the same issue.

**Comment by Keridos** [comment]
This is related to either a cracked client or due to the mojang server not authing correctly. Use a different launcher or better the original launcher to fix this.

**Comment by Wolftein** [comment]
I'm using the original vanilla launcher.

NOTE: Indeed the issue was the server not being authing correctly, ty.

**Comment by Keridos** [comment]
Yeah they have problems today...
