### ISSUE TITLE
Walls & Fences

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#124]
The walls and Fences for the 2.1.0 release

- [x] Barbwire Fence
- [x] Mesh Fence
- [ ] Electric Fence
- [x] Wall
- [x] Better Wall?

**Comment by Keridos** [comment]
A quck note to this, the electric fence should have a base station that powers it in my opinion. And it should damage everybody that touches or attacks it.

**Comment by Poenjabiesous** [comment]
I have considered this, but that would require the fences to have tile entities. If every player then plops down, say, a hundred of these... Its simply not lightweight enough for them to implement IEnergyHandler as well as a TE, since imo its a block that can be used for general construction purposes. They do, however, hurt anyone/anything.

**Comment by Keridos** [comment]
You do not need the Interface for the fences with the solution I mentioned. Only the Base Station for the fences does. You can do all the other things via using a reference to the base station like the turretheads do.

**Comment by Poenjabiesous** [comment]
I can look into this; what advantages will the electric fences have over the normal current barbed fences? Damage?

**Comment by Keridos** [comment]
Yes, and also damage people who attack it. And armor ignoring damage maybe

**Comment by Poenjabiesous** [comment]
I like that. I'll do a tiered electric fence base as well that simply looks for electric fences in it's area and powers them.

**Comment by Keridos** [comment]
We can require it to be connected to the fences optionally?

**Comment by Poenjabiesous** [comment]
Yes. What I mean is I'm not gonna implement a breadth- or depth first fence searching algorithm. It's gonna be too expensive. If a fence base has a fence block next to it, power all in a 3x3 (Tier 1), 5x5(Tier 2), 7x7, etc.

**Comment by Keridos** [comment]
Ah ok.

**Comment by Keridos** [comment]
Though we technically could do the search algorithm. We can change it to only update when a fence is placed near one of the bases.

**Comment by Poenjabiesous** [comment]
Let me think/do some research on this one. If we were to do it, we will need a lightweight search algorithm that supports a max depth - we can then base the base tier scaling based on that; i.e: Tier 1 -> max search depth = 3, Tier 2 =5, etc.

**Comment by Keridos** [comment]
We could make it easier as well: Just implement a scan button in the GUI so that the player has to place the fence and then base, then tell the base to search.

**Comment by Poenjabiesous** [comment]
I think the current options are enough for the time being.
