### ISSUE TITLE
Suggestion: Anti-turret systems

### ISSUE THREAD

**Issue by Flenix** [OpenModularTurretsTeam/OpenModularTurrets#125]
Just an idea really. I've got OMT installed on a server which has PvP/Raiding allowed, and as such feel the turrets are a little overpowered. Players can place them in towns, where raiding players cannot build, and therefore the raider has no defense against the turret.

I was thinking of a few ideas which might balance them a little more for this kind of situation. Obviously they could all be configurable for the users who just want a simple anti-grief system for peaceful servers etc.

1. Turret Hacking. Some sort of PDA-style item which when pointed at a turret block and enabled, it disables the turret block & all attached turrets for X seconds. Maybe make it so they have to keep line of sight for X seconds to take it offline, or maybe even just it's only offline while being watched (encouraging teamwork)

2. Turret Health. Turrets could have a set amount of "health", and take damage. This would be pretty easy to do for Melee-style weapons (Check if player clicked, if so get held item -> get attack damage, negate off health) but I'm not sure how well it would work for projectiles such as those from Flan's mod, or explosives. Hence it's just an idea :)
It could also pave the way for a new upgrade option to increase health, as well as another continual upkeep cost in repairing damaged turrets. Once a turret is 100% damaged it simply wouldn't work and could be repaired back to normal.

3. EMP grenades. Similar to turret hacking, EMPs could take the turret offline for X seconds, but with the bonus of being able to take a few close-together ones out in one go. Maybe also drain out all RF?

Might think of more later :)

**Comment by Poenjabiesous** [comment]
Implementing something like this will change the scope of the mod in its entirety; it will become a war mod instead of a defense mod. Like I said before, if players are finding the turrets overpowered, then they are doing exactly what they were meant to do- keeping entities out of a specific area. 

Thanks for the interest in the mod in any case.

**Comment by Keridos** [comment]
Still any block destroying weapon can be used to destroy the turrets. Config settings for that are already implemented.

**Comment by Flenix** [comment]
Keridos; just to confirm, can it be configured so the turret blocks can be broken in a normal manor WITHOUT players being able to open the GUI? We have turrets at spawn which has heavier protection (due to mob mods we have overrunning spawn :P) so want to keep those safe.

**Comment by Keridos** [comment]
Yes.
