### ISSUE TITLE
IGWMod compatability with new version

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#126]
Gonna need to change a few things to make our igwmod support work with the new version of igwmod.

**Comment by Poenjabiesous** [comment]
Thanks! Any users running the new V2.0.0 version will get the update notifications, so they will know about bug fixes.

**Comment by Keridos** [comment]
Was there any reason why you replaced the accurate information from the wiki in the igwmod wiki files? Like the technical stuff. In my opinion we should keep that in.

**Comment by Poenjabiesous** [comment]
I took it out because it is configurable, if a server admin changes it, it wont reflect in the .txt file, unless theres a way to access the config from there

**Comment by Keridos** [comment]
Yeah, ok, then I think I am done with my work on that. Gonna make that be version 2.0.1.

**Comment by Poenjabiesous** [comment]
Perfect. Once the new jar is on curse we can remove the v2.0.0-133 jar

**Comment by Keridos** [comment]
I'd say lets keep the old version, why archive them?
