### ISSUE TITLE
Localization updates

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#127]
So, we will need to rely on the community for the updates to the current Chinese and Russian localizations; thought I'd make an issue here in the hopes of someone picking it up. @Keridos, will you be able to do a German one? :)

I'll do an Afrikaans one just for the heck of it. 

Lekker!

- [x] German
- [ ] Afrikaans

**Comment by Keridos** [comment]
Yes, I will do a translation, gonna do that for the 2.1.0 release.

**Comment by teamMK** [comment]
Maybe I can help with German

**Comment by Keridos** [comment]
@teamMK you can take a look at the translations I made and if you find anything wrong or unfittingly translated, just change it and make a PR.

**Comment by teamMK** [comment]
I allready fixed some things today :-). I send you the file withe corrections/translation suggestions hopefully tomorow.

**Comment by Keridos** [comment]
You can just fork the repo, change it in your repository and then make a pull request, so we can merge it.

**Comment by Poenjabiesous** [comment]
Thanks for the Chinese translation updates.
