### ISSUE TITLE
Mekanism universal cables don't attach to turrets.

### ISSUE THREAD

**Issue by davidwlewis** [OpenModularTurretsTeam/OpenModularTurrets#128]
Turret Bases won't accept RF from Mekanism universal cables. Some digging unearthed [this issue](https://github.com/aidancbrady/Mekanism/issues/1965 "Universal Cables not connecting to MFR/Thermal Expansion/Ender IO machines #1965").

The upshot is that Mekanism cables (and presumably other mods) no longer deliver power to the outdated version of [IEnergyHandler](https://github.com/CoFH/RedstoneFlux-API/blob/master/src/main/java/cofh/api/energy/IEnergyHandler.java) interface. [IEnergyReceiver](https://github.com/CoFH/RedstoneFlux-API/blob/master/src/main/java/cofh/api/energy/IEnergyReceiver.java) seems to be the appropriate replacement.

**Comment by Poenjabiesous** [comment]
Thanks for letting us know, will look into it.

**Comment by davidwlewis** [comment]
Having done some more reading, it looks like the same sort of issue *was* caused by an old version of the CoFH API, but the one shipping with OMT appears to be up to date.

I have replicated the issue with only Mekanism and OMT loaded, versions:
* Mekanism-1.7.10-8.1.5.246
* OpenModularTurrets-1.7.10-2.0.1-137

It also occurs with CoFHLib-[1.7.10]1.0.3B2-169 included, removing the cofh folder from the OMT jar. I presume this means there is another cause, perhaps on Mekanism's end.

**Comment by Keridos** [comment]
We updated the CoFH API not so long ago and I do not think that there was an update to it in the past few months. Maybe Mekanism is using the old API or something like that.

**Comment by davidwlewis** [comment]
To clear this up, everything works if you include CoFHCore instead of CoFHLib.

This is dumb, but is a problem with Mekanism, not OMT. =)
