### ISSUE TITLE
Modpack Incompatibility

### ISSUE THREAD

**Issue by ThunderSourceLLC** [OpenModularTurretsTeam/OpenModularTurrets#129]
Hey, I am making a mod pack which, compared to most Technic and FTB packs, is not very large. Every mod in the pack loads fine for my partner in crime, but on my computer I am having issues with OpenModularTurrets. Here is my crash report, let me know if anything strikes you as odd.

----------------------

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/10/15 6:57 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: java.util.logging.Logger.getGlobal()Ljava/util/logging/Logger;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: java.util.logging.Logger.getGlobal()Ljava/util/logging/Logger;
	at openmodularturrets.compatability.ModCompatibility.checkForMods(ModCompatibility.java:27)
	at openmodularturrets.ModularTurrets.init(ModularTurrets.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 272331904 bytes (259 MB) / 835465216 bytes (796 MB) up to 3203792896 bytes (3055 MB)
	JVM Flags: 2 total; -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 108 mods loaded, 108 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHI	Forge{10.13.4.1481} [Minecraft Forge] (modpack.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHI	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	bdlib{1.9.0.94} [BD Lib] (bdlib-1.9.0.94-mc1.7.10.jar) 
	UCHI	ae2stuff{0.4.2.43} [AE2 Stuff] (ae2stuff-0.4.2.43-mc1.7.10.jar) 
	UCHI	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHI	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHI	CoFHCore{1.7.10R3.0.3B2} [CoFH Core] (CoFHCore-[1.7.10]3.0.3B2-294.jar) 
	UCHI	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	Automagy{0.26} [Automagy] (Automagy-1.7.10-0.26.jar) 
	UCHI	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHI	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar) 
	UCHI	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHI	BuildCraft|Core{7.0.13} [BuildCraft] (buildcraft-7.0.13-core.jar) 
	UCHI	Forestry{3.6.2.19} [Forestry for Minecraft] (forestry_1.7.10-3.6.2.19.jar) 
	UCHI	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHI	ThermalFoundation{1.7.10R1.2.0B1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0B1-95.jar) 
	UCHI	ThermalExpansion{1.7.10R4.0.2B2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.2B2-210.jar) 
	UCHI	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHI	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCHI	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCHI	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCHI	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCHI	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCHI	BuildCraft|Energy{7.0.13} [BuildCraft Energy] (buildcraft-7.0.13-energy.jar) 
	UCHI	BuildCraft|Silicon{7.0.13} [BuildCraft Silicon] (buildcraft-7.0.13-silicon.jar) 
	UCHI	BuildCraft|Transport{7.0.13} [Buildcraft Transport] (buildcraft-7.0.13-transport.jar) 
	UCHI	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHI	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHI	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHI	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHI	chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-1.jar) 
	UCHI	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UCHE	openmodularturrets{2.0.1-138} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.0.1-138.jar) 
	UCHE	combatplus{1.0.2} [Combat Plus] (CombatPlus-1.0.2.jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHI	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHI	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHI	ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar) 
	UCHI	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
	UCHI	fluxedCrystals{1.0.3} [FluxedCrystals2] (Fluxed-Crystals2-1.0.3.jar) 
	UCHI	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHI	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHI	GardenCore{1.7.10-1.6.3} [Garden Core] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHI	GardenContainers{1.7.10-1.6.3} [Garden Containers] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHI	GardenStuff{1.7.10-1.6.3} [Garden Stuff] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHI	GardenTrees{1.7.10-1.6.3} [Garden Trees] (GardenStuff-1.7.10-1.6.3.jar) 
	UCHI	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHI	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHI	LogisticsPipes{0.9.1.15} [Logistics Pipes] (logisticspipes-0.9.1.15.jar) 
	UCHI	lootbags{1.8.1} [Loot Bags] (LootBags-1.7.10-1.8.1.jar) 
	UCHI	MagicBees{1.7.10-2.3.2} [Magic Bees] (magicbees-1.7.10-2.3.2.jar) 
	UCHI	mcheli{0.9.3} [MC Helicopter] (mcheli) 
	UCHI	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104 (1).jar) 
	UCHI	modtweaker2{0.8.3} [Mod Tweaker 2] (ModTweaker-2-0.8.3.jar) 
	UCHI	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCHI	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCHI	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHI	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) 
	UCHI	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHI	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHI	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UCHI	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCHI	SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
	UCHI	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) 
	UCHI	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHI	thaumicenergistics{0.8.10.7} [Thaumic Energistics] (thaumicenergistics-0.8.10.7.jar) 
	UCHI	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHI	ThermalDynamics{1.7.10R1.1.0B2} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0B2-149.jar) 
	UCHI	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHI	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHI	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHI	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHI	technom{0.11.1} [Technomancy] (Technomancy - 0.11.1 - 1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.2.7 310.41.25f01' Renderer: 'NVIDIA GeForce GT 750M OpenGL Engine'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3B2-294
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.2.0B1-95
	ThermalExpansion: -[1.7.10]4.0.2B2-210
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	ThermalDynamics: -[1.7.10]1.1.0B2-149
	List of loaded APIs: 
		* API_NEK (1.0.0) from NotEnoughKeys-1.7.10-1.0.0b29.jar
		* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
		* appliedenergistics2|API (rv2) from ThaumicTinkerer-2.5-1.7.10-164.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar
		* BotaniaAPI (51) from Fluxed-Crystals2-1.0.3.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|blueprints (1.3) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|core (1.5) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|robotics (2.1) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.13-core.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|tools (1.0) from SolarExpansion-Basic-1.6a.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.0.13-core.jar
		* ChiselAPI (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.4.1.40.jar
		* CoFHAPI (1.7.10R1.0.12) from Fluxed-Crystals2-1.0.3.jar
		* CoFHAPI|block (1.7.10R1.0.12) from Technomancy - 0.11.1 - 1.7.10.jar
		* CoFHAPI|core (1.7.10R1.0.12) from Fluxed-Crystals2-1.0.3.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from buildcraft-7.0.13-core.jar
		* CoFHAPI|fluid (1.7.10R1.0.13B1) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHAPI|inventory (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|item (1.7.10R1.0.12) from Fluxed-Crystals2-1.0.3.jar
		* CoFHAPI|items (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from Fluxed-Crystals2-1.0.3.jar
		* CoFHAPI|world (1.7.10R1.0.13B1) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|audio (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|gui (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|gui|container (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|gui|element (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|inventory (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|render (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|render|particle (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|util (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|util|position (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|world (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* CoFHLib|world|feature (1.7.10R1.0.3B2) from CoFHCore-[1.7.10]3.0.3B2-294.jar
		* ComputerCraft|API (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|FileSystem (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Lua (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Media (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Peripheral (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Permissions (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Redstone (1.74) from ComputerCraft1.74.jar
		* ComputerCraft|API|Turtle (1.74) from ComputerCraft1.74.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.2.19.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.2.19.jar
		* GardenCoreAPI (1.0.0) from GardenStuff-1.7.10-1.6.3.jar
		* IC2API (1.0) from Fluxed-Crystals2-1.0.3.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|core (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar

**Comment by ThunderSourceLLC** [comment]
Also, the pack works great without them. I'd really like to include them if I can find a fix... :)

**Comment by Keridos** [comment]
You have java 6 which is an ancient version, upgrade your java to at least 7. The mod is already marked as non compatible with java 6 on curseforge.

**Comment by ThunderSourceLLC** [comment]
I have Java 8 U 45.

**Comment by Keridos** [comment]
But your Minecraft does not use that, check your Log it states clearly you use "Java Version: 1.6.0_65, Apple Inc."

**Comment by ThunderSourceLLC** [comment]
Okay. I'll try it. I typed this into terminal and got this so I know I have 8 but 6 might still be there.

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by ThunderSourceLLC** [comment]
I deleted Version 6 and it worked. Thank you, I didn't realize I still had 6 on my computer.

**Comment by Keridos** [comment]
Glad I could help!
