### ISSUE TITLE
(Feature) Towny integration

### ISSUE THREAD

**Issue by ThunderSourceLLC** [OpenModularTurretsTeam/OpenModularTurrets#130]
I've done some work with Java for modding and Bukkit Plugins.... I was wondering if you'd be interested in helping me create a mod addon that gives OpenModularTurrets compatibility with Towny (and others like Factions).

I was thinking of either:
A) making an OMT (OpenModularTurrets) addon that adds player lists to turret trusted players, so you can add groups of players in addition to individual players. These groups would be managed by the server-side OMT that keeps record of every group. Then I'd have a towny addon plugin that updates those OMT groups to equal the towns and the players within the towns. Upon players joining and leaving towns, the lists would be updated and since the turrets reference the dynamic list they will update instantaneously.

or...
B) if the authors of OMT want to add a grouping feature themselves or have another idea of how to do this I'd love to hear it.

What i'm looking for is having it set up that on my server (and others with Towny or Factions), turrets will not target players belonging to the identical town as the turret owner.

Let me know what your thoughts are, this is a flat-out question/feature-request. I really have no idea how it would be best to attempt this, but I have some ideas.

**Comment by Keridos** [comment]
That might be integratable into OMT fairly easy if towny has a good API to use for that.

**Comment by ThunderSourceLLC** [comment]
To my knowledge, Towny has an exceptional API. I'll do some poking around and see what I can find.

**Comment by Keridos** [comment]
I'd be willing to let you write the integration, if you want to do it, I can give you info on how to do that trusted player stuff in the code. @Poenjabiesous you ok with that?

**Comment by Poenjabiesous** [comment]
Sure, sounds good. Ill help where im needed as well.

**Comment by Keridos** [comment]
@ThunderSourceLLC You want to do that? If yes, just fork the repo here and write a class for it in the compatability package in the source.

**Comment by ThunderSourceLLC** [comment]
Okay, I'll take a look and see what I can accomplish. It shouldn't be terribly difficult. I'm thinking OMT could have an option in the config that enables/disables this feature of plugging into certain server plugins.

**Comment by Keridos** [comment]
And if you have any question, ask here or in the esper IRC on #OpenModularTurrets

**Comment by ThunderSourceLLC** [comment]
Roger that. I'll get to work shortly.

**Comment by Battelman2** [comment]
(gaming account for Thunder Source LLC) I'm forking the project and will see if I can make something happen.

**Comment by Battelman2** [comment]
I believe I have a way of accomplishing this. I will be working on it for a couple day likely and then I'll let you know.

Also, most of the code will go into the Compatibility Package, but I will need to insert a few lines in TurretHeadUtil to check for allied players. It's just an extra if statement in the targeting if-nest.

**Comment by Battelman2** [comment]
A lot quicker than expected... I pushed a new version on my fork. (https://github.com/Battelman2/OpenModularTurrets). It may need adjusting, but the concept is there. I also wonder what else is necessary to add since Towny is server-side only and OMT is both, so I don't know if the client will complain or anything. I'd imagine that there would be some special addition necessary to get a forge mod to interact with a bucket plugin. I have not done work with Plugin-Mod relationships, only plugins and mods independently. Let me know what should be changed, thanks for taking the time!

Also, I set the boolean value to by default say towny is not present. There should be an addition in the OMT server-side config with which server administrators can enable it.

**Comment by Keridos** [comment]
You can do a world.isRemote() to check if stuff is done serverside like we do it in most of the TurretBases functions. We just need to figure out on how to get the info if towny is present in our modcompatability class.

**Comment by Battelman2** [comment]
So is the last thing we need, besides adding .config variables, an actual hook into Towny? It seems the code is all there for the functionality, so all thats left should be hooking Towny into the compat class. Let me know if you have an idea as to how this works, otherwise I'll go do some digging and try to find out. After that, it should be pretty much ready for deployment.

**Comment by Keridos** [comment]
The only thing we need to consider is that setting the config variable to true will most likely cause the server to crash when towny is not available.

**Comment by wbattel4607** [comment]
Is there a way to check if Towny is available? Unfortunately the server mods load before the server plugins so we can't check if Towny is active. Though I just though of something... we could put the whole thing in a catch statement to do the following:

- Launch server, OMT will load without Towny Integration, Towny may or may not load later.
- OMT will check (After full server start, including plugins, or on server stop) if Towny ever activated. If not, nothing changes. If so, OMT will update the config to enable it automatically.
- Restart server to activate OMT+Towny Integration. OMT will expect Towny to still be present after restart.
- If Towny is removed after OMT enabled it, OMT will catch it in the try-catch and cancel the initialization of the integration and revert the config to exclude Towny.

Let me know what you think.

**Comment by wbattel4607** [comment]
ugh.. forgot I'm on another alt account. Sorry for the confusion. This is my personal, the other are my Work and Gaming. Oops.

**Comment by Battelman2** [comment]
(Repost)
Is there a way to check if Towny is available? Unfortunately the server mods load before the server plugins so we can't check if Towny is active. Though I just though of something... we could put the whole thing in a catch statement to do the following:

- Launch server, OMT will load without Towny Integration, Towny may or may not load later.
- OMT will check (After full server start, including plugins, or on server stop) if Towny ever activated. If not, nothing changes. If so, OMT will update the config to enable it automatically.
- Restart server to activate OMT+Towny Integration. OMT will expect Towny to still be present after restart.
- If Towny is removed after OMT enabled it, OMT will catch it in the try-catch and cancel the initialization of the integration and revert the config to exclude Towny.

Let me know what you think.

**Comment by Keridos** [comment]
We could also look for Towny before WorldLoad or something like that. That could work also, we just need to figure out when to check.

**Comment by Battelman2** [comment]
Either/or. Whatever you think is best. I'f be winning to test on my server if you want to make it work either way and see which is best.

**Comment by Keridos** [comment]
Is there a way to get the cauldron stuff via the build.gradle as a dependency?

**Comment by Battelman2** [comment]
Not sure, I'll investigate.

**Comment by Keridos** [comment]
Also a really worrysome thing, maybe an addon for that would be better, I think Cauldron is DMCA'd so that might be a bigger issue with licensing. When that does not work we might need to put that into an addon developed with cauldron as base and not forge.

**Comment by Battelman2** [comment]
Cauldron is DMCA'd but KCauldron (successor) is not. An Haddon would be fine though if its doable.

**Comment by Keridos** [comment]
The thing is that adding towny to the build process will probably need cauldron as dependency and that would probably go really derpy with forge as base and conflict a LOT.

**Comment by Battelman2** [comment]
Well, the only thing I can think of is having some sort of addon server side that acts a a middleman. I understand your logic I am just looking for a workaround. Maybe I should get in touch with Towny devs and get their input.

**Comment by Battelman2** [comment]
And to my knowledge, KCauldron is perfectly okay with this sort of hook-in. Cauldron got DCMA'd pretty heavily but KCauldron is an entirely different entity legally speaking. I know that some mods do use KCauldron dependancies, the most well known being Dynmap for Forge.

**Comment by Poenjabiesous** [comment]
What is the progress on this?

**Comment by Battelman2** [comment]
Waiting to figure out how to build a dependency against KCauldron.

**Comment by Ske39** [comment]
following the train of thought of the original request. I understand there are some issues with supporting towny, but how about factions?

**Comment by Keridos** [comment]
If they are forge mods (not cauldron) then maybe yes, cauldron support would require os to toss all our build configs and dev workflows at this very moment.

**Comment by Poenjabiesous** [comment]
Is this implementation dead, or is there any feedback here?

**Comment by spannerman79** [comment]
As far as I know as long as a FakePlayer is declared properly then protection based systems can use it - example being https://github.com/OreCruncher/ThermalRecycling/wiki/Fake-Player

**Comment by Battelman2** [comment]
My apologies for being off of the radar. I would still like to pursue this at some point but am flustered with school for the time being. I'm convinced that we can find a way to do it, I just do not know at this time. It is at the mod authors' discretion as to whether this should still be considered for implementation. I agree that the DMCA was an issue, but time has passed and in the near future I think we can find a valid hook-in. The only thing we are having a hard time with is that server-side mod to plugin relationship, which exists in some places but I'm not an expert in this area.

**Comment by spannerman79** [comment]
It doesn't need to be built against KCauldron or any other mod or build environment.

Take a look at https://github.com/OreCruncher/ThermalRecycling/blob/master/src/main/java/org/blockartistry/mod/ThermalRecycling/util/FakePlayerHelper.java for example. And you can see some of that code was "borrowed" from buildcraft and I know for a **fact** that I can restrict or allow the fakeplayer [BuildCraft] without anything special in place done on behalf of the BuildCraft dev team.

Personally I don't use Towny as I use Grief Protection Plus as it gives much finer control then what Towny does.  Although towny already has a system in place for FakePlayers - the mod just needs to use it - that is all.

**Comment by Battelman2** [comment]
@spannerman79 thank you for the advice. Assuming the mod authors are permitting, I will look into this in the near future. I think you're on to something.

**Comment by spannerman79** [comment]
Even if it wasn't for a permission based system like Cauldron/KCauldron ForgeEssentials needs a FakePlayer as well so there is no avoiding it.

If there is something similar within Forge 1.8 it will need to be added as OMT has 1.8 releases and there is [ForgeSponge](http://files.minecraftforge.net/spongepowered/)

**Comment by Keridos** [comment]
I think the original issue was not directly directed at the compat for our turrets to do stuff in protection plugins but to have whitelists and blacklists for targets from Towny. If required I or @Poenjabiesous can add in the fake player code to allow our Turrets to shoot in protected regions. The Towny Compat module either needs to be compiled against some form of API for the Towny related stuff. That would most likely mean it needs to be compiled against KCauldron as well, which is why I proposed to put it into an external module. If required we can add in API documentation on how to add/remove trusted players.
