### ISSUE TITLE
Trusting and OPs

### ISSUE THREAD

**Issue by Aphex124** [OpenModularTurretsTeam/OpenModularTurrets#131]
Is there any way you can make it so that there is a global trusted players list, so admins and etc can go to bases without being shot up. Ive had this problem with trying to be in vanish and going to somebody's base. Also maybe the feature for OPs being able top break a players turret.

**Comment by Poenjabiesous** [comment]
What version of OMT are you running?

**Comment by Keridos** [comment]
There is no global trusted list, but the admin can just go into creative and done. Turret will not target creative players.

**Comment by Aphex124** [comment]
Ok then, I must not have been in creative when trying to break a turret. Thank you very much.
