### ISSUE TITLE
V2.2.0 Milestone checklist

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#133]
V2.2.0 checklist, for your (and my) convenience. 

Add whatever I missed and was discussed.

- [ ] Towny stuff
- [ ] Localizations
- [ ] Electric Fences?
- [x] Multitargeting
- [x] Cloakable Turrets

**Comment by Poenjabiesous** [comment]
Moving some of this out, I want to do another release before v2.1.0, which will be the big towny integration release.

**Comment by Keridos** [comment]
Why not make the current version 2.1.0 and the towny relase 2.2.0?

**Comment by Keridos** [comment]
Btw, using githubs milestone feature we do not need such issues, just take a look at the milestones section and you can see all related issues and their progress.
