### ISSUE TITLE
{SMP} configure buttons are vanished

### ISSUE THREAD

**Issue by NoireMann** [OpenModularTurretsTeam/OpenModularTurrets#135]
So, thats it.

In singleplayer i can see the configure, drop turret/base buttons, and i can change the trusted list.

But on SMP it is impossible, because these buttons are vanished or kinda like that O_o

Please, check this.
Thank you.

**Comment by Keridos** [comment]
What did you do exactly, in all our testing the mod worked fine in SMP.

**Comment by Poenjabiesous** [comment]
Are you using a cracked client by any chance?

**Comment by Keridos** [comment]
Ah yeah, that can obviously cause that.

**Comment by NoireMann** [comment]
I am using self-written Minecraft launcher.

Maybe it is related to the authlib?

**Comment by NoireMann** [comment]
In addition, i didnt had any problems with trusted players adding in v.1.x., when it was configuring by an item.

Seems strange.

**Comment by Poenjabiesous** [comment]
The reason for this happening is the complete rewrite the mod's ownership had to undergo- With 1.7.10 players could start changing their player names, so we couldn't use player display name as owner anymore. We now use the player's UUID from Mojang itself (Mods like TE also use this method) to dictate ownership.

You will find if you place something like a tesseract with private ownership, you will run into the issue of not being able to set it to private channels because it won't be able to find the player's UUID.

Something in the launcher is causing the UUID to be null.

**Comment by NoireMann** [comment]
I can be 100% sure that the latest TE4 with private security system works well with my launcher.

**Comment by Poenjabiesous** [comment]
After quickly testing with AtLauncher, FTB Launcher, Vanilla and even Technic, I can comfirm that everything works as intended in SMP.

Something interesting though:

I tested (just for the sake of being thorough) a cracked version of the Technic launcher as well; One that only requires a Username, not a password. Got into the game, plopped down some turret bases, and saw this:

![image](https://cloud.githubusercontent.com/assets/8829214/8793720/303c8eb4-2f7b-11e5-9b1c-435d77077403.png)

No buttons.

**Comment by NoireMann** [comment]
Fixed.

I`ve just tried another working launcher.

Sorry :P

**Comment by Poenjabiesous** [comment]
No problem!

**Comment by NoireMann** [comment]
Do you have an IRC Channel?

**Comment by Poenjabiesous** [comment]
Yeah, esper.net -> #OpenModularTurrets

**Comment by Keridos** [comment]
BTW: When I do not react, just write my name like "Keridos:" +  Your message, I will definitely read it later since I have a bouncer that relays messages to me later when I am not logged in at any time.

**Comment by dakakeisalie** [comment]
Playing FTB Horizons: Daybreaker from FTB Launcher does not show any config buttons on a multiplayer server, but does on singleplayer
![singleplayer](https://cloud.githubusercontent.com/assets/10680583/11704838/f31773c8-9eb0-11e5-951b-c13aab836e2f.png)
![multiplayer](https://cloud.githubusercontent.com/assets/10680583/11704837/f314e8a6-9eb0-11e5-8db2-30e5816cf981.png)

**Comment by Keridos** [comment]
We can confirm that this works as intended, the issue must likely be within mojangs services or the server set to offline mode.

**Comment by Poenjabiesous** [comment]
I can second Keridos on that, we've been through this issue many times and its always related to the server not being able to talk to Mojang servers.
