### ISSUE TITLE
3.0.0: subblocks

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#136]
I have implemented a metadata based subblock in my own floodlights mod and so it happens, I know what is needed to be done for that. So I will make this suggestion: For later blocks we add in we can add in subblocks which drastically reduce the number of block IDs OMT is going to use. When we do a non backwards compatible version once too, we could also apply that to the rest of the blocks.

**Comment by Poenjabiesous** [comment]
Yes, the next major release should use subblocks. The mod's scope is growing and with it the amount of blocks. Let's do this before it becomes problematic.

**Comment by Poenjabiesous** [comment]
Agreed. Doing some housekeeping- closing this.

**Comment by Keridos** [comment]
Implemented in my dev branch.
