### ISSUE TITLE
Camouflage activation weird

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#137]
Can we change the camouflage to only update when shift clicked with a block instead of doing that on every rightclick? I find It a bit irritating like it is atm.

**Comment by Poenjabiesous** [comment]
Yes, we can.

**Comment by Keridos** [comment]
There is just one issue there, normally shift rightclicking places the block. Mmh, maybe an item to change the camouflage?

**Comment by Poenjabiesous** [comment]
Now I remember why I didn't use shift for the camo placement. Let me think about this one a bit.

**Comment by Poenjabiesous** [comment]
I agree with the item that does the camo stuff. Lets get the logic stuff for this out of the onBlockActivated method.

**Comment by Keridos** [comment]
We just need a way to set the block, maybe per crafting?

**Comment by Forecaster** [comment]
You could have a slot in the block that you put the desired camo block into. Or in the item I guess if you handle it that way.

**Comment by Poenjabiesous** [comment]
I'd rather do it through an item than crafting/container slot.

**Comment by Poenjabiesous** [comment]
Right so instead of our previous discussions, I've made the camo activation play along a bit nicer. Turret base gui will now open while holding anything that cannot be used to camo a turret with, e.g: items, blocks with tile entities, etc. I find this to be very fluid.
