### ISSUE TITLE
(Feature) Addon/ammo turret inventory slots only

### ISSUE THREAD

**Issue by NoireDvachevsky** [OpenModularTurretsTeam/OpenModularTurrets#138]
So, that would be nice, if u can make turret`s inventory capable to include only turret addons and ammos.

The point is that players on server are using turrets like an unbreakable safes. Thats not fair :P

Thanks!

/edit by Keridos for clarity, the plan:

- [ ] add a whitelist for ammo default cobble, planks and all ammo and a new special ammo slot that checks against this list.
- [ ] add a config to specify the whitelist with the additional stuff, default cobble and planks. Though not entirely sure how to exactly implement this.

**Comment by Poenjabiesous** [comment]
The problem with this is that the Disposable item turret can use anything as ammo, so limiting bases to only accept ammo/addons/upgrades would render that turret 'useless'. @Keridos, what do you think?
I suppose we can limit the input to only cobble/dirt (things of that nature) ?

**Comment by NoireMann** [comment]
>I suppose we can limit the input to only cobble/dirt
This. Or maybe you can create a Disposable item turret Ammo, for ex Cobblestone Orbs?

**Comment by Palius84** [comment]
Why not just add a whitelist in the config, and put in those items, that way servers can choose which items they feel can be put in there.

**Comment by Keridos** [comment]
We could make the orbs an ammo craftable from any item, but not reversible. Then we can just change isItemValidForSlot(params) to return false when trying to insert anything wrong.

**Comment by Battelman2** [comment]
+1

**Comment by Poenjabiesous** [comment]
Yes, i think we can have an item that will turn any item/block in a crafting grid (when placed alongside) into these orbs. Thoughts?

**Comment by Keridos** [comment]
Yes, or a block that converts those

**Comment by Poenjabiesous** [comment]
Yes, I like that.

**Comment by lellasone** [comment]
Perhaps with a config setting not to require it?

**Comment by Keridos** [comment]
After thinking about this; I do propose that adding a whitelist for the disposable turret might be far easier to implement and would remove the clutter in JEI.
