### ISSUE TITLE
(Feature) Configurable turret base placing limitation in area

### ISSUE THREAD

**Issue by NoireMann** [OpenModularTurretsTeam/OpenModularTurrets#139]
Hello again!

On a large servers lots of turret bases in a single chunk are causing heavy lags and TPS jumps.

So that would be nice if you add a turret placing check, for example, turrets can be placed only if there are no other turrets in 3x3x3 blocks area. (configurable area, i think :P)

**Comment by Keridos** [comment]
I generally approve of that!

**Comment by Poenjabiesous** [comment]
Yeah, we can do a check like that. Should be quick.

**Comment by Keridos** [comment]
Let me do that, I know exactly on how to accomplish that!

**Comment by Poenjabiesous** [comment]
I got this one as well.

**Comment by Poenjabiesous** [comment]
I'm not sure if this is still valid after everything that has changed. Can I close this?

**Comment by Poenjabiesous** [comment]
The TPS lag issue was fixed in a previous release. I see no more reason to implement this.
