### ISSUE TITLE
(Feature) Multitargeting system for a single turret base

### ISSUE THREAD

**Issue by NoireMann** [OpenModularTurretsTeam/OpenModularTurrets#140]
Could you please add multitargeting to a single turret base?

6 turrets killing a single zombie, while there are lots of them around seems inpractical :(

**Comment by Poenjabiesous** [comment]
The turrets all target independently; if all of them were targeting the same entity, It means:

1. All 6 turrets could see the entity.
2. All 6 turrets could see (LOS, range) only the that entity.
3. All 6 turrets could only target that one entity.

**Comment by Keridos** [comment]
We can still add in a check to make them not all target the same. Even now they target the closest enemy to them, that often makes multiple shots wasted since it kills the target after 2 or 3 hits, the rest of the bullets are simply wasted.

**Comment by Poenjabiesous** [comment]
Okay. We add a check for that. Should also be easy to do.

**Comment by Poenjabiesous** [comment]
Thing is, what if you want to then have all turrets attack a single entity? A friend of mine uses the turrets in a wither grinder, and wants all of the available turrets to attack it at once.

**Comment by NoireMann** [comment]
is it possible to make a configurable multi/single? For ex in config-menu button in UI?

**Comment by Poenjabiesous** [comment]
Yes, it's possible.

**Comment by NoireMann** [comment]
Great! More configurability - more epicness! :P

**Comment by Keridos** [comment]
Maybe an upgrade to make it target a specific entity ID only?

**Comment by NoireMann** [comment]
Sounds nice, but i think general multiaiming should be realised.

**Comment by Poenjabiesous** [comment]
I'm having a hard time finding a solution for this that isn't expensive.
