### ISSUE TITLE
(Feature) Ground spikes

### ISSUE THREAD

**Issue by NoireMann** [OpenModularTurretsTeam/OpenModularTurrets#141]
What about adding ground defence spikes?

Simple, poisonous, incendiary? Like there were in ICBM mod? Or even some new types of them!

**Comment by Poenjabiesous** [comment]
I feel that the current fences and upcoming electric fences would suffice to the use case of ground spikes (passively keeping entities out of specific areas, cactus-style damage on touch). I can't see a practical case where the spikes can do what the fences won't.

**Comment by Keridos** [comment]
Though the visuals of tank traps are appealing :D

**Comment by Poenjabiesous** [comment]
I think an implementation such as this would just replicate OpenBlocks spikes.

**Comment by NoireMann** [comment]
I think that would be useful in creating traps and grinders. For ex Vietnamese spike-trap :D

**Comment by Keridos** [comment]
I think replicating other mods stuff or rather reinventing it should not hinder us in putting appropriate content into OMT.

**Comment by Zaflis** [comment]
Just for reference or maybe hints, there are 4 tiers of spikes in Extra Utilities - wooden, iron, golden and diamond. They do different things, some give xp orbs, some give loot etc. If you still want to reinvent it, your call. At least i'm not aware of spikes that would be visually almost flat as pressure plates.

**Comment by Poenjabiesous** [comment]
Closing this.
