### ISSUE TITLE
(Feature) Turret per player limitation?

### ISSUE THREAD

**Issue by NoireMann** [OpenModularTurretsTeam/OpenModularTurrets#142]
Turret per player limitation might be helpful for optimizing gameplay and performance on servers!

**Comment by Poenjabiesous** [comment]
We thought of this even before the v2.0.0 release. The decision was that there are already tools and plugins out there to manage this kind of thing, IMO it should not be the mod's  responsibility to cater for  administrative things such as this. It would be like TE having config to limit the amount of machines you can have- too many of those can also cause lag. In fact, too much of any tileEntity will put strain on a server.

**Comment by Poenjabiesous** [comment]
With the limitation on the turret base per area config and the configurable turret tick rate, I feel that this will offset server side load enough to not worry too much about this.

**Comment by Keridos** [comment]
We might need something like this for the control addon.
