### ISSUE TITLE
Turret global configurable tick rate

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#143]
On the topic of performance optimization, I would like to introduce a configurable tick rate for turrets. At the moment, they look for targets once every tick; I would like that configurable. This should bave a massive impact on server-side mod performance, with minimal practical impact.

**Comment by Battelman2** [comment]
+1

**Comment by Poenjabiesous** [comment]
Done.

**Comment by Poenjabiesous** [comment]
Default turret tick rate will be 10, if target is null. In other words, If the turret's target is null, it will wait 10 ticks before looking again. If it finds one, tick rate becomes 1:1 for the duration of the attack.
