### ISSUE TITLE
Computer access not working when only OpenComputers is installed

### ISSUE THREAD

**Issue by pingex** [OpenModularTurretsTeam/OpenModularTurrets#144]
Hello,

As a big fan of OpenComputers, I use this mod over ComputerCraft. Since the new release of OMT which has an integration for OC/CC I wanted to try this new feature.

I'm now running into the issue where turrets returns "Computer access deactivated!" on any function call. I didn't forget to place a serial add-on in the turret. This happens when I have only OC installed. If I start MC with both CC and OC installed, the functions works properly. So I think the OMT doesn't check correctly whether OC is installed (or doesn't check at all ?).

Can you have a look on this issue ? I don't want to install CC just to make the computer integration work properly with OC.

Anyway thanks for this awesome mod you have created :)
-Pgx

**Comment by Poenjabiesous** [comment]
Hi Pingex

Do you mind copy/pasting your Lua code here? 

I might have a theory.

**Comment by pingex** [comment]
Hi,

I just did `=component.tierFiveTurretBase.getActive()` in a lua shell,
but the problem is the same with any function.

-Pgx

**Comment by Poenjabiesous** [comment]
Found the issue: We are doing this check:

 if (!ModCompatibility.OpenComputersLoaded || !ModCompatibility.ComputercraftLoaded) {
            return false;
    }

which will always return false if both mods aren't installed.

Thanks the feedback, will let you know when the fixed dev build is done. This fix will only be released in V2.2.0, but you can use the dev build in the mean time.

**Comment by pingex** [comment]
Thanks ;)

**Comment by Poenjabiesous** [comment]
There you go:

https://www.ironhide.de/jenkins/job/OpenModularTurrets/155/artifact/build/libs/OpenModularTurrets-1.7.10-2.1.0-155.jar
