### ISSUE TITLE
Feature Request: Cloakable Turret / Pop Out Turret

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#148]
We can make this very very easily by just disabling the rendering of the turrets on a base when no target is in range. Make it accessable via addon. @Poenjabiesous what do you think?

If you want, I can implement that.

**Comment by Forecaster** [comment]
Maybe render a flat box on the base so you can tell something is there? (suggested by Player)

**Comment by Keridos** [comment]
Yeah, good idea.

**Comment by Poenjabiesous** [comment]
This can be an addon. Will require some time to get the animations right, but will be worth it. I'll pick this one up.

**Comment by Poenjabiesous** [comment]
Done
