### ISSUE TITLE
Change: Rename Machine Gun Turret to Gun Turret

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#150]
By Forecaster on IRC. The turret fires rather slow so machine gun does not make that much sense...

**Comment by Poenjabiesous** [comment]
Refactoring the name is quite a task, not to mention the unlocalized name is machineGunTurret. I understand the argument, but I feel that calling a turret with one of the highest base attack speeds "Machine Gun Turret" to be valid. Especially if you start playing with the upgrade system.

**Comment by Keridos** [comment]
We do not need to change the internal name, just the lang files.

**Comment by Poenjabiesous** [comment]
Okay, lets do it.
