### ISSUE TITLE
Config and question

### ISSUE THREAD

**Issue by Carbon-Ghost** [OpenModularTurretsTeam/OpenModularTurrets#152]
Hi, wanted to request, can you add a config to disable blocks, fences and other non turrets related stuff ? It's just I don't need them because I add my own ^^

Also, small question, is the rocket launcher turret really firing homing missiles ? Because in the tool tip it says so but visually speaking I tried it versus dragon ( it didn't damage him btw, intentionnal I guess ? ) and, visually speaking didn't hit him all the time :/ 
If not may you add it ? xD

Last thing, may we have a json file for adding custom turrets ?

**Comment by Keridos** [comment]
Gonna add config options in. No Idea about the targeting issue.

json files for turrets are not good, because you also need to do models and the rendering stuff.

**Comment by Carbon-Ghost** [comment]
I am ok with the need of models, me and someone else forked part of your mod a while ago to test custom turrets, but we'd rather have a json file with them, WAYYYYYY EASIER imo, then for model you can choose one of the defaults ones are add a custom one in the same folder as the json file and reference the model with the json file :)

also, may you add the homing ability if it's not in there ? Doesn't seems to work ;( 
If you dunno how to do it, take project E archangel smites projectiles homing part of code in the worst case, but might be visual but rockets doesn't appear to follow stuff, they are VERY PRECISE but I can't say if they actually home ^^

Last thing : The friendly fire option doesn't work, I tried it but my own turrets projectiles hurt me ;(

Also, not next update, not next next update but the one after, we will try to add compat to OpenModular Turrets with IC2 classic, may you think about it please ?

**Comment by Carbon-Ghost** [comment]
Ah nice ;)

**Comment by Keridos** [comment]
Thing is I have no clue about how to properly parse a json yet. Doing a class that adds turrets from data should not be that hard. I can probably do that. So we just define the model, the projectile and then just the parameters like fire rate, damage etc.

**Comment by Carbon-Ghost** [comment]
And projectile special properties like AoE damage, explosion, fire, speed, gravity, homing ^^

Also, you really don't know if your rockets home although you made the mod xD ?

**Comment by Keridos** [comment]
I did not make the whole mod, @Poenjabiesous is the original author of the mod and that stuff was in even before I started authoring here. For that I would need to get into the targeting stuff and the rocket projectile code, did not really do much in there except for small bugfixes.

**Comment by Carbon-Ghost** [comment]
Can you still check if homing works and that the "bug" I reported to you is only visual ? 

Also having so much fun with this mod, I made all turrets overpowered, with them shooting 20 times a sec and having 2,5 hearts of damage, or shooting less frequently but having more damage output, in the end all tier 2-5 turrets have same DPS but different properties, and Project E allows me to have infinite projectiles, it's so fun to watch rapid fire grenade launcher with spread upgrades :D 
Also rocket launcher is quite funny xD

Last thing though, may you add a proper projectile to the disposable turret ? Stone rounds/pebbles seem ok, but the fact that it fires EVERYTHING is kinda broken and make no sense ;P

Lastly, the deaths are hilarious but can you add a config to disable the funny death messages, I just prefer being a bit serious with these turrets ;)

**Comment by Keridos** [comment]
I can try to check on the homing thing. The ammo thing for disposable is being worked on as far as I know. For the chat messages I am gonna add in a new config setting. Btw, please create multiple issues for different things, makes managing the issues far far easier for us.

**Comment by Carbon-Ghost** [comment]
Yeah I know that, sorry, this whole "issue" began to be a discussion xD
Have a good night ;)

**Comment by Poenjabiesous** [comment]
Hi Guys.

The rockets are no longer homing in 2.X.X. This was done on purpose.

**Comment by Keridos** [comment]
The death messages are note being sent from our mod apparently, that may be CoFHCore, check its configs.

**Comment by Carbon-Ghost** [comment]
Ah kk for death msgs ^^
Yup, Speiger's IC2 classic xD
Also, may you add back the homing ability to rockets and have a config if you really don't want them to be homing by default ? I can try make them homing by myself but I am pretty sure I will break the mod xD

Really want homing rockets :3

**Comment by Poenjabiesous** [comment]
After adding the scattershot upgrade, I made the decision to have rockets act as normal projectiles. If a rocket is homing, and you spam a turret base with scattershot upgrades, all 9 rockets that gets shot will all hit their target at the same time. It won't even give the target a fighting chance. It will be a really, really bad idea to make them homing again; the pack will be taken out of the mainstream modpacks for being overpowered.

**Comment by Carbon-Ghost** [comment]
But I love overpowered, in my modpack, all turrets are overpowered to counter heavily armored people ( gem armor, nanosuit, thaumcraft armor... ), my suggestion is to then re add it and add a config to disable homing if it's necessary :) It's quite awsome to have a "shotgun" like weapon with homing projectiles ;)

**Comment by Keridos** [comment]
The Railgun should have armorpen and if that does not work, just tell me.

**Comment by Carbon-Ghost** [comment]
if you wonder how overpowered I made them, I gave them all a RPS of 50 hearts, most of the turrets got their damage lowered a bit but have a 20rps rof, exception being the railgun with 5 rps and the grenade with 10 rps ^^ But I want AND need them overpowered, because one may wear an armor which will basically kill the whole purpose ;P 

Anyway, my suggestion is reAdd it but disable it by default in configs ;)

**Comment by Carbon-Ghost** [comment]
And no I am still near invincible in gem armor, from time to time I take damage but I heal almost instantly ^^'

**Comment by Poenjabiesous** [comment]
The railgun ignores armor. I'm sorry but I can't see a good enough reason to make rockets homing again at this point, it does not make sense from a balancing perspective.

**Comment by Carbon-Ghost** [comment]
Well, config ? Disable them by default, or tell me where is the code for that, if I want to fork and make my own small version with homing rockets ^^

**Comment by Poenjabiesous** [comment]
Its in EntityRocketProjectile if I can remember correctly. Go for it.

**Comment by Keridos** [comment]
We can add a config option for that too...

**Comment by Poenjabiesous** [comment]
I just feel that its not standard abstract projectile function to be homing or not. If we add config for its, it must be a config option with all projectiles.

**Comment by Carbon-Ghost** [comment]
I want homing stuff :D My goal is too make turrets a very expensive but almost perfect way to defend yourself, also railgun is failing at armor piercing, unless gem armor is ignored xD

**Comment by Keridos** [comment]
Gem armor?

**Comment by Carbon-Ghost** [comment]
Project E armor, is like EE2 old Gem armor, grants you air gliding, 90% damage reduction ( might actually be near 100% in the remake ), creative flight if you tap double space, infinite food, high speed movement, water and lava walking, fast falling if you press shift, fall damage immunity, fire immunity, water breathing and more ^^

**Comment by Carbon-Ghost** [comment]
Well, in the end will you guys make a config for that or no ?  :c 

But config or not, small question here : https://github.com/OpenModularTurretsTeam/OpenModularTurrets/commit/80f90a0e870f5bda0c56f04001e49809cfef57b3 , so if I replace the new code by the old one, it should work like before right ? Well small question, the last lines with unlocalisation, what should I do here, since you changed accuracy with scattershot...

**Comment by Keridos** [comment]
@Carbon-Ghost I can easily change the armor pen from dealing damage to simply reducing the health of the target by a fixed amount.

**Comment by Carbon-Ghost** [comment]
That would be a solution, but for the homing thing, what should I do for line 20 of the scattershot upgrade @ https://github.com/OpenModularTurretsTeam/OpenModularTurrets/commit/80f90a0e870f5bda0c56f04001e49809cfef57b3 ?

**Comment by Keridos** [comment]
I'd say deactivate homing for those, 9 homing missiles per shot seems really broken as Poenja pointed out.

**Comment by Carbon-Ghost** [comment]
If you guys want to, I think it's quite cool xD But anyway, to I simply need to change and add the homing code back or should I revert everything to the state it was before ?

**Comment by Keridos** [comment]
Add the homing code back but with a config setting, Imo we can even put that into the mod itself here.

**Comment by Carbon-Ghost** [comment]
Forked mod for testing purposes, gonna try to add homing back, dunno how to add config though never tried before ^^'

**Comment by Keridos** [comment]
Simple, put a new public variable in the confighandler, copy one of the functions that set that in the init() function and just replace every changed thing in the copy.

**Comment by Carbon-Ghost** [comment]
public static boolean rocketsCanHome;
rocketsCanHome = config.get("miscellaneous", "Can rockets fired by the rocket launcher turret home on targets ?", false).getBoolean();
        But wait, one thing I kinda missed here, I didn't understood, how do I refer to the homing ability function ? Walp xD

**Comment by Carbon-Ghost** [comment]
Do I need to create rocketsCanHome in the projectile class or should I refer to it in another way ?

**Comment by Carbon-Ghost** [comment]
Ok, only was able to make homing back, not tested though, configs confuses me too much xD ( never tried doing one before ).

**Comment by Carbon-Ghost** [comment]
So, now I need to use gradlew create the .jar... except, it's a long process since I haven't prepared anything yet... xD dunno if I will finish today, but if you guys add a config for that directly, you would kinda save me because all this time I am trying to make this work, I am tired =.=

**Comment by Keridos** [comment]
You can simply call the variable from the ConfigHandler class like
```
if (ConfigHandler.canRocketsHome) {

} else {

}
```

**Comment by Carbon-Ghost** [comment]
And I need to put this in the projectile file for the homing code ?

**Comment by Keridos** [comment]
I guess so. and btw: if you do not know how to even do that, before forking and maintaining a fork you should really learn how to program. The config stuff is plain, basic java stuff for beginners.

**Comment by Carbon-Ghost** [comment]
I know basic of Java bases, but I never had a chance to use it, and due to this fact I am kinda unexperimented ^^

**Comment by Keridos** [comment]
By the way, use an IDE like intellij IDEA or eclipse to make those changes. The code you submitted was not compiling, nor working at all. Within those IDE's you can also check if the code works by just launching minecraft and testing.

**Comment by Carbon-Ghost** [comment]
Yeah I really should do that, I changed directly on github ^^'' Gonna install it now on this computer, my other computer already have it ^^

**Comment by Keridos** [comment]
The rockets are a bit buggy atm also.

**Comment by Carbon-Ghost** [comment]
Due to my tweaks or in general ?

Also gonna investigate on projectile textures on rockets, seems like you forgot to set transparency on one part ^^'

**Comment by Keridos** [comment]
I am gonna close this issue now, if you have anything else, open another issue please

**Comment by Carbon-Ghost** [comment]
Kk ^^
