### ISSUE TITLE
Start using branches

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#153]
I just noticed that currently we cannot fix old issues without releasing already done features in the repository. So I do suggest we using branching (basically copies the repo at a specific commit) and we add all new features into a dev branch and keep the master branch for fixing bugs. When the features for a new major release are ready we merge them into the master branch. If wanted I can take care of doing the merges.

@Poenjabiesous how we do that is that we checkout a new branch once we want to start working on features for a new version. Then put all bugfixes for the old version in the master branch and all the new features into the new branch. After all features are in the branch, we merge it into the master branch. Only someone would need to do the merging if it cannot be simply merged. With IntelliJ IDEA that is super easy though so I suggest I do that.

I can easily add in a second build job on the jenkins for the feature branches btw. if needed.

**Comment by Poenjabiesous** [comment]
Agreed. Doing some housekeeping- closing this.
