### ISSUE TITLE
IC2 Power support

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#154]
Shall I add that in?

Looks like the IC2Classic version from Speiger is compatible to IC2Exp API, so it should technically be possible to just write IC2Exp compat code and it will be automagically compatible to the classic version for 1.7.10.

**Comment by Poenjabiesous** [comment]
Hmmm... Are we still gonna use RF on the bases  (convert EU to RF for display purposes)? Or are we gonna change localizations and config?

**Comment by Keridos** [comment]
If I just do it like I did with my floodlights, I just have an internal EU buffer that fills up the RF first and then fills up to a certain point. We can then either use up the EU or RF first, if we want GUI changing the RF stuff we can just use up the RF; it should be autorefilled, but using the EU buffer first is I think a tad more performant.

**Comment by Carbon-Ghost** [comment]
Can't you guys make an option like Immibis did for his mod where you have choice of which power system you want to use ?

**Comment by Keridos** [comment]
I'd simply put the support in without such a thing because imo that is overkill.

**Comment by Carbon-Ghost** [comment]
I wanted to make turrets only use EU, as RF is more for other things in my modpack ^^ And IC2 classic and GregTech reborn are my main mods in the pack ^^

**Comment by Forecaster** [comment]
An option is to have a power module that you insert that allows the base to accept one of the power types, and disabling crafting of one of those could be used to limit the options if the user wants to?

**Comment by Carbon-Ghost** [comment]
:+1:

**Comment by Keridos** [comment]
Thing is we need to do quite a bit more for that, like changing GUI's.

**Comment by Carbon-Ghost** [comment]
Ah, well we just give ideas, but do it the way you guys think is the best ^^

**Comment by LemADEC** [comment]
Any idea when we can have IC2 support? My modpack is based on IC2/GT, would like to skip on adding a power conversion mod just for turrets.

**Comment by Keridos** [comment]
NO idea, depends on when we will write that stuff. Until now we have not even decided on how to do it.

**Comment by Poenjabiesous** [comment]
I vote for internal EU to RF conversion. That way, all GUI's and other stuff can stay the same. Any objections?

**Comment by Forecaster** [comment]
Sounds fine to me as long as they get EU support!

**Comment by Carbon-Ghost** [comment]
Will it be configurable for the RF only users ? ( I understand them if they want to disable it xD )

**Comment by Forecaster** [comment]
@Carbon-Ghost Disable the EU support? Why? If you only have RF it wont make a difference...

**Comment by Poenjabiesous** [comment]
You will never know that you are working with EU from the turret's point of view. You will simply plug in EU, and the internal RF storage will go up.

**Comment by Carbon-Ghost** [comment]
But then wouldn't that be more "Conventional" to use your own units ? Because technically, RF and EU are supposed to be completely different as RF is not electricity ( though convertible ). It's like mixing mana with Vis :/

**Comment by Keridos** [comment]
@Carbon-Ghost technically it will never be loaded if IC2 is not installed.

**Comment by Carbon-Ghost** [comment]
Well, worst case gonna write config with that, from the little I learned by trying to do it for the homing missiles XD Though it's just I don't find this very conventionnal, I would liked to have some kind of ElectroField-Flux Transformer upgrade ^^

**Comment by Keridos** [comment]
From the technical perspective RF and EU are pretty much the same, comparable with WattHours (Wh) in real life. Personally I think adding an upgrade for this will make turrets only more annoying to setup since they do not have that much upgrade slots.
