### ISSUE TITLE
Camouflage Config Setting

### ISSUE THREAD

**Issue by Carbon-Ghost** [OpenModularTurretsTeam/OpenModularTurrets#158]
Can we please have a config for camouflage, I don't want people using them on turrets in my modpack ^^

**Comment by Keridos** [comment]
:+1: from me!

**Comment by Carbon-Ghost** [comment]
^^ Thanks, also, do I need to redo the homing rockets or no ?

**Comment by Keridos** [comment]
all fixed, check the commits.

**Comment by Carbon-Ghost** [comment]
Ah thx ^^ Sorry :)
