### ISSUE TITLE
Missiles derping a bit when in homing mode

### ISSUE THREAD

**Issue by Carbon-Ghost** [OpenModularTurretsTeam/OpenModularTurrets#159]
MIssiles derp when in homing mode, as sometimes they begin to fly around high health mobs and if other missiles are already here, they begin to bump into the mob, fly above him and trying to hit him but ends up flying above him in circles, kinda like archangel smites arrows in the old EE2, so my suggestion to fix that is to make them explode automatically when near the target, so when the missile knows the target is on the blast radius, it auto-detonate, this will reduces lag caused by this if you have multiple missile launchers or an overclocked one ^^

2 other small derps, but if you overclock a lot / have a high rate of fire missile launcher, when missiles are fired, not all of them are fire from the same spot, and some even are fired slight above the launcher, dunno if it's just visual or not and the missile entity seems to lack transparency, gonna send you the new texture once I finish it ^^

That was it, otherwise no friendly fire works again, hope next release is stable ;)

**Comment by Keridos** [comment]
try the newest build, i derped up some aiming issues where they shoot too high.

**Comment by Carbon-Ghost** [comment]
Kk, also, gonna go in assets see if you indeed forgot the transparency

**Comment by Carbon-Ghost** [comment]
And what about the explosion thing ? Will allow us to not have derping missiles ^^

**Comment by Keridos** [comment]
Why should missiles be transparent???

**Comment by Carbon-Ghost** [comment]
You forgot to erase the white square around the missile I think, not the missile itself xD

**Comment by Keridos** [comment]
I am fixing the texture right now.

**Comment by Carbon-Ghost** [comment]
I also fixed it xD But you ninja'd me ^^
What do you mean by update my comments ? I don't understand you here ^^''

Also, missiles doesn't derp when locked on mob, but still derp when fired, it appears 3 missiles are stacked on top of the other on the turret although it should be one missile that is fired ( no scattershots ) and then all goes in a single line for the target :/

**Comment by Keridos** [comment]
You make double comments and I think even a triple comment. If your comment is the last one, update it, do not make a new comment.

Missiles derped not once for me in my testing in the past hours using the code that currently is on the repo.

**Comment by Carbon-Ghost** [comment]
Try setting a high rate of fire, or overclock them ^^ So you want me to refresh my page ? xD Don't exactly understand what you mean ;P

**Comment by Keridos** [comment]
What is unclear about this: "You make double comments and I think even a triple comment. If your comment is the ***last*** one, update it, do ***not*** make a new comment." ?
Updating means editing which refers to the pencil symbol on your last comment.

**Comment by Carbon-Ghost** [comment]
Ah understood, ^^ Didn't knew that ^^

**Comment by Keridos** [comment]
Sorry for being a bit annoyed by that...

**Comment by Carbon-Ghost** [comment]
It's ok, my fault, should learn english a bit better ^^ I speak french as my main language, ^^

**Comment by Poenjabiesous** [comment]
Is this ticket done?

**Comment by Keridos** [comment]
I think so.

**Comment by Carbon-Ghost** [comment]
Nope, still derping in build 177 :/ When fired from the turret, if overclocked a lot, the missile turret will sometimes appear to fire missiles above him, unless it's visual...

And if a target is dead, still here goes crazy for a moment and then disappears....
Last thing, gonna open a new issue for that as it also concerns other projectiles from other turrets but when a projectile is fired from turrets, if you are looking at it at a certain angle or you are too far from it, it will appear to disappear :/ This one is visual...

**Comment by Poenjabiesous** [comment]
Dont need to make a ticket for that, I already fixed it on my side. Was due to an incorrect hotbox.

If possible @Carbon-Ghost, can this homing issue be fixed and closed as soon as possible. The current master branch cant be used for new releases as it currently is.

**Comment by Carbon-Ghost** [comment]
I think it's visual, and if it's fixed on your side, kk, and it's already closed anyways ^^''

Gonna re-test it, but from what I understand missiles still home on the enemy for a few seconds even though it's dead ^^
