### ISSUE TITLE
When setting I:recycler=100 ammo is still being consumed rarely.

### ISSUE THREAD

**Issue by Teravisor** [OpenModularTurretsTeam/OpenModularTurrets#160]
Sometimes (very rarely though) with setting I:recycler=100 and recycler addon installed, ammo is still being consumed from turret inventory. Noticed it in railgun turret (not sure about others). After about a day or two(real-time) of doing something I've noticed turrets I set up with 64 ammo only have 61-63(varies between turrets). Railguns were shooting a lot during that time. Unfortunately, I cannot reproduce it reliably.
If that matters, I've setup T5 turret bases with railguns on top of them with recycler/solar generator addons and 4xfire rate, 4xaccuracy mods (yes, I know accuracy are useless on railgun). They are installed as a large perimeter, and are not all loaded simultaneously. Running singleplayer game.

**Comment by Keridos** [comment]
Do not see any bug in the code for this at this moment.
