### ISSUE TITLE
turret base configuration buttons not showing server side

### ISSUE THREAD

**Issue by shazzi2k** [OpenModularTurretsTeam/OpenModularTurrets#161]
Hi guys i am having an issue with OpenModularTurrets and cannot seem to figure this out. Running the latest version of OMT (great BTW) the turret base configuration buttons are not showing when on a server however do show in singleplayer  both client and server are using both same versions.

Any ideas?
![2015-08-14_10 05 25](https://cloud.githubusercontent.com/assets/13795733/9271614/3543fbc6-4273-11e5-897b-30a488fc4d16.png)
![2015-08-14_10 08 15](https://cloud.githubusercontent.com/assets/13795733/9271615/3545019c-4273-11e5-9f57-24f5b67038b1.png)

**Comment by Poenjabiesous** [comment]
What launcher are you using?

**Comment by Poenjabiesous** [comment]
See #123

**Comment by shazzi2k** [comment]
Using AT launcher and its on bo buddy bunkers modpack

**Comment by shazzi2k** [comment]
Thanks Poenjabiesous  for the help. After following and reading your link i read up on this https://bukkit.org/threads/psa-the-switch-to-uuids-potential-plugin-server-breakage.250915/page-4
All i had to do was change the server properties it was set to Online=False.

Thanks for helping me solve this XD
