### ISSUE TITLE
issue with fence

### ISSUE THREAD

**Issue by aidancrazywierd** [OpenModularTurretsTeam/OpenModularTurrets#163]
diamond pickaxe breaks obsidian tier 5 fence but the fence doesnt drop to be picked up again.

**Comment by Utildayael** [comment]
This also seems to happen with Mekanism Paxels. Fence breaks but doesn't drop the fence. [all tiers]

**Comment by Keridos** [comment]
Does this only happen with the tier 5 fence?

**Comment by Utildayael** [comment]
All tiers for the Mekanism paxel issue.

**Comment by aidancrazywierd** [comment]
all tiers with any pickaxe.

ALSO, can you maybe just make it so the person who places the fence can only break the fence, like you did with the turrets ? Or maybe poenjabiesous can just claim his land with factions or towny in servers if he doesnt want people taking his fences

**Comment by Poenjabiesous** [comment]
Thats not possible with normal blocks. You cant really store information in it, and all blocks on the map are a singleton of the same block class. The only way to do this is to involve tile entities, and binding one to a block that will be used a lot, is a very bad idea performance wise.

**Comment by aidancrazywierd** [comment]
hm, ok.

**Comment by Poenjabiesous** [comment]
I will however check why they don't drop, that's not correct.
