### ISSUE TITLE
No License?

### ISSUE THREAD

**Issue by grondag** [OpenModularTurretsTeam/OpenModularTurrets#165]
Can't find any info on how this mod is licensed.

Can it be distributed in mod pack?
Can it be distributed with modification to the code?
Under what terms?

**Comment by Keridos** [comment]
Modpacks are fine, as for the license, we should probably ask @Poenjabiesous. I'd personally go for the LGPL License and mention that just forking this and redistributing it publically while this is still maintained is a "jerk" move.

**Comment by Poenjabiesous** [comment]
I'm not too clear on the formalities of all the legal stuff around licencing, but I think I agree with @Keridos on the LGPL licence after doing some reading on it.

**Comment by Keridos** [comment]
A small addition for me, I personally am fine with redistributing it in a private modpack when modified. But modifying it and then redistributing it publically I do not like at all, at least not without consulting us (the OMT Team).

**Comment by Rukachan** [comment]
In the Curse page it mentions that this is licensed under GPLv3.

**Comment by Keridos** [comment]
So we use LGPL @Poenjabiesous ?
If yes, I am gonna add in the necesaary files.

**Comment by Poenjabiesous** [comment]
Sounds good.

**Comment by Keridos** [comment]
@Poenjabiesous Just a small thing I did not see, LGPL enables people to use part of our source in non opensource stuff, which I personally do not really like. I suggest just using the GPL for this one then. Sorry for my derp.

**Comment by Poenjabiesous** [comment]
As long as credit is given where its due, I dont really have a problem wheure the code is used. I see this project as a knowledge collective.
