### ISSUE TITLE
Can't Craft Tier II Base or Higher

### ISSUE THREAD

**Issue by Utildayael** [OpenModularTurretsTeam/OpenModularTurrets#166]
I have an odd issue. I can't seem to craft Tier 2 or higher turret bases! Recipe is set to auto and it is feeding me the Mekanism items to build it. Ok no problem. I put everything in the grid as asked and... nothing to craft.

I checked the config and while I found lines to enable/disable turrets, I didn't see anything of the like for the bases.

:(

**Comment by Utildayael** [comment]
Additional: Tried to change the config to manually be "vanilla" but the recipes in NEI still showed Mekanism sooo.....

Also tried to hard code "mekanism" as the recipe type and still no dice

I show the recipe as.. in order by row...

enriched iron - energy tablet - enriched iron
io module - tier 2 sensor - io module
enriched iron - tin bar - enriched iron

I tried charged and uncharged energy tablets. I tried both Forestry and Mekanism tin bars. No dice.

**Comment by Keridos** [comment]
Gonna look into that though setting the recipes to vanilla should work.

**Comment by Poenjabiesous** [comment]
Version? 

Try deleting the config file and rerunning...

**Comment by Keridos** [comment]
Yeah the config file needs to be regenerated, as it was stated in the changelog and the news page.

**Comment by Utildayael** [comment]
No dice gents. I nuked the config file and still no joy. :(

**Comment by Poenjabiesous** [comment]
I am unable to reproduce this. I have instantiated the recipes with all 4 different options, and everything is looking healthy on my side.

**Comment by Poenjabiesous** [comment]
Yeah, run a bunch of different permutations, and its not happening on my side:
![craft](https://cloud.githubusercontent.com/assets/8829214/9698438/8d9a5dc0-53b6-11e5-96c3-d16a8c68fac8.jpg)

Perhaps something broke your environment, try reinstalling the mod.

**Comment by Utildayael** [comment]
Thanks for looking into this. Reinstall didn't work. I'm not sure what the deal is, something must be conflicting. That said, we're working on a pack upgrade to our server so should be on the current new version here soon and hopefully that will sort things out.  :)

**Comment by dakakeisalie** [comment]
I am having this problem currently on a server we are playing. We do have mekanism and NEI suggests that you must have an energy tablet with no metadata 4900 or I guess 4900:0. However, the tablets store energy and only exist in 4900:1 - 4900:100 form.

**Comment by Poenjabiesous** [comment]
See #186.
