### ISSUE TITLE
Disguise metadata bug

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#170]
From mskurnik (accidentally posted that on my floodlights mod):

When you right click on a base to add a disguise, the base ignores the sub I'd of the block in your hand. For example attempting to use a block with ID 999:4 ends up inserting ID 999:0. I am not at the computer right now but it at least happens with third party blocks such as railcraft quarried blocks and natura blocks. I have not tested with vanilla blocks.

**Comment by Poenjabiesous** [comment]
I'm such a derp XD.

**Comment by mskurnik** [comment]
Yeah.  I posted this to the wrong repo when I was using my phone.  The bases also only grab the front texture of the block.  A vanilla example is sandstone.  The front face of the sandstone block is used on all 6 sides of the base.

**Comment by Keridos** [comment]
Proposing: Release another set of small patches as a release (not beta) as 2.1.7. We should then have a rather stable build before we move out to the new features in 2.2.0. @Poenjabiesous you ok with that?

**Comment by Poenjabiesous** [comment]
Perfect.

**Comment by Keridos** [comment]
@Poenjabiesous any ETA on when you can fix this?
