### ISSUE TITLE
Drops and mod conflict

### ISSUE THREAD

**Issue by andrenoel1** [OpenModularTurretsTeam/OpenModularTurrets#171]
1st I love this mod.  Thanks!  =)

2: I want to run a server with OpenModularTurrets and Advent of Ascension mod.  They do work together but the problem is when turrets kill monsters it leaves drops from mobs in the AoA mod that should not be killable by the player yet.  I am glad the turrets kill them.  I need an option to have mobs killed by turrets not give drops so players cannot cheat their way up in the AoA mod.

Is there a possibility of a config flag to prevent all drops from mobs killed by turrets?

Links just for reference for you: (not needed but easy reference)
https://www.youtube.com/watch?v=7GR0HhP8YEM
http://adventofascension.gamepedia.com/Advent_of_Ascension_Wiki
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286381-aoa-20-new-dimensions-300-mobs-27-bosses-450-items

**Comment by Keridos** [comment]
+1 for this one for me, I just literally have no idea on how to do that at this moment.

**Comment by andrenoel1** [comment]
I had some thoughts on this.

I was thinking that when any entity takes damage perhaps the event knows where the damage came from.  If damage came from a player add an NBT tag to the entity that a player damaged this entity.  if damage came from a turret then add an NBT saying that a turret damaged this mob.  Then trap entity death, and if the entity is tagged as damaged by turret and NOT tagged by player damage then instead of letting the entity die and giving drops, have the entity cease to exist and not give drops.  i have used a method like this  
myEntity.setDead() 
which when I have used it, makes the entity disappear and not do drops.

I do not know if this helps but im hoping it does. =)

**Comment by Poenjabiesous** [comment]
I guess it's a good idea to make a configurable option of making turret kills do mob drops.
