### ISSUE TITLE
Configure menu doesn't show when server is in offline mode

### ISSUE THREAD

**Issue by TehSomeLuigi** [OpenModularTurretsTeam/OpenModularTurrets#174]
Hello, similar to (or the same as) #161 , the configure menu and other such buttons aren't accessible in offline mode.

Unfortunately, I am unable to disable offline mode in this scenario.

Is there a workaround that could be implemented?

If there was a configuration setting such that **anyone** can reconfigure any turret, I would love that, for example.

Thanks in advance.

**Comment by Poenjabiesous** [comment]
As per #162: 

"The thing is that we would need to make the entire UUID system compatible with offline mode. Second thing is that I think 99,9% of the people who use offline mode make it to make cracked clients possible to join their server and me and @Poenjabiesous have agreed that we will NOT make this mod compatible with cracked clients."

We cannot enforce/help people playing offline/cracked servers. If the users are all premium, an online server would not be an issue.

**Comment by TehSomeLuigi** [comment]
Unfortunately, this is untrue in this instance.

I'm playing on a LAN and we do not always have access to the Internet,
ergo we have to play in offline mode as the server will refuse any
connections when it cannot verify them with Mojang's servers.

I understand your decision, though it's a bit of a shame that this is
how the new UUID system can cause issues.

I suppose I'll have to take a look at creating some kind of coremod that
allows one to manually assign a UUID to a username.

Thanks for taking the time to respond.
