### ISSUE TITLE
World crash

### ISSUE THREAD

**Issue by Tyrantin** [OpenModularTurretsTeam/OpenModularTurrets#177]
So, had an admin decide to quit and delete his "base" via world edit! It glitches the tier 5 base's throughout the world causing a catostrophic world corruption! Just wanted you to be aware of this potential issue.

**Comment by Keridos** [comment]
I have no idea how that could happen with our TileEntities, we need a lot of more info before we can tackle such a problem.

**Comment by Poenjabiesous** [comment]
I agree, the statement gives us no scope of what the issue entails.

**Comment by Tyrantin** [comment]
Basically the lvl 5 turret basses started to break and replace in very rapidly throughout the world! It had created a log but no crash. They were doing it so fast that the TPS went down to 2-3. We had to do a rollback but it had created such massive lag that only one person could go in to the server and when that person got close to the area of "infection" it would cause the server to restart. The lag was so intense that one person could only move at a snails pace. If I can find the log I will post it.

**Comment by Poenjabiesous** [comment]
This ticket gives no discriptive scope to the possible issue. Closing.
