### ISSUE TITLE
Feature request: mobile turrets

### ISSUE THREAD

**Issue by Hypocrisy** [OpenModularTurretsTeam/OpenModularTurrets#179]
Maybe this is too ambitious of a request but I really think it would be amazing to have turrets (and their base) that could move along some type of track. Steve's Carts has something similar with their turret cart but I would much prefer an OMT alternative.

What I am thinking for a way to fit the modular theme of the mod would be to have a separate block that would be mobile that you would supply with fuel (coal possibly) and the turret base could be placed onto it.

Now, I don't know the first thing about coding or mod development but I understand Minecraft usually doesn't have a fun time with moving blocks. I've seen mods that try to attempt moving blocks by simply continually removing and re-placing blocks in the direction you want to move but I don't think that would be the best solution. So, what if you just used the same code used for mine carts and track but gave it your own textures? I am thinking of something like a rail or cable that would feed through the engine block so that you could place a base on top, bottom, left, and right (or at least just top and bottom).

Another idea for mobility would be to have a base, or something the base could hook on to, that would latch on to the top of your fences and perimeter them back and forth or loop. This way you wouldn't need to really come up with many other textures and you could create effective paths with the doubled security of a fence.

Reasons why I think having mobility would be beneficial:
* A more unique and diverse solution to guarding the boundaries of your entire base or land.
* Could also be more fun for your enemies because they would have to time the paths.
* If using the fence mount idea, it would give even more functionality and reason to use your fences.
* You could create an ammo resupply station that the turret would path by every revolution.

I know this is a very ambitious request and maybe it is too much in the style of a cart mod for you guys but I really think it would make an awesome addition to this mod, if doable.

What do you guys think?

**Comment by Keridos** [comment]
The thing here is that (we had that somewhere in another issue) that everything we have codewise is centered about the turrets being a block. We most likely would have to rewrite almost all code to work with movable turrets. That accounts to a few thousand lines of code. And it would take weeks of testing to fix all the bugs we would likely introduce again. Currently we are just 2 people working on the project, another coder might help improve the situation by a lot.

**Comment by Hypocrisy** [comment]
Sorry again for my coding ignorance but couldn't you leave the turrets coded as a block and then just create a moveable entity that can move stationary blocks?

**Comment by Keridos** [comment]
If that was possible I think we would aready have a mod that did exactly that.

**Comment by Poenjabiesous** [comment]
I agree with Keridos. I'm quite busy as of late as well, so getting to the issues in this mod's issue list is hard. I will, however, get some time in the near future to work on this project again- I had an idea a while back similar to this one, (excluding the tracks) but it might take some time to implement. Just watch this space.

**Comment by Hypocrisy** [comment]
Well, it's a shame you guys are under staffed. I wish I could help. Regardless, I love your mod and will continue to support it. Good luck.
