### ISSUE TITLE
Crashing dev 2.1.5-184

### ISSUE THREAD

**Issue by YanFull** [OpenModularTurretsTeam/OpenModularTurrets#181]
I'm getting this crash, i think this is some kind of lack Id's (exeptions in the crash log), the official beta build in curse forge are with same crash for me. Take a look, if is too crashlog short i'll send a full if needed.

http://pastebin.com/RG8ccWh7

thanks

**Comment by Poenjabiesous** [comment]
Looking at this log, the issue you are getting has nothing to do with OMT:

03/11/2015 12:52:52 PM] [Client thread/ERROR] [FML]: Caught an exception during block registration
[03/11/2015 12:52:52 PM] java.lang.RuntimeException: Invalid id 10241 - maximum id range exceeded.

You probably have too many mods trying to start up.

**Comment by Keridos** [comment]
This crash has no indications of OMT doing this at all in its crash log, the Init that fails is Translocators by ChickenBones.

**Comment by Poenjabiesous** [comment]
Please check stacktraces in the future before posting new tickets.

**Comment by YanFull** [comment]
Right, when i pull omt works normaly

**Comment by Keridos** [comment]
Try removing Translocators and look then. Should also work.

**Comment by YanFull** [comment]
Shoud< 
Did not work, still in beta the mod, when release maybe i try again

**Comment by Keridos** [comment]
Still weird, I am fairly sure OMT does not use up 10k block id's.

**Comment by YanFull** [comment]
Of course not, i'm get this exeption id with another mods, but i want a turrent mod and this interesting me thats why those post

**Comment by YanFull** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276277-1-5-2-sp-mp-lan-turret-mod-v3-0-1#0

this could help the development with everything that already this old mod has
