### ISSUE TITLE
Ender Dragon not taking damage from missiles ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [OpenModularTurretsTeam/OpenModularTurrets#182]
The Dragon doesn't seems to be damaged by turrets, although I pretty am sure this was made so intentionnally, I request a config for that, because in my modpack ( soon, inb4 XyCraft ), to beat a dragon it's a must having turrets, the ender dragon fight is a lot harder, regening health passively stacked with the crystal thingy, so attacking it by yourself is near impossible to beat him ( being an endgame fight due to his high speed mobility escapes and him regening ).

**Comment by Poenjabiesous** [comment]
Since rockets can be homing, I personally feel that it does not give the dragon a sporting chance. Other turrets (Laser, Railgun, etc.)  can still be used, however.

**Comment by Carbon-Ghost** [comment]
yeah but may we still have config for that xD ? The thing is, the rockets are for him to stop regening his life when he is away, else fight is impossible, sure laser can help but it's not as precise due to lack of homing :/

**Comment by Poenjabiesous** [comment]
Did'nt you put the rocket homing code into the project?

**Comment by Carbon-Ghost** [comment]
"I put" the rocket code to the project, the work was not mosly done by me though ^.^''
But TL;DR May you add a config for this, it's really a must in my case :/ I don't know what code cause this and tbh, haven't touched to eclipse for a while now...

**Comment by Poenjabiesous** [comment]
Change made in the newest dev build. Please note that I don't agree with this, it makes the ender dragon battle ridiculously easy for every other pack using this mod.

**Comment by Carbon-Ghost** [comment]
So it is present but by default or has config ?

**Comment by Poenjabiesous** [comment]
There's new config under misc. Off by default.

**Comment by Carbon-Ghost** [comment]
Kk, thanks :D 
At least that sucka won't regen that fast when he is escaping :3

**Comment by Keridos** [comment]
The ender dragon is ridicilously easy to kill with a bow and arrows :p

**Comment by cloakable** [comment]
Also: You're basically launching SAM site missiles at the Ender Dragon with this on. If it WASN'T easy under those conditions, I'd be shocked!

**Comment by Carbon-Ghost** [comment]
I would love to see how you would kill the dragon with bow and arrow with a dragon that regenerates health :P ( by himself he isn't much of a threat, more an annoyance... )

**Comment by Keridos** [comment]
You can kill the crystals that regenerate him with a bow and arrows.

**Comment by Carbon-Ghost** [comment]
He passively regenerates on top of that :P
