### ISSUE TITLE
requireds

### ISSUE THREAD

**Issue by anar4732** [OpenModularTurretsTeam/OpenModularTurrets#183]
### Creative Upgrade ###
what does it do?:
 * how much energy is stored can be changed tarret
 * Unlimited energy

-----------------------------------------------

### Redstone control upgrade ###
 * redstone on / off control tarret

---------------------------------------------

### MınıGun Tarret ###
 * much more expensive and dangerous

------------------------------------------------------

note: my English sucks

**Comment by Poenjabiesous** [comment]
Noted. I agree with a creative upgrade, but not the minigun. Redstone control is already implemented, please make sure of functionality before you post tickets about them in the future.
