### ISSUE TITLE
Scattershot upgrade doesn't use extra ammo per shot...

### ISSUE THREAD

**Issue by Twilight13** [OpenModularTurretsTeam/OpenModularTurrets#184]
This is using:
OpenModularTurrets-1.7.10-2.1.5-184

I had a Disposable Turret on a Tier 2 Base, and gave it the Scattershot upgrade, and while it did use up triple the amount of RF for each shot, and seemed to shoot three projectiles each shot, it did *not* use up three items from the base inventory each shot, only one. When I tried this with a machine gun turret, it *did* use up three bullets per shot, so this may be a disposable turret specific problem.

**Comment by Twilight13** [comment]
Oh, just noticed one more thing. If you make changes in the config file, such as changing the energy used per shot (I changed the disposable turret to use 20RF instead of 2), it isn't reflect in the tool tips for the turret item, which still shows it as using 2 RF per shot.

**Comment by Poenjabiesous** [comment]
Thanks, will look into this.

**Comment by Poenjabiesous** [comment]
Fixed in the newest dev build.
