### ISSUE TITLE
crank on top

### ISSUE THREAD

**Issue by 4rz0** [OpenModularTurretsTeam/OpenModularTurrets#185]
Cranks, when placed on top of a turret, don't properly connect to the turret base, and don't work.

**Comment by Poenjabiesous** [comment]
The crank was never designed to go onto the top of a base, this is not an issue.

**Comment by 4rz0** [comment]
I see.
In this case, this should be mentioned, and made impossible.

**Comment by 4rz0** [comment]
Or, if possible, implemented, that'd be even better ;D
