### ISSUE TITLE
Mekanism recipes broken

### ISSUE THREAD

**Issue by allaryin** [OpenModularTurretsTeam/OpenModularTurrets#186]
Turret bases (and presumably other recipes) that use Mekanism energy tablets are uncraftable because they appear to expect meta 0 - which tablets never have. They seem to set meta to 100 when empty and 1 when fully charged.

OMT version 2.1.5-184, Mekanism version 8.1.7.252 fwiw.

**Comment by HeliosDK** [comment]
It seems i have the same problem with the energy tablet from mekanism tablet in receipe is missing the meta info from mekanism so it doesn't work without it.
This is tried with mekanism 1.7.10-8.1.7.252 and OpenModularTurrets-1.7.10-2.1.5-184

**Comment by Keridos** [comment]
Here is the download: http://minecraft.curseforge.com/projects/openmodularturrets/files/2267223
