### ISSUE TITLE
Tier 2 sensor cant be made

### ISSUE THREAD

**Issue by HeliosDK** [OpenModularTurretsTeam/OpenModularTurrets#188]
The recipe works but as soon as you try to take it its stuck in the finish object areal.

**Comment by Keridos** [comment]
Any information, which forge version, which mod version, which recipes. Please make proper bug reports...

**Comment by HeliosDK** [comment]
forge 10.13.4.1541-1.7.10
OpenModularTurrets-1.7.10-2.1.6-187

**Comment by Keridos** [comment]
Which recipes do you use?

**Comment by HeliosDK** [comment]
Thermal expansion

**Comment by Keridos** [comment]
Can't reproduce it here, can craft it fine in a normal crafting table.
I guess something else is bugging that recipe, tried a normal crafting table?
