### ISSUE TITLE
EnderIO Recipes very expensive in early game

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#190]
The tier 2 turretbase needs a 5m RF capacitor and only has 500 rf capacity, I suggest making this one quite a bit more affordable (I got an idea on how to do that). You ok with that @Poenjabiesous?

/edit, I changed it to require the basic capacitor bank.

**Comment by Poenjabiesous** [comment]
Perfect, thanks!
