### ISSUE TITLE
SMP: Trusted Players not updating on adding a player.

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#191]

**Comment by Keridos** [comment]
Not fixed apparently, needs some more digging.

**Comment by Poenjabiesous** [comment]
This is a timing issue:

1. The packet gets sent to the server to add a trusted player, which obviously takes time to arrive and be acked.

2. At the same time the GUI gets redrawn on the client side, before the tile entity had time to sync the new data that was just sent. Client side, the new trusted player does not exist yet.

**Comment by Poenjabiesous** [comment]
Think I got it.
