### ISSUE TITLE
SMP: Clientside Desync on inventories.

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#195]
I noticed that on clientside the shift clicking of items was a bit buggy for me. Not sure if I caused it with my refactoring, but it might be in that. Triple checked if I did anything wrong though and did not find anything. Can somebody else check on that maybe?

**Comment by Poenjabiesous** [comment]
I saw it before as well, but I was unable to reproduce it reliably. Saw it on some other mods more recently as well, Like Thermal Expansion, EnderIO and Big Reactors.

**Comment by Keridos** [comment]
Maybe a forge bug?

**Comment by Poenjabiesous** [comment]
My guess is a UTP packet that gets lost/receives no ack.

**Comment by Keridos** [comment]
I am fairly sure now that this is a bug I may have introduced, thinking about that packets are maybe not correctly sent.
