### ISSUE TITLE
Relativistic Turret culls block face below it when Smooth Lighting is disabled

### ISSUE THREAD

**Issue by HanFox** [OpenModularTurretsTeam/OpenModularTurrets#196]
I made this issue (https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/178) a while ago and was met with the response of it being unreplicatable and that it may have been an "environment issue" on my PC.

However, as I posted in the last comment (after it was closed and likely no longer being noticed) I figured out what caused the issue which is that disabling Smooth Lighting causes the block face to cull.

Hopefully with this extra information it can be replicated and indeed fixed.

**Comment by Keridos** [comment]
Reopened the other issue, you couldve just poked us there, thought it was open the whole time.
