### ISSUE TITLE
[feature] projectile speed

### ISSUE THREAD

**Issue by shadoxxhd** [OpenModularTurretsTeam/OpenModularTurrets#200]
it would be nice to have a setting to adjust projectile speed in the config. also, there could be an upgrade for that, as with longer ranges turrets have big trouble hitting even slow moving entities. the laser turret could have a hitscan-option (like a real laser would work - but would be nice gameplay wise, too).

apart from that, a simple vector prediction (reading the movement vector of the entity and multiplying it with distance/projectile_speed would be enough, as interception point calculation should only help with VERY fast moving entities (neutralizing overcompensation with swiftly approaching targets and undercompensation with targets swiftly moving away from the turret) and AI prediction would be way out of scope) would be very useful, especially if you configure the turrets to have a longer range than normal.

**Comment by Poenjabiesous** [comment]
Turrets with the longest ranges, like the railgun and rocket turrets, were designed in such a way that they very, very rarely miss. Not sure if the following is true:

"...as with longer ranges turrets have big trouble hitting even slow moving entities."

Calculation already takes place. The vector of the target is added to the one of the projectile, as one would expect. Without this, a very small percentage of turret shots would be effective.

What is a "fast moving entity"? In the all the mod integration we have done, Im yet to see an entity that matches that description- moving quickly enough and changing direction quickly enough for the previous turret shot to be moot.

I do however agree that projectile speed should be configurable, although having lower and upper limits.

**Comment by shadoxxhd** [comment]
the problem is that i set turrets to have much longer ranges than normal (railgun and laser around 100 blocks), and at this distance they even miss an 'activating' wither which slowly sinks down.

apart from that even if the shots are correctly aimed, the projectiles need quite some time to reach the target at 100 blocks distance, so fast shooting turrets waste a lot of ammo.

as for fast moving entities ... have you ever seen the chaos guardian from draconic evolution? it should match this description quite well.

**Comment by Poenjabiesous** [comment]
I'm sorry, but the mod was never designed with 100 block turret ranges in mind for normal use. Apart from the server load, this is a very specific issue, only related to your use of the mod, and I unfortunately can't agree with the request. (apart from the configurable projectile speed.)

What you can however do, is branch the project and make the changes yourself if you so wish. This is after all an opensource mod.

**Comment by Poenjabiesous** [comment]
Additionally, turret accuracy can also be set to 0, which means it will statistically miss 0% of any shot taken over a distance of 10 blocks.

**Comment by shadoxxhd** [comment]
as the configurable projectile speed was all i was asking (as the basic movement prediction i suggested was already implemented), i don't see a problem here. will you add the option to make the laser turret instant hit (as it's also projectile speed related, and would give a cool alternative look)?

**Comment by Poenjabiesous** [comment]
The minecraft engine does not allow a projectile speed of infinity. Like I said, I will add the configurable projectile speed; what the end user does with this option (as with all others) is up to them.

**Comment by shadoxxhd** [comment]
i don't mean infinite projectile speed, but rather a hitscan option (instead of firing a projectile, it deals damage right away if the ray hits, and shows the beam path for 1 (or maybe more, depending on how it looks) tick)

**Comment by Keridos** [comment]
The ray may be usable, I think that is what some of the Thaumcraft wands do.
