### ISSUE TITLE
Port to 1.10.2

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#202]
This thread is for discussing of the 1.10.2 port's progress. We are currently working on this and using this to collect all the needed information for the port.

For the devs: this describes pretty good how the rendering changed: https://gist.github.com/williewillus/57d7093efa80163e96e0

Checklist:
- [x] get the gradle stuff going in the branch
- [x] get it to compile
- [x] get all the normal items to render (this should be ready in the next few days)
- [x] fix the GUI
- [x] change normal block rendering, including the power and inventory expanders
- [x] fix block bounds (cannot be set in constructor, have to implement geBoundingBox(blockstate))
- [x] fix the TESR for turrets and the lever(@VoltyFarstar, please take a look at that)
- [x] rework the upgrade / addon item max stacksize to be configured in the slots of the turretbase itself
- [x] add in dynamic JEI hiding for the GUI
- [x] convert all the tiered blocks to use subblocks so just 1 ID for base, one for wall etc.
- [x] convert all the items into metaitems so just 1 ID for each metaitem (currently 4 IDs for all items).
- [x] fix the rest of the recipes to use the new meta items and standardize the recipes (setting all the craftable items in RecipeHandler as an ItemStack for reference)
- [x] convert all internal Names to use the unlocalized Names from the Names class.
- [x] for future compatability rework all internal names to 1.11 standards (only lowercase). Should we do "upgrade_efficiency" or "upgradeefficiency" ?
- [x] fix sound file playing
- [x] implement tossaponks new fixes for targeting
- [x] fix Dungeonloot (or maybe remove it)

**Comment by Poenjabiesous** [comment]
Agreed.

**Comment by Keridos** [comment]
To be honest, it is a lot of work, but the new codebase is far better than the old one. Performance should be much better and it is easier to work with than the old block rendering stuff.

**Comment by Poenjabiesous** [comment]
Busy reading up on everything that needs to change.

**Comment by Keridos** [comment]
We can also consider having a 1.7.10 version and 1.8.x version up at the same time, OpenComputers and a few other mods do it as well so it seems to be managable workwise.

**Comment by brucethemoose** [comment]
Eagerly awaiting the 1.8.9 port, thanks guys.


But on a separate note... Are there any plans for 1.9? 1.8.9->1.9.x isn't a massive change like 1.7.10 ->  1.8.9, so porting to 1.8 still isn't a bad idea.

**Comment by Poenjabiesous** [comment]
Playing with forge 1.8.9 atm, the modeling changes are seismic to say the least. I do feel that our TESRs (as is currently used) will still be viable.

**Comment by Keridos** [comment]
The performance might be a bit better with the static parts of the turrets via normal rendering. Since most of the turret heads are animated the moving parts still need to be TESR.

**Comment by Keridos** [comment]
I might start an 1.8.9 port soon in a seperate branch. But it will probably take quite some time until we even get it to compile. The changes for the BlockPos are really annoying to port and take quite some time. Then we'd have to fix the rendering though I might do the TurretBases first, we later need to check how we would do the camo with the new rendering system.

**Comment by Poenjabiesous** [comment]
The camo functionality is probabaly gonna be scraped, I am not aware of a way to make block textures dynamic in 1.8. 1.9 might be different though, but will need to check.

**Comment by Keridos** [comment]
@Poenjabiesous Camo can apparently be done via ISmartModel, take a look here: https://github.com/TheGreyGhost/MinecraftByExample/blob/master/src/main/java/minecraftbyexample/mbe04_block_smartblockmodel1/CamouflageISmartBlockModelFactory.java

**Comment by Keridos** [comment]
I think we should start working on this @Poenjabiesous EnderIO has a 1.8 port, BC has one and more mods are moving over. Since this is gonna take some time, better start sooner than later.

**Comment by Keridos** [comment]
Ok, after porting my own mod to 1.8.9 and then 1.9.4 I feel quite confident we can do the same with OMT now, gonna start a new branch maybe tomorrow and will try to push as much changes into the first commit, but we will probably need a few commits before it even compiles. Since I have a pretty good idea how we can do the Bases I might start refactoring them.

**Comment by melekaiah** [comment]
why not just move straight to 1.10.2 in this case? it seems to the one most mods are updating too now. seens to be the new 1.7.10. and may be an easy update path to 1.11 

good luck cant wait to test

**Comment by Keridos** [comment]
Already did the first changes to 1.10.2, dropping 1.8.9 and 1.9.4 port goal.

**Comment by Keridos** [comment]
Its done :)
