### ISSUE TITLE
ComputerCraft compatibility not working

### ISSUE THREAD

**Issue by NEXUS2345** [OpenModularTurretsTeam/OpenModularTurrets#203]
Placed the computer next to the turret, wrapped it as a peripheral, and then this: 
https://gyazo.com/78e69a1be827250e9bef3c4714b1be7d

**Comment by Keridos** [comment]
There is no GetType() function. simple as that.

**Comment by Keridos** [comment]
you can call peripheral.getType() in the next version.

**Comment by Keridos** [comment]
Also some derps in the CC code, I am currently at fixing this, but I need some info from the CC devs since the documentation on creating Peripherals is pretty much nonexistant.
