### ISSUE TITLE
recipe type not syncing with server

### ISSUE THREAD

**Issue by shadoxxhd** [OpenModularTurretsTeam/OpenModularTurrets#204]
i set the server to use thermal expansion recipes, yet the client thought the mod was using the enderIO ones (client config was set to auto). would it be possible to sync the config on joining a server (like many other mods already do)?

**Comment by Keridos** [comment]
sounds like a config desync, if you wanna play on a server, you should probably get the official configs, many bugs can arise else. We might look if and how the syncing is done though.

**Comment by Keridos** [comment]
We would need our own recipe handler for this to work, this is not easy to implement at all.
