### ISSUE TITLE
Bug: Computer Craft Integration

### ISSUE THREAD

**Issue by CzEMC** [OpenModularTurretsTeam/OpenModularTurrets#205]
When having the Addon, "Addon - Serial Port" (ID 6526) or not having it installed in a turret base, Computer craft doesn't work with any API's at all.

Other Information:

Lua command "peripheral.getMethods("_SIDE-TURRET-BASE-IS-ON_")" returns:

```
{
    "getAspects",
    "getAspectCount"
}
```
Lua command: "peripheral.getType("_SIDE-TURRET-BASE-IS-ON_")" returns:

`tt_aspectContainer`

The computer thinks that The Turret base is a ThaumCraft Aspect Jar

Version Information
Open Modular Turrets: 2.1.9 [Build 211]
Computer Craft: 1.75
Environment: Minecraft Forge 10.13.4.1558 [For Minecraft 1.7.10] Java 7 (Also tested with same results on Java 8)

**Comment by Poenjabiesous** [comment]
Please read the readme on the landing page for information on the correctness of posting issue tickets. 

You have not provided the version you are experiencing this with, the CC this is happening with, or your operational environment. In fact, the ticket only describes the issue experienced and nothing else. This is insufficient in helping us understand the problem. 

In the future, tickets like these will be closed immediately.

**Comment by CzEMC** [comment]
Sorry for the miss-understanding. I have provided the information in the creation post.

**Comment by Keridos** [comment]
Works fine for me in my dev environment and the code is completely correct for this.
check this here, no idea why it should do that: https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/master/src/main/java/openmodularturrets/tileentity/turretbase/TurretBase.java#L885-L1035

**Comment by CzEMC** [comment]
I see that you have referenced Thaumcrafts Aspect jar and tubes, I don't understand why, but computer craft is picking that up instead of the defined OMTBase.

I have Peripheral++ and OpenPeripherals installed. I'll test to see if I get any new results when I remove them.

**Comment by Poenjabiesous** [comment]
Just to confirm, the CC stuff seems to work correctly here as well.

**Comment by Keridos** [comment]
The thing probably is that we use the TC API, but as intended (I took a look at the interfaces we use). Another mod like the extra compat modules should check first if the block already is a component before just overwriting its support with some generic stuff based on interfaces.

**Comment by Keridos** [comment]
@CzEMC ay news on this?

**Comment by CzEMC** [comment]
Just having computercraft, thaumcraft and OpenModularTurrets solved the problem. It might be a problem with Peripheral++ and OpenPeripherals.

**Comment by Keridos** [comment]
Can you report that to them please?
