### ISSUE TITLE
[Feature Request] Wall variants of the Hard Walls

### ISSUE THREAD

**Issue by SnowShock35** [OpenModularTurretsTeam/OpenModularTurrets#208]
Hi OMT Team,

I have a small feature request for OMT.

For the Hard wall blocks it would be neat if you could make them into the wall variants as well as having the block. It would add more detail to the wall and I think would fit nicely.

Hope you like the idea. :D

**Comment by Poenjabiesous** [comment]
Hi SnowShock35

I will implement this personally. 

Thanks for the input.

**Comment by SnowShock35** [comment]
@Poenjabiesous Thanks, really appreciate it. :smile:

**Comment by Keridos** [comment]
Closing this, check this out for the passive defense stuff: https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense
