### ISSUE TITLE
Can’t configure attack mode, on server.

### ISSUE THREAD

**Issue by Cbert** [OpenModularTurretsTeam/OpenModularTurrets#210]
Can’t configure attack mode, on server, there is no menu as it is on SSP.
![2016-03-20 09 30 18](https://cloud.githubusercontent.com/assets/9320867/13903341/c4230cbc-ee7e-11e5-8c04-93fc57f044d8.png)

**Comment by Poenjabiesous** [comment]
Please read the rules about posting issue tickets on the landing page. There are about 6 closed tickets relating to this issue.

**Comment by Keridos** [comment]
This is fixed in v2.2.5 but you are f*cking greedy if you do not want to pay for minecraft. If you have fun with the game the money is not *wasted*. Support the developers to make the game better and more awesome..

**Comment by Cbert** [comment]
I’m not greedy, I just can’t pay everyone, I have to choose, I’m not oligarch. May be you live in welfare and don’t even realize that, if I do as you say Ill die. With all due respect, next time try to think about that.

**Comment by Keridos** [comment]
Sorry about writing that this way, we just had somebody who was like: fuck you and make cracked clients work. Should not have written that in this thread. I think that was a thing I posted in pretty much all requests for that.
