### ISSUE TITLE
Turrets mounted on bottom are bugged

### ISSUE THREAD

**Issue by zzApotheosis** [OpenModularTurretsTeam/OpenModularTurrets#212]
Java 8 Update 77 (64-bit)
MCP v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1614
OptiFine_1.7.10_HD_U_D3
FastCraft 1.21

I have a Laser Turret mounted on the bottom of a Tier 5 Base, and the bottom turret will not fire at any valid targets more than 3ish blocks below its Y level. For instance, the bottom-mounted turret will not fire at a zombie 5 blocks directly below it, but will fire at a zombie 5 blocks to the side of it.

The bottom-mounted turret doesn't fire at this zombie...
![2016-03-31_21 10 15](https://cloud.githubusercontent.com/assets/11908793/14196861/933164ea-f785-11e5-87bc-21a1c6221fc4.png)

But will fire when it's around the same Y level.
![2016-03-31_21 10 34](https://cloud.githubusercontent.com/assets/11908793/14196876/b5b8d71e-f785-11e5-9aa9-fe08efb29021.png)

**Comment by Poenjabiesous** [comment]
Have you configured the -Y in the turret base GUI to more than the default of 2?

**Comment by zzApotheosis** [comment]
Oh, I see. Haha, please disregard.






I'll go away now.
</pride>
