### ISSUE TITLE
running modular turrets 1.6.4 mod WITHOUT thermal expansion 3

### ISSUE THREAD

**Issue by CashMoneyLife** [OpenModularTurretsTeam/OpenModularTurrets#213]
hey i got a problem i love this mod so much but it always want me to install thermal expansion 3 and im asking why i have other mods that generates energy for the turrets and i dont need TE3 because its useless for me and the second reason it crashes my minecraft because of the fucking blizz spawn and i cant disable it so im asking here how i can run this mod for 1.6.4 without TE3 please help

**Comment by Poenjabiesous** [comment]
Hi CashMoneyLife

This mod's 1.6.4 support has ended over a year ago. Please use MC 1.7.10 if you wish to use this mod without TE3.
