### ISSUE TITLE
2.2.0 Crash

### ISSUE THREAD

**Issue by TheGameAce** [OpenModularTurretsTeam/OpenModularTurrets#214]
So after recently posting about the camouflage not working for the turret bases, I noticed that the mod finally got updated and a fix applied for that. When I went to test it though, I got a crash...
http://pastebin.com/qdrMUsDu

**Comment by dr3amnightmare** [comment]
Problem seems to lie in openmodularturrets.compatability.IGWSupportNotifier in the onPlayerJoin function. Problem will only exist when In-Game Wiki is not present in the mods folder. Hope for a speedy fix. Cheers

**Comment by Poenjabiesous** [comment]
Issue not fixed yet, but 2.2.1 on CurseForge works for the time being.

**Comment by Keridos** [comment]
Oh I think derped this.
