### ISSUE TITLE
(Feature) Advanced Security System

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#215]
An idea I had: Add in a complete security system with the following features:
1. control turret settings remotely
2. add the ability to name turretbases
3. groups support for targeting and trusted players, maybe including wildcard support for Names or such things.
4. an item to sync settings from one turret base to another

Post your feedback here :)

**Comment by ImSoBored246** [comment]
This sounds good. Maybe for syncing data you could have a "Database" block with:
A) A frequency
B) A card to synchronize data
C) Both
I'm sorry if my suggestions are horrible or vague, I'm new to things like this.

**Comment by Keridos** [comment]
@Poenjabiesous what do you think about this, maybe good features for 3.0.0?

**Comment by Poenjabiesous** [comment]
Yeah, we can definitely add this in. I already have an idea about how I would like to approach this, but I will need to tinker first. (Thinking about an item with a gui where your turretbases show up in, using some mechanism).

**Comment by ImSoBored246** [comment]
@Keridos That's a good point, but I think that you may have missed my point slightly. Although extra computer mod integration would be nice (and probably not added), the Database block mentioned would allow remote turret control with the mod alone and not just with a computer. The computer integration was just wishful thinking.

**Comment by Keridos** [comment]
This will come in a seperate mod since we are making OpenModularTurrets modular :)
