### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Sermax18** [OpenModularTurretsTeam/OpenModularTurrets#216]
when i place turret base any tier i get crash mods:thermal expansion,openmodularturrets 2.2.2-217,opencompunters 1.5.21.41

**Comment by Keridos** [comment]
We need a crash report or better the game log to provide any help here.

**Comment by Poenjabiesous** [comment]
Please see the landing page regarding crash logs, recreate the ticket. The information here does not help us in any way.

**Comment by Keridos** [comment]
@Poenjabiesous why recreate the ticket? That is just more overhead for us here. People can edit their issues.

**Comment by Poenjabiesous** [comment]
I feel that when ticket creators are forced to look at the stacktrace they post, more than half of the tickets won't be opened since they will most likely see the issue. The landing page stipulates that this is one of the requirements when opening a crash issue, which is why I closed this one.
