### ISSUE TITLE
Crash without IC2 (OMT 2.2.2.217)

### ISSUE THREAD

**Issue by MineWitherMC** [OpenModularTurretsTeam/OpenModularTurrets#217]
The OMT 2.2.2-217 crashes when I place turret base (that was tier 5 for me, don't think if that matters):
http://codepad.org/OduBfcDN

**Comment by Keridos** [comment]
This is weird, should not happen... and it doesnt happen for me in a testing instance. There is something wrong with any other mods in your pack, apparently forge thinks IC2 is installed.

**Comment by MineWitherMC** [comment]
@Keridos I will test some my mods that have IC2 api with OMT and tell results in about 1 hour.

25.04.2016, 16:21, "Keridos" <notifications@github.com>:

**Comment by Poenjabiesous** [comment]
Thanks @MineWitherMC

**Comment by MineWitherMC** [comment]
Also I'm sure that this bug is related to several Flux Omniwrench crashes (like this https://github.com/CoFH/Feedback/issues/1115). So maybe it's Mekanism. But not sure, will tell results after testing.

25.04.2016, 16:26, "Poenjabiesous" <notifications@github.com>:

**Comment by MineWitherMC** [comment]
I'm sorry пгны but I couldn't find mods causing this issue...

**Comment by Keridos** [comment]
Tried without Mekanism?

**Comment by MineWitherMC** [comment]
Tried with: Mek, MFR, forestry, OpenComputers, RA, RailCraft, AE2, TCo, IE and gendustry. It's not one of them. Maybe Rotarycraft? Will test now...

**Comment by Keridos** [comment]
I removed Reikas mods out of my tech modpack some time ago because I had quite a lot of intermod compatability issues with it. Especially DragonAPI.

**Comment by MineWitherMC** [comment]
That is not RC/D.Api though...
