### ISSUE TITLE
Bug: missing GUI buttons in MP

### ISSUE THREAD

**Issue by krovn** [OpenModularTurretsTeam/OpenModularTurrets#220]
Seems like GUI buttons (drop turret/base, configuration) are missing in MP. 
Logs are clear, no error messages, mod loads normally.
In SP GUI is available with same mod set.

UPD:
Possible overlay with NEI

Version information
Minecraft 1.7.10
MCP 9.05
FML 7.10.99.99
Minecraft Forge 10.13.4.1492 
Java 8u11(client)/8u77(server)
OpenModularTurrets 2.2.2

**Comment by Keridos** [comment]
Offline mode enabled?

**Comment by ColonelHades** [comment]
> Offline mode enabled? We had like a dozen reports like that one and all point towards offline mode servers or cracked servers.

Is there a fix for it?

**Comment by ColonelHades** [comment]
Is there a fix for this type of issiue?

**Comment by Keridos** [comment]
Enable offline mode in the config.
