### ISSUE TITLE
Turret setting buttons missing in SMP

### ISSUE THREAD

**Issue by Shadow79473** [OpenModularTurretsTeam/OpenModularTurrets#222]
When playing on single player the buttons appear fine, however in multiplayer the buttons are not there, and it is impossible to change the turret setting or get it to drop
This is on Singleplayer
![2016-05-07_21 19 06](https://cloud.githubusercontent.com/assets/8226620/15095675/c7ed088e-1499-11e6-95ea-035025268e12.png)
This is on Multiplayer
![2016-05-07_21 20 38](https://cloud.githubusercontent.com/assets/8226620/15095676/d09e62a2-1499-11e6-8af5-c4dafbed14ac.png)

This is on the latest version 2.2.0

**Comment by Poenjabiesous** [comment]
Please read our disclaimer on the landing page regarding opening new issue tickets. This issue was reported at least 8 times now, and is linked to offline servers/cracked clients. Please check closed tickets in the future before opening up new ones.

**Comment by Keridos** [comment]
This is fixed in v2.2.5 but you are f*cking greedy if you do not want to pay for minecraft and have a cracked client. If you have fun with the game the money is not *wasted*. Support the developers to make the game better and more awesome.
