### ISSUE TITLE
Cannot add Turrets to bases

### ISSUE THREAD

**Issue by SplinterCube** [OpenModularTurretsTeam/OpenModularTurrets#224]
I'm running Forge 1.7.10 Forge 10.13.4.1614-1.7.10 without any other mods but this one. Is there something I'm missing or all you have to do is right click with the turret in hand on the base? I tried many combinations: example i tried using a t1 base with the t1 potato gun with a lever, but I'm unable to mount either the lever or the turret to the base. every time i right click with the turret in hand it brings up the GUI for configuring the base block.

I tried using:
OpenModularTurrets-1.7.10-2.2.2-218
OpenModularTurrets-1.7.10-2.2.2-217
OpenModularTurrets-1.7.10-2.1.6-189

I deleted the config files after each change!

I could not find anyone else having this problem. 
I can send more information on this if needed, but I'm not seeing any errors

**Comment by Keridos** [comment]
Tried shift click?

**Comment by Poenjabiesous** [comment]
You need to shift-click, otherwise the GUI will open each and every time.
