### ISSUE TITLE
Server Side Config bug

### ISSUE THREAD

**Issue by anar4732** [OpenModularTurretsTeam/OpenModularTurrets#225]
Hello. We are currently working on a modded server and we are using your OMT but we have an issue. İts okay in single player but when we use it on the server turret configs are not showing at the sides. We cant configure it. İts a very big issue for us. If you can solve this problem we would really appriciate it. Thank you for the good work.

**Comment by Keridos** [comment]
?

**Comment by Poenjabiesous** [comment]
Is the server in online mode and does it have general internet access?

**Comment by anar4732** [comment]
We tried it in the online mod and it worked but our server is going to be on online mod off so is it possible to make it work with offline mod

**Comment by Poenjabiesous** [comment]
No, it wont. Our mod works with player UUID's, and that means that the server needs to be in online mode. As we have stated many times before, we do not support offline servers/cracked clients.

**Comment by anar4732** [comment]
We understand your consern about offline servers. But for once can you please add a config to change the UUID to player nicknames. We would really appreciate that. OMT is our base mod of the modpack. We really need this config option. Please let us use this great mod. Thank you for the great work please keep going and improving.

**Comment by Poenjabiesous** [comment]
That would unfortunately mean a rewrite of most of the security in the mod, and implementing that would be giving the option to use our mod with cracked clients and servers. We cant do that, and we have never supported it before. In my opinion, I cant think of a reason to run a server in offline mode other than allowing non-premium players access to it.

**Comment by Keridos** [comment]
This is fixed in v2.2.5 but you are f*cking greedy if you do not want to pay for minecraft. If you have fun with the game the money is not *wasted*. Support the developers to make the game better and more awesome, and stop being so damn obnoxious about not having offline support.
