### ISSUE TITLE
[Feature] Factions Compatibilty

### ISSUE THREAD

**Issue by Acdrybones** [OpenModularTurretsTeam/OpenModularTurrets#226]
It would be pretty amazing if this mod had compatibility with Factions. That way, turrets can be set to target Enemy & Neutral factions, and target any Factions you set to kill.

**Comment by Keridos** [comment]
Is that a forge mod?

**Comment by Acdrybones** [comment]
No, it is a Plugin for a server.

**Comment by Keridos** [comment]
Then this is most likely not gonna be implemented until someone can point out how we can do that without building our mod against Cauldron or some other forge/bukkit crossover. Also see issue #130.
