### ISSUE TITLE
Homing rockets explode on launch

### ISSUE THREAD

**Issue by Stalkstalks** [OpenModularTurretsTeam/OpenModularTurrets#227]
Hi, I'm using 2.2.2-217, and if I set rockets to be able to home, they explode immediately on launch. I saw that there was a similar bug that was fixed quite some time ago - perhaps this is related to rockets being changed to not home by default?

**Comment by Keridos** [comment]
@Poenjabiesous can you take a look at that?

**Comment by Poenjabiesous** [comment]
I'll try, I'm not home atm, and wont be for about 2 more weeks. But I think I know whats causing this.

**Comment by Keridos** [comment]
@VoltyFarstar Any news on this?

**Comment by VoltyFarstar** [comment]
The projectile speed is different when homing is enabled, and the impact ignore time of 2 ticks is not sufficient for the projectile to then escape the block, and collides with the turret head.

We will need to keep an eye on the homing functionality, it seems to be badly implemented and was not added by a member of the OMT team.
