### ISSUE TITLE
Multiplayer Configuration Issue

### ISSUE THREAD

**Issue by Andrew2070** [OpenModularTurretsTeam/OpenModularTurrets#228]
Hi,

In a multiplayer server, the turret buttons have disappeared making it impossible to target players.
I looked through the closed issues and found one, where this is intentional due to UUID support.
I was wondering if it could be allowed to function on Cracked servers as well as they are important.
I mean, I have flans and the only thing that can auto kill a fighter jet is a rocket launcher turret.

Anyhow, I think it is set only to work on online mode, however I cannot be sure about that.
Even so, if it isn't could this be fixed to work on all servers regardless of Mojang being in the way.
The reason people want turrets is to protect themselves from THOSE cracked people in factions.

[Private Modded Factions Server] - I really kinda need turrets to kill my friends, but 2 are cracked.

~Many thanks, very amazing mod especially with CC support :)

**Comment by Poenjabiesous** [comment]
Hi Andrew

Unfortunately, we can't support non-premium client based issues, as the one described above. You are not the first person to ask this, and you will most probably not be the last.

If you like a game, its always worth supporting the developer by buying it. If not, the community supporting that game (thats us) can not support you.

**Comment by Keridos** [comment]
This is fixed in v2.2.5 but your players are f*cking greedy ifthey do not want to pay for minecraft. If they have fun with the game their money is not *wasted*. Support the developers to make the game better and more awesome, and if they are unwilling to play tell them from me to stop being so obnoxious about not having offline support.
