### ISSUE TITLE
Config option to allow OPs to access any turret

### ISSUE THREAD

**Issue by Yanniclord** [OpenModularTurretsTeam/OpenModularTurrets#229]
Would it be possible to add a simple config option to let Operators open any turret? It sometimes is necessary on my server due to people overspamming their bases with Turrets (funny enough), and i often need to break them down instead of just being able to control them.

Also, any possibility in doing a quick hotfix to fix the Y axis bug? Explained: The Y axis option is always set to 2, and if you set it to 9, and the server reboots (or you just relog), it is back at 2.

**Comment by Keridos** [comment]
The bugfix can be made, yeah, should be fairly trivial, gonna get that in in the next days.
