### ISSUE TITLE
High network bandwith when placing turret bases

### ISSUE THREAD

**Issue by LemADEC** [OpenModularTurretsTeam/OpenModularTurrets#232]
A player base reached 200kB/s of network bandwidth, it was narrowed down to the turret bases.
Dismounting the railguns didn't help.
Each dismounted Turret base (tier 5) saved us ~7kB/s per player in the area.
Just in case, here's a screenshot of the turret setup, through apparently,  the default turret configuration is enough to cause the lag:
![image](https://cloud.githubusercontent.com/assets/4776032/17310310/de3bf5e4-5843-11e6-89e1-f19c0aac0d76.png)

There was no power connection to any Turret bases.

Observed with OpenModularTurrets-1.7.10-2.2.3-220

**Comment by Keridos** [comment]
Try this please: https://jenkins.ironhide.de/job/OpenModularTurrets/223/

**Comment by LemADEC** [comment]
Network usage due to turret bases is 50% lower, so it's better but there's still too much bandwidth usage.

**Comment by VoltyFarstar** [comment]
I take it that this network usage measurement was made server side?

**Comment by LemADEC** [comment]
No, we've way too many players online for server side measurement.
I do it client side, and teleport in/out of the area several times to confirm there's no interferences.
I've also tried loading existing chunk or placing a new setup, but there's no change in bandwidth usage.

**Comment by Keridos** [comment]
Try this please, not sure if this will improve anthing or totally bug the client-server sync. https://jenkins.ironhide.de/job/OpenModularTurrets/lastSuccessfulBuild/artifact/build/libs/OpenModularTurrets-1.7.10-2.2.4-224.jar

**Comment by LemADEC** [comment]
I did a quick test in SMP, it's much better with no visible network usage from the turret base.
Turrets were turning around and shooting properly a few cows.
Inventory and added players do show up in GUI when I reopen it.
Solar addon is properly shown in GUI and on the turret itself.

However, the energy storage and attack flags won't refresh on client side until I reconnect to the server.
Using WAILA, the energy level does change in the in-game tooltip, but opening the GUI shows no update.

**Comment by Keridos** [comment]
Still need to tackle the update thing then, this is way easier in 1.9+, you can just override some method in the Server side GUI element and send the data just to the players who have the GUI opened. in 1.7.10 it is a bit uglier, we might probably need to end up just sending data to all players within lets say 6 blocks or so (the distance you need to be in to open the GUI).

**Comment by Keridos** [comment]
Try this please: https://jenkins.ironhide.de/job/OpenModularTurrets/lastSuccessfulBuild/artifact/build/libs/OpenModularTurrets-1.7.10-2.2.4-225.jar

This should just send a big stream of data to the person who is actually in the GUI of the base.
Also this fixes the visual stuttering(button changes, changes back until about a fifth of a second later it shows the correct value again) when changing configs in the configure GUI in SMP, yay.

**Comment by LemADEC** [comment]
Network usage is negligeable, even I'm opening a GUI.
GUI content is refreshing properly.
Everything fine.

When registering a new player, you need to close/open the GUI to be able to change it's permissions. This behavior already exists in OpenModularTurrets-1.7.10-2.2.3-220, so it's not a regression.
