### ISSUE TITLE
OpenModularTurret 2.2.3 does not fix IC2 Compat

### ISSUE THREAD

**Issue by Joshwoo70** [OpenModularTurretsTeam/OpenModularTurrets#233]
hello! Just reporting a bug from the ferret business modpack.
It seems that the latest does not fix the IC2 issues and still crashes.
https://gist.github.com/Joshwoo70/3fb9ad293c6d6c71baf7720f7906f915
https://gist.github.com/Joshwoo70/3ccb2649afeae7f96fefdaa92622a665

**Comment by VoltyFarstar** [comment]
Cool, thanks for the feedback. Will look into it.

**Comment by VoltyFarstar** [comment]
(Thanks for being thorough with the stacktraces)

**Comment by VoltyFarstar** [comment]
If possible, could you update your forge version (if possible) to the latest 1.7.10 build and re-test?

**Comment by Joshwoo70** [comment]
Okay I will have a look

**Comment by Joshwoo70** [comment]
Checked, it is the latest forge version.

**Comment by Keridos** [comment]
This is weird, I am literally checking if the interface we use is present in the classpath. I guess some mod may be shipping an incomplete ic2 api in that modpack. Can you please check if one of the jars has an "ic2" folder in it?

**Comment by Joshwoo70** [comment]
@Keridos thanks for the info. can we have a config option to override incase this happens?

**Comment by TheBlueTroll** [comment]
it has been fixed in the latest dev build OpenModularTurrets-1.7.10-2.2.4-225

**Comment by Joshwoo70** [comment]
Isse closed.
