### ISSUE TITLE
[1.7.10-2.2.4-225] Server bug

### ISSUE THREAD

**Issue by Maks2103** [OpenModularTurretsTeam/OpenModularTurrets#234]
Currently (in 2.2.4-255) unable to configurate turret on server.

**Comment by Keridos** [comment]
Turn off offline mode.

**Comment by Maks2103** [comment]
I don't have an a minecraft account, and don't want to waste my money, so please fix this bug already.

**Comment by VoltyFarstar** [comment]
This is not a bug. This mod uses your UUID from Mojang (as any other mod that implements player ownership) We will never support cracked clients or servers. If you see the game as a waste of money, why are you playing it and logging this ticket?

**Comment by Keridos** [comment]
This is fixed in v2.2.5 but you are f*cking greedy if you do not want to pay for minecraft. If you have fun with the game the money is not *wasted*. Support the developers to make the game better and more awesome, and stop being so damn obnoxious about not having offline support.

**Comment by Maks2103** [comment]
@Keridos , i don't interested of new minecraft versions development 'cuz i f*cking hate all versions above 1.8 and the game's price in country that i living in is very high. Thanks for fixing this bug.
P.S. I'm still going to buy this game, but later.

**Comment by Fortist** [comment]
Actually, as someone who doesnt always play online (internet goes out too, you know) this shouldnt have been a thing in the first place. Plus the MC account severs go down every once in a while.

Also, stop self censoring yourself like a pussy.
