### ISSUE TITLE
Feature Request: A manual with screenshots how to use the mod.

### ISSUE THREAD

**Issue by MilesTFox** [OpenModularTurretsTeam/OpenModularTurrets#235]
This mod seriously is a mystery.

Google cannot find any form of manual, the page on the ftbwiki has been deleted.

There are some youtube mod spotlight videos, but I do not use youtube.

For example, one thing that I cannot find info on anywhere is how to add the upgrades!

**Comment by MilesTFox** [comment]
Note: I am aware of the IGW mod entries, and they also do not tell me anything about adding the upgrades.

**Comment by MilesTFox** [comment]
Note: did some digging, Version: Open Modular Turrets 2.2.2-217 included in Bevo's Tech Pack BTP-Reborn-BetaX-Hotfix

**Comment by SephirothWS** [comment]
Upgrades are inserted into the upgrade slots of any **turret base**. just right-click a turret base with an empty hand to open its GUI.

**Comment by MilesTFox** [comment]
I don't see any upgrade slots. It is a tier 1 turret base. Do different
tiers have more/less upgrade slots? (this information is not included in
the IGW either)

**Comment by Keridos** [comment]
If needed I will modify the wiki pages to be a bit more accurate. Also maybe change the tooltip on the turretbases.

**Comment by Keridos** [comment]
Also: Turretbases have a tooltip that displays pretty much everything you need to know about them already, including upgrade and addon slots. NEI/JEI easily finds the upgrades and addons and they have a tooltip as well stating what they do.
