### ISSUE TITLE
No gui to add players

### ISSUE THREAD

**Issue by djoey123** [OpenModularTurretsTeam/OpenModularTurrets#240]
There is no Gui to add trusted players
or change the modes of the Turret

http://prntscr.com/chfc2u

I am running the latest version

**Comment by VoltyFarstar** [comment]
Are you running a cracked client/offline server?

**Comment by djoey123** [comment]
It is a offline server is that the problem? i dont got cracked players.

**Comment by VoltyFarstar** [comment]
Yes, if your server is in offline mode, OMT does not have access to player UUID's that is used to define turret ownership.

**Comment by djoey123** [comment]
Is it possible to bypass that?

**Comment by VoltyFarstar** [comment]
No. Is there a reason why your server is in offline mode?

**Comment by djoey123** [comment]
When i change it back to online mode now everyone will lose ther stuff and homes and claims

**Comment by Cbert** [comment]
**djoey123**, you didn’t made mistake, you made right choice. The mistake made by OpenModularTurrets author, and now everyday world remind him that.

**Comment by Keridos** [comment]
We will probably add offline mode support, just to be clear that that will make turrets unsafe if no method of authentication is available since we can only check the playernames (and those can be faked)
