### ISSUE TITLE
Turret base's configure UI does not appear in multiplayer

### ISSUE THREAD

**Issue by ied206** [OpenModularTurretsTeam/OpenModularTurrets#242]
I am using minecraft 1.7.10 version of OpenModularTurrets, and found out in multiplayer, turret base's UI is crippled and unable to configure it.

**Singleplayer**
![sinpleplayer](https://cloud.githubusercontent.com/assets/7675657/18816993/16e4a5a4-8390-11e6-8fc5-4ad81343f382.png)

**Multiplayer**
![multiplayer](https://cloud.githubusercontent.com/assets/7675657/18816995/17e6a812-8390-11e6-826f-d5da6e3d3fd6.png)

Also, I set **B:"Can turrets attack neutrals?"** to false in **globaltargetingparameters** section of OpenModularTurrets.cfg, but in game it seems to be ignored.

**Comment by VoltyFarstar** [comment]
Please read our policy on the landing page about posting new tickets. This was answered many times before. As for the targeting parameter, have you actually tested if a neutral mob gets shot with your settings?
