### ISSUE TITLE
1.10.2 Turret Targeting

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#249]
Turret Targeting is partially broken/the projectiles somehow do not hit.
- [x] Rail Gun
- [x] Laser
- [x] disposable
- [x] rocket
- [x] incendiary
- [x] gunturret
- [x] grenade
- [x] potato

**Comment by Keridos** [comment]
@tossaponk can you maybe take a look at that too?

**Comment by VoltyFarstar** [comment]
This has to do with the way the projectiles ignore impact for the first few ticks. I'll look into this.

**Comment by Keridos** [comment]
It worked fairly fine for me yesterday
