### ISSUE TITLE
1.10.2 - Server crash on load

### ISSUE THREAD

**Issue by Anteater46** [OpenModularTurretsTeam/OpenModularTurrets#251]
Log: http://pastebin.com/3sxwUQWH

**Comment by canitzp** [comment]
Same issue for me. It is because https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.10.2/src/main/java/omtteam/openmodularturrets/proxy/CommonProxy.java#L20 is called in your common proxy, so server side too

**Comment by Keridos** [comment]
Yes, gonna push a build that fixes this now.

**Comment by Keridos** [comment]
https://minecraft.curseforge.com/projects/openmodularturrets/files/2352439
