### ISSUE TITLE
1.7.10-2.2.6-227 IC2 Power support

### ISSUE THREAD

**Issue by skushnarev** [OpenModularTurretsTeam/OpenModularTurrets#252]
HI!
I'm using version 1.7.10-2.2.6-227. Turrets do not use EU energy. In settings:
```
modcompatability {
     B: "Can turrets be powered with EU?" = True
     D: "EU to RF Ratio" = 8.0
     B: "Enable offline mode support (warning, makes turrets fairly unsafe)?" = False
}
```

IC2 cable is not connected. A cable connects GregTech 5 but does not transmit energy. Although the GT itself converts its energy into RF, but the charge is not.

**Comment by Keridos** [comment]
RF should work fine, IC2 support should work fine, gonna test that here

**Comment by skushnarev** [comment]
I tested several versions. Something went wrong, starting with 2.2.3-220.
Version 2.2.2-217 works GregTech and IC2.

**Comment by Keridos** [comment]
Cannot reproduce this, what is your IC2 version?

**Comment by skushnarev** [comment]
forge 10.13.4.1614-1.7.10 
industrialcraft-2-2.2.810-experimental
gregtech-5.09.26

**Comment by Keridos** [comment]
Try removing gregtech from the mods and see if this exist please, it works fine for me in my local dev build even with the same IC2 version.

**Comment by VoltyFarstar** [comment]
I can confirm that everything works fine here as well. Perhaps Gregtech overrides the EnergySink/something else interface on runtime to a non standard api version?
