### ISSUE TITLE
Game crashes when I put a capacitor for powering the turrets

### ISSUE THREAD

**Issue by KiraLinux** [OpenModularTurretsTeam/OpenModularTurrets#255]
[crash-2016-12-05_01.15.14-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/629869/crash-2016-12-05_01.15.14-server.txt)

**Comment by Keridos** [comment]
Try this build of OMLib please: https://jenkins.ironhide.de/job/OMLib/lastSuccessfulBuild/artifact/build/libs/omlib-1.10.2-3.0.0-28.jar

**Comment by KiraLinux** [comment]
Thank you so much

**Comment by VoltyFarstar** [comment]
@KiraLinux, can you please provide feedback for us after you have tested?
