### ISSUE TITLE
when I added the improvement of the turret game crashes

### ISSUE THREAD

**Issue by KiraLinux** [OpenModularTurretsTeam/OpenModularTurrets#256]
[crash-2016-12-06_10.38.58-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/633193/crash-2016-12-06_10.38.58-server.txt)

**Comment by Keridos** [comment]
check curseforge for new release, thanks!

**Comment by KiraLinux** [comment]
thank you so much
