### ISSUE TITLE
Game crash when trying to get turret to shoot at players

### ISSUE THREAD

**Issue by TheCodedOne** [OpenModularTurretsTeam/OpenModularTurrets#263]
Crashes when i try to toggle target players in the GUI, OMLib config is set to support offline mode if that is of any concequence, https://gist.github.com/TheCodedOne/a426e177270ad6ff8664dd6656f9553d

**Comment by Keridos** [comment]
Try this please: https://jenkins.ironhide.de/job/OMLib/38/ https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/43/

**Comment by TheCodedOne** [comment]
It no longer crashes with that, but i am unable to add new trusted players

**Comment by Keridos** [comment]
OK that is weird, I am relying on the username cache of the server that *should* still work in offline mode.

**Comment by Keridos** [comment]
Try this please https://jenkins.ironhide.de/job/OMLib/39/

**Comment by TheCodedOne** [comment]
That one seems to work

**Comment by Keridos** [comment]
Ok great! Thanks for the bugreport, closing this now.
