### ISSUE TITLE
[1.10.2] Crash with Ender IO + Sponge

### ISSUE THREAD

**Issue by ElvenChaos** [OpenModularTurretsTeam/OpenModularTurrets#264]
Server-side only, OMT causes a crash when used along-side Ender IO and Sponge **together**.

Forge 2185
Sponge 5.1.0 - 1992
OMT 3.0.0 - 42
EIO - 139

Crash log: http://pastebin.com/qXVxB1iQ

**Comment by Keridos** [comment]
I see no trace that this is caused by OMT and I have absolutely no idea what causes that NPE, too

**Comment by ElvenChaos** [comment]
It can be recreated with just the above mods (plus required libraries) above. I only started getting that error when I added in OMT, so I went through my modlist to see which combination of mods was causing the issue, and ended up with the above. Do you think I should open a ticket with the other two mods to see if something can be figured out?

**Comment by Keridos** [comment]
Yeah would be nice, I have pretty much no idea why this should happen.

**Comment by Bluexin** [comment]
@ElvenChaos did you report it to them? Couldn't find on the issue tracker.
The error refers to somewhere in this method :
https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/fml/common/MixinLoader.java#L91
I cannot do further testing right now, but *might* in a somewhat near future.

**Comment by Keridos** [comment]
Any updates on this?
