### ISSUE TITLE
Unable to add trusted players using turret GUI

### ISSUE THREAD

**Issue by adam8797** [OpenModularTurretsTeam/OpenModularTurrets#265]
Title explains. I'm unable to add any players to the list of trusted players.

Server is in Online Mode. 

We're using the Project Ozone 2 Pack, which appears to be using version 2.2.7 of OMT

Steps to reproduce:

1. Place turret base and turret (We used tested both Laser, Rail, and Gun turrets, with their respective bases)
2. Open the "Configure" GUI
3. Type a valid username into the box.
4. Click the "+" button.
5. Nothing happens. Even after GUI close/open the name is not added to the list.

**Comment by Keridos** [comment]
Can you try it with this build please: https://jenkins.ironhide.de/job/OpenModularTurrets/229/ ?

**Comment by adam8797** [comment]
I installed build 229 on both client and server, with no luck.

Problem still persists.

**Comment by adam8797** [comment]
I managed to get a debugger attached, and I started stepping through the GUI code.

I've got to wait for a friend to get back on my server, but hopefully I'll have a lead for you in the morning.

**Comment by adam8797** [comment]
Alright. I did some debugging with a friend on the server, and without taking a deep dive into the whole project, it appears that there is an issue in `PlayerUtil.getPlayerUUID()`

It appears that `UsernameCache.getMap().entrySet()` only contains my username, regardless of any other players on the server. 

Therefore, when `TurretBase.addTrustedPlayer()` is called, it can never find the uuid of other players. Because the uuid is null, and the server is set for online mode, it returns `false`.

I hope this is helpful

**Comment by Keridos** [comment]
Ok that is strange, the Username Cache should contain all active players on the server in online mode. Gonna ask around if that is intended.

**Comment by Keridos** [comment]
Try this build please: https://jenkins.ironhide.de/job/OpenModularTurrets/230/

**Comment by adam8797** [comment]
No dice. Same issue as before.  

`PlayerUtil.java:73` only loops once, for my username, even when another user is connected.

That tells me that, again, `UsernameCache.getMap().entrySet()` only has one entry on the client.

I'm going to be in the game for most of the night tonight. If you want, I'd be happy to give you server details, and we can figure this out.

**Comment by Keridos** [comment]
The client should not loop through that at all, the change is just sent to the server, the server then executes addtrustedplayer and adds it to the base, then it just sends it back to the client. Works fine for me here on a dedicated server with my 2 Accounts.

**Comment by adam8797** [comment]
I'll have to wait for a friend to get back on and check. It was definitely running on the client though.

**Comment by Keridos** [comment]
Try this now: https://jenkins.ironhide.de/job/OpenModularTurrets/231/
I removed the entire check if the name is valid from the client, it should now never be executed on the client.

**Comment by adam8797** [comment]
Looks like that did the trick.

**Comment by Keridos** [comment]
This will probably glitch out for very very laggy servers, in that case you should still need to reopen the GUI then.
