### ISSUE TITLE
When placed on an Airship, Turrents lose their ability to aim

### ISSUE THREAD

**Issue by BigBastard** [OpenModularTurretsTeam/OpenModularTurrets#266]
This is actually an issue that occurs with my mod Valkyrien Warfare, of which the turrents cant aim when placed on a Physics Entity.

![image](https://cloud.githubusercontent.com/assets/13895645/21529865/c5d70662-ccf9-11e6-9092-1d90e290b560.png)

Its probably an issue with the targeting system not knowing the turrets real position is relative to the world (Physics Entities use their own local block coordinates relative to itself). I have an API that should compensate for this issue.

How should I start?

**Comment by Keridos** [comment]
Check this class, it contains most targeting functions: https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.10.2/src/main/java/omtteam/openmodularturrets/util/TurretHeadUtil.java

If you want to help our mod to be optionally dependable on your API, you can fork the repo and bring it the changes yourself, we will then evaluate them and pull them if we are satisfied with them. You can try to reach me on the MMD discord or on espernet IRC, I am active in both, if you need help.

**Comment by Sunspot0411** [comment]
Hi there, last checked, turrets still cannot aim when put on an airship.

**Comment by BigBastard** [comment]
:/ Sorry I have the fix coded, I just havent bothered getting it pulled onto here :P

Will do over weekend

**Comment by Keridos** [comment]
Thanks for the pull request 👍
