### ISSUE TITLE
Turret Base's in NEI are not reading currectly

### ISSUE THREAD

**Issue by idnthvn** [OpenModularTurretsTeam/OpenModularTurrets#270]
Currently updated to version 2.2.9 for version 1.7.10.
I was using 2.2.4 and thought 2.2.9 ma fix it, but did not. 
My issue is that Tier 3, 4, and 5 are not reading the config correctly.
When placing a Tier 5, in the NEI shows 500,000RF when indeed the tier 4 should be 500,000RF
I did modify the config for custom RF and they work when you place the base's down, So for instance, 
a tier 5 base should hold 10,000,000RF, in NEI shows 500,000 but when placed, the actual base shows 10,000,000RF.
Does this make any sense?
Like Tier 3 and Tier 2 are reading the same part and show the exact same information in NEI.
I am either hopeing for an update, or maybe even a (Hey here is the correct location for that, change it here and compile) and i can do that. 
Let me know please and thank you

**Comment by Keridos** [comment]
Will be fixed.

**Comment by idnthvn** [comment]
Cool so i can fix this on my own, or you coming out with a release soon?

**Comment by Dream-Master** [comment]
@idnthvn https://jenkins.ironhide.de/job/OpenModularTurrets/
@Keridos hope is is ok to leak the source ;)

**Comment by idnthvn** [comment]
nice thank you
