### ISSUE TITLE
[1.10.2-3.0.0-16] Unable to add trusted friends

### ISSUE THREAD

**Issue by clifftrials** [OpenModularTurretsTeam/OpenModularTurrets#271]
Hello,

Similar to issue #265, I am unable to add trusted friends to my turrets. I enter my friends name, hit the +, and nothing happens. I am running a 1.10.2 Forge Server 12.18.3.2185 and verified that the server is running in Online mode. Anything I need to do on my end? I realize the 1.10.2 version is in Alpha so if this missing feature is known and still pending, my humble apologies. Thank you!

**Comment by Keridos** [comment]
Gonna take a look at this soonish, might have a clue what is happening there.

**Comment by clifftrials** [comment]
Yes, they have, they were also online at the time when I was trying to add them. Thanks for looking into it!

**Comment by Keridos** [comment]
This apparently is caused by client server desyncs...
