### ISSUE TITLE
Chain Lighting Turret

### ISSUE THREAD

**Issue by Notawallplan** [OpenModularTurretsTeam/OpenModularTurrets#272]
Something i'd like to see in OMT.

- Chain Lightning Turret

Tier/minimum tier base: 5
Range: 15b (can be even shorter, but making it longer would probably make it OP.)
Accuracy: Pin point
Ammo Type: None
Proj Damage: 3.0 hearts
AoE Radius: 4
Shots/second: 0.5
RF/Shot: 50000

When fired, there's not a projectile per say. It applies damage (with a particle effect) to the mob directly and then chains to one other mob within the AoE radius with the same effect (on a small delay) until it has chained 2 times, dealing 1 less damage per transit. The first hit sets the mob on fire. Scattershot has the turret pick random enemies to target other than the main one. Damage boost only mitigates the damage penalty the chains have.

**Comment by VoltyFarstar** [comment]
I was looking into adding some new turrets at some point, will keep this one in mind. Thanks for your input.

**Comment by Notawallplan** [comment]
I'm fine with you changing the numbers around. They really just came off the top of my head.

**Comment by Keridos** [comment]
I kind of like this idea, would be a cool turret 👍

**Comment by Keridos** [comment]
See #324
