### ISSUE TITLE
[1.10.2]  "Can OPs access all turrets?" not working

### ISSUE THREAD

**Issue by DeadSix27** [OpenModularTurretsTeam/OpenModularTurrets#273]
I've set, "B:"Can OPs access all turrets?"=true" and despite being OP I can not access any other users turret.

On that note, I was trying to use that to work-around this bug:

https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/271

**Comment by Keridos** [comment]
Config works now but was moved to OMLib
