### ISSUE TITLE
Compatibility problems

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#274]
Hi there, I just tried the newest 1.10.2 version, it seems this mod does not include compatibility for Valkyrien Warfare mod and IC2 experiment. Hope you could get these fixed. Thanks!

**Comment by Keridos** [comment]
Valkyrien Warfare is quite a big project and I think the author of it is already working on that (see the appropriate issue). IC2 support *should* work, I am gonna retest that though.

**Comment by Sunspot0411** [comment]
My IC2 version is :industrialcraft-2-2.6.142-ex110

**Comment by Keridos** [comment]
And what does not work? Power transfer works fine her for me.

**Comment by Sunspot0411** [comment]
I could not connect turret bases and generators, bases do not accept IC2 wires.

**Comment by Sunspot0411** [comment]
![2017-01-21_13 08 14](https://cloud.githubusercontent.com/assets/25239527/22176963/bbd708a8-dfda-11e6-8460-1d8c8303138b.png)

**Comment by Keridos** [comment]
Very interesting, gonna test that outside of my dev environment, though debugging that may be difficult.

**Comment by Keridos** [comment]
Fixed!
