### ISSUE TITLE
Missing Walls

### ISSUE THREAD

**Issue by Utildayael** [OpenModularTurretsTeam/OpenModularTurrets#275]
I saw comment about walls/fences being back in and we're on the new .52 version on MC 1.10.2 but... I'm not seeing them. Am I missing something? Checked config as well to make sure it wasn't something I had to turn on. :(

Cheers

**Comment by Keridos** [comment]
From the top of the OMT page on curseforge:
News: 1.10.2 Port still in progress, alpha is released. Most things seem to work, some errors will still need to be fixed, so bear with us until we get this. You can however test the mod, but please message Keridos directly for any bugreports. ´´´You can also get an alpha build of the mod that contains the passive defenses from OMT (walls etc. and more) now [here](https://minecraft.curseforge.com/projects/open-modular-passive-defense/)´´´. 1.10.2 Builds require OMLib. Please backup your worlds though, this is very much alpha and might break worlds.

**Comment by Utildayael** [comment]
Oh! Apologies. I didn't realize you took the passive defenses out of the main mod. I read that as the current alpha version had it. Didn't click link. Whoops. :)

Curious why removed from OpenTurrets? They complemented each other really well. 

Thanks

**Comment by Keridos** [comment]
We are making the mod more modular, and have additional plans for the passive defence mod and we are also adding an addon to OMT in the future that enables grouping and advanced control over turrets.

**Comment by Utildayael** [comment]
Ah. Makes sense. Fantastic to hear. Glad those pieces are still around! Thanks for the info. :)
