### ISSUE TITLE
Ammo configuration 

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#277]
Just want to ask could you allow us to config whether railgun bullets and rockets are able to destroy blocks or not in the future version?

**Comment by Keridos** [comment]
I think we have this disabled for a good reason, we might add a config though to do that.

**Comment by Sunspot0411** [comment]
I want this because now we have compatibility with VW mod, it would be interesting if we can use turrets to perform ship to ship combat. So maybe the targeting system also needs some upgrades so that turrets can lock on ships.

**Comment by Sunspot0411** [comment]
I think expending the potenial targets beyound mobs, natruals and players would be good. There are lots of mods that has characters cannot be placed into those categories, for example the Custome NPC mod.

**Comment by Keridos** [comment]
We can add CustomNPCs pretty much without a problem tbh. Gonna take a look on how to implement this though.

**Comment by Keridos** [comment]
The targeting system and ships might be not optimal to do since ships are large. per default we aim at the eye coordinates of any creature. That is not easily possible for ships. You can control the turrets manually via opencomputers however. Including rotation and shooting.

**Comment by Sunspot0411** [comment]
So you mean it is possible to destroy blocks now right?

**Comment by Sunspot0411** [comment]
Thank you very much! So is there any tutorial tells me how to use OpenComputers to operate turrets?

**Comment by Keridos** [comment]
Hm, should be pretty intuitive. Place turret base and provide energy to it.  then place turrets on it. If turret needs ammo place it in the base. Apply addons/upgrades as needed in the base. Almost all items should have tooltips for that.
