### ISSUE TITLE
Compatibility problem with VW mod

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#280]
Hi Keridos, I just tried the newest 1.10.2 version, when I place a turret base on my ship the game crashes.

**Comment by Sunspot0411** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  ValkyrienWarfareBase CoreMod (valkyrienwarfare-1.10.2-0.8.6d-47.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 1/31/17 12:36 AM
Description: Tesselating block model

java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at omtteam.openmodularturrets.client.render.models.CamoBakedModel.func_188616_a(CamoBakedModel.java:53)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at ValkyrienWarfareBase.Render.PhysRenderChunk$RenderLayer.updateList(PhysRenderChunk.java:167)
	at ValkyrienWarfareBase.Render.PhysRenderChunk$RenderLayer.renderBlockLayer(PhysRenderChunk.java:102)
	at ValkyrienWarfareBase.Render.PhysRenderChunk.renderBlockLayer(PhysRenderChunk.java:42)
	at ValkyrienWarfareBase.Render.PhysObjectRenderManager.renderBlockLayer(PhysObjectRenderManager.java:162)
	at ValkyrienWarfareBase.CoreMod.CallRunnerClient.onRenderBlockLayer(CallRunnerClient.java:465)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1298)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at omtteam.openmodularturrets.client.render.models.CamoBakedModel.func_188616_a(CamoBakedModel.java:53)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)

-- Block model being tesselated --
Details:
	Block: openmodularturrets:turret_base[tier=5]
	Block location: World: (-499996,128,-500000), Chunk: (at 4,8,0 in -31250,-31250; contains blocks -500000,0,-500000 to -499985,255,-499985), Region: (-977,-977; contains chunks -31264,-31264 to -31233,-31233, blocks -500224,0,-500224 to -499713,255,-499713)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)

-- Block being tesselated --
Details:
	Block type: ID #369 (tile.turret_base // omtteam.openmodularturrets.blocks.BlockTurretBase)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-499996,128,-500000), Chunk: (at 4,8,0 in -31250,-31250; contains blocks -500000,0,-500000 to -499985,255,-499985), Region: (-977,-977; contains chunks -31264,-31264 to -31233,-31233, blocks -500224,0,-500224 to -499713,255,-499713)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at ValkyrienWarfareBase.Render.PhysRenderChunk$RenderLayer.updateList(PhysRenderChunk.java:167)
	at ValkyrienWarfareBase.Render.PhysRenderChunk$RenderLayer.renderBlockLayer(PhysRenderChunk.java:102)
	at ValkyrienWarfareBase.Render.PhysRenderChunk.renderBlockLayer(PhysRenderChunk.java:42)
	at ValkyrienWarfareBase.Render.PhysObjectRenderManager.renderBlockLayer(PhysObjectRenderManager.java:162)
	at ValkyrienWarfareBase.CoreMod.CallRunnerClient.onRenderBlockLayer(CallRunnerClient.java:465)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1298)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Keystone2670'/159, l='MpServer', x=256.48, y=86.29, z=-430.48]]
	Chunk stats: MultiplayerChunkCache: 1117, 1117
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-192,64,252), Chunk: (at 0,4,12 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3847212 game time, 471759 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 122 total; [EntityCreeper['Creeper'/512, l='MpServer', x=266.45, y=74.00, z=-498.23], EntityZombie['Zombie'/257, l='MpServer', x=235.50, y=68.00, z=-388.50], EntityCreeper['Creeper'/513, l='MpServer', x=259.50, y=72.00, z=-497.50], EntityCreeper['Creeper'/258, l='MpServer', x=222.50, y=50.00, z=-378.50], EntityBat['Bat'/259, l='MpServer', x=210.32, y=53.10, z=-381.25], EntityBat['Bat'/260, l='MpServer', x=209.62, y=50.62, z=-374.74], EntitySkeleton['Skeleton'/261, l='MpServer', x=220.51, y=70.00, z=-374.25], EntityIronGolem['Iron Golem'/262, l='MpServer', x=209.05, y=160.00, z=-370.11], EntitySkeleton['Skeleton'/524, l='MpServer', x=298.34, y=72.00, z=-486.50], EntityBat['Bat'/525, l='MpServer', x=285.76, y=31.74, z=-468.11], EntityCreeper['Creeper'/526, l='MpServer', x=282.50, y=33.00, z=-476.50], EntityCreeper['Creeper'/527, l='MpServer', x=283.50, y=33.00, z=-475.50], EntitySheep['Sheep'/528, l='MpServer', x=281.74, y=72.00, z=-472.42], EntitySheep['Sheep'/529, l='MpServer', x=273.96, y=70.67, z=-478.50], EntityZombie['Zombie'/283, l='MpServer', x=204.50, y=69.00, z=-489.50], EntityItem['item.tile.turret_base_tier_five'/295, l='MpServer', x=255.30, y=70.00, z=-435.58], EntityItem['item.tile.turret_base_tier_five'/296, l='MpServer', x=255.35, y=67.00, z=-434.21], EntityItem['item.tile.turret_base_tier_five'/297, l='MpServer', x=252.23, y=82.54, z=-447.10], EntityItem['item.tile.rail_gun_turret'/298, l='MpServer', x=252.02, y=82.54, z=-447.27], EntityItem['item.item.bone'/299, l='MpServer', x=272.28, y=75.00, z=-411.90], EntityEnderman['Enderman'/305, l='MpServer', x=312.50, y=76.00, z=-439.50], EntityCreeper['Creeper'/309, l='MpServer', x=254.50, y=46.00, z=-356.50], EntitySkeleton['Skeleton'/317, l='MpServer', x=306.50, y=70.00, z=-428.50], EntitySkeleton['Skeleton'/318, l='MpServer', x=295.50, y=74.00, z=-413.50], EntityZombie['Zombie'/320, l='MpServer', x=258.26, y=25.00, z=-369.50], EntityCreeper['Creeper'/321, l='MpServer', x=260.50, y=72.00, z=-381.50], EntityCreeper['Creeper'/322, l='MpServer', x=258.50, y=72.00, z=-383.50], EntitySheep['Sheep'/324, l='MpServer', x=303.51, y=69.00, z=-444.23], EntityCreeper['Creeper'/337, l='MpServer', x=232.50, y=20.00, z=-359.50], EntitySpider['Spider'/338, l='MpServer', x=231.50, y=50.00, z=-367.50], EntitySheep['Sheep'/345, l='MpServer', x=295.51, y=70.00, z=-426.74], EntitySkeleton['Skeleton'/349, l='MpServer', x=274.50, y=53.00, z=-365.50], EntityBat['Bat'/357, l='MpServer', x=315.39, y=42.93, z=-389.16], EntityZombie['Zombie'/377, l='MpServer', x=266.50, y=31.00, z=-361.50], EntityZombie['Zombie'/160, l='MpServer', x=258.58, y=58.00, z=-420.30], EntityEnderman['Enderman'/161, l='MpServer', x=259.43, y=59.00, z=-421.49], EntityZombie['entity.Zombie.name'/162, l='MpServer', x=258.18, y=51.00, z=-430.67], EntityCreeper['Creeper'/163, l='MpServer', x=261.20, y=58.00, z=-417.44], EntityZombie['Zombie'/164, l='MpServer', x=258.32, y=58.92, z=-418.53], EntityItem['item.tile.turret_base_tier_five'/165, l='MpServer', x=261.51, y=65.00, z=-430.47], EntityItem['item.tile.laser_turret'/166, l='MpServer', x=263.11, y=68.00, z=-430.98], EntityItem['item.tile.laser_turret'/167, l='MpServer', x=262.70, y=64.00, z=-428.41], EntityItem['item.tile.turret_base_tier_five'/168, l='MpServer', x=264.69, y=68.00, z=-429.76], EntityItem['item.tile.rail_gun_turret'/169, l='MpServer', x=264.80, y=68.00, z=-429.70], EntityItem['item.tile.rail_gun_turret'/170, l='MpServer', x=260.20, y=67.00, z=-431.21], EntityItem['item.tile.turret_base_tier_five'/171, l='MpServer', x=260.61, y=79.54, z=-431.20], EntityItem['item.tile.rocket_turret'/172, l='MpServer', x=257.69, y=67.00, z=-431.72], EntityItem['item.tile.turret_base_tier_five'/173, l='MpServer', x=256.56, y=84.40, z=-431.14], EntityZombie['Zombie'/180, l='MpServer', x=202.21, y=35.00, z=-383.49], EntitySpider['Spider'/181, l='MpServer', x=199.50, y=71.00, z=-375.50], EntityPlayerSP['Keystone2670'/159, l='MpServer', x=256.48, y=86.29, z=-430.48], EntityItem['item.tile.cloth.silver'/183, l='MpServer', x=229.52, y=71.00, z=-441.42], EntityItem['item.item.muttonCooked'/184, l='MpServer', x=229.64, y=70.00, z=-443.26], EntitySheep['Sheep'/185, l='MpServer', x=208.51, y=67.00, z=-416.71], EntitySheep['Sheep'/441, l='MpServer', x=238.19, y=70.00, z=-484.50], EntitySkeleton['Skeleton'/186, l='MpServer', x=222.50, y=69.00, z=-430.50], EntitySheep['Sheep'/442, l='MpServer', x=231.81, y=69.00, z=-486.24], EntitySheep['Sheep'/443, l='MpServer', x=228.55, y=68.00, z=-480.27], EntitySheep['Sheep'/444, l='MpServer', x=223.04, y=69.00, z=-474.61], EntityZombie['Zombie'/189, l='MpServer', x=189.50, y=70.00, z=-388.50], EntitySheep['Sheep'/445, l='MpServer', x=213.77, y=69.00, z=-469.52], EntityCreeper['Creeper'/191, l='MpServer', x=245.50, y=22.00, z=-451.50], EntityCreeper['Creeper'/192, l='MpServer', x=245.50, y=22.00, z=-452.50], EntitySheep['Sheep'/193, l='MpServer', x=247.51, y=71.00, z=-460.26], EntityItem['item.tile.rail_gun_turret'/194, l='MpServer', x=255.51, y=72.00, z=-449.08], EntityItem['item.tile.turret_base_tier_five'/195, l='MpServer', x=255.50, y=70.00, z=-448.81], EntityItem['item.tile.turret_base_tier_five'/196, l='MpServer', x=250.14, y=67.00, z=-448.75], EntityItem['item.tile.rail_gun_turret'/197, l='MpServer', x=251.27, y=73.00, z=-450.65], EntityItem['item.tile.rail_gun_turret'/198, l='MpServer', x=255.07, y=72.00, z=-451.19], EntitySheep['Sheep'/455, l='MpServer', x=208.50, y=67.00, z=-439.73], EntityCreeper['Creeper'/199, l='MpServer', x=248.50, y=68.00, z=-452.31], EntitySheep['Sheep'/456, l='MpServer', x=216.39, y=68.00, z=-432.82], EntityItem['item.tile.turret_base_tier_five'/200, l='MpServer', x=254.68, y=82.54, z=-448.35], EntitySheep['Sheep'/457, l='MpServer', x=220.51, y=69.00, z=-446.80], EntitySkeleton['Skeleton'/202, l='MpServer', x=196.50, y=25.00, z=-390.50], EntitySkeleton['Skeleton'/458, l='MpServer', x=276.21, y=80.00, z=-503.50], EntityItem['item.item.sulphur'/206, l='MpServer', x=317.68, y=97.00, z=-475.49], EntitySheep['Sheep'/207, l='MpServer', x=278.19, y=65.43, z=-439.09], EntitySheep['Sheep'/208, l='MpServer', x=275.45, y=66.97, z=-439.46], EntityItem['item.tile.cloth.white'/209, l='MpServer', x=286.21, y=68.00, z=-447.43], EntityItem['item.item.muttonCooked'/210, l='MpServer', x=285.91, y=68.00, z=-447.27], EntityBat['Bat'/217, l='MpServer', x=257.25, y=59.10, z=-414.75], EntitySkeleton['Skeleton'/218, l='MpServer', x=258.49, y=59.00, z=-411.32], EntityBat['Bat'/219, l='MpServer', x=256.25, y=60.10, z=-412.75], EntitySheep['Sheep'/475, l='MpServer', x=249.65, y=70.00, z=-479.19], EntityItem['item.item.arrow'/220, l='MpServer', x=271.18, y=75.00, z=-411.93], EntitySheep['Sheep'/476, l='MpServer', x=252.50, y=71.00, z=-470.76], EntityZombie['Zombie'/477, l='MpServer', x=247.50, y=71.00, z=-468.50], EntitySkeleton['Skeleton'/221, l='MpServer', x=227.31, y=25.00, z=-369.25], EntityBat['Bat'/478, l='MpServer', x=231.75, y=24.10, z=-463.25], EntityZombie['Zombie'/222, l='MpServer', x=225.50, y=50.00, z=-373.50], EntityWitch['Witch'/479, l='MpServer', x=227.50, y=23.00, z=-458.50], EntityZombie['Zombie'/223, l='MpServer', x=224.50, y=50.00, z=-374.50], EntityCreeper['Creeper'/224, l='MpServer', x=222.50, y=15.00, z=-361.50], EntityCreeper['Creeper'/480, l='MpServer', x=228.78, y=22.00, z=-463.51], EntityCreeper['Creeper'/225, l='MpServer', x=211.50, y=15.00, z=-352.50], EntityBat['Bat'/481, l='MpServer', x=228.88, y=25.12, z=-457.76], EntityZombie['Zombie'/226, l='MpServer', x=223.74, y=68.00, z=-356.54], EntityItem['item.tile.turret_base_tier_five'/227, l='MpServer', x=262.38, y=72.00, z=-432.75], EntityItem['item.tile.rocket_turret'/228, l='MpServer', x=256.23, y=70.00, z=-437.17], EntityItem['item.tile.rocket_turret'/229, l='MpServer', x=263.93, y=72.00, z=-434.79], EntityItem['item.tile.rocket_turret'/230, l='MpServer', x=260.39, y=67.00, z=-440.43], EntityItem['item.tile.rocket_turret'/231, l='MpServer', x=258.06, y=67.00, z=-433.53], EntityItem['item.tile.rocket_turret'/232, l='MpServer', x=262.29, y=72.00, z=-437.10], EntityItem['item.tile.turret_base_tier_five'/233, l='MpServer', x=262.92, y=79.54, z=-435.20], EntityItem['item.tile.turret_base_tier_five'/234, l='MpServer', x=258.70, y=79.54, z=-432.45], EntityItem['item.tile.turret_base_tier_five'/235, l='MpServer', x=261.34, y=79.54, z=-438.16], EntityItem['item.tile.turret_base_tier_five'/236, l='MpServer', x=262.42, y=79.54, z=-436.59], PhysicsWrapperEntity['entity.valkyrienwarfare.PhysWrapper.name'/237, l='MpServer', x=260.30, y=82.69, z=-435.01], EntityItem['item.tile.turret_base_tier_five'/238, l='MpServer', x=265.87, y=84.61, z=-433.47], EntityItem['item.tile.rail_gun_turret'/239, l='MpServer', x=265.37, y=84.54, z=-433.59], EntityBat['Bat'/240, l='MpServer', x=251.70, y=62.07, z=-422.34], EntityZombie['Zombie'/241, l='MpServer', x=251.30, y=60.00, z=-420.10], EntityZombie['Zombie'/242, l='MpServer', x=252.04, y=60.00, z=-420.70], EntityCreeper['Creeper'/243, l='MpServer', x=253.54, y=59.00, z=-422.19], EntitySkeleton['Skeleton'/244, l='MpServer', x=255.52, y=59.00, z=-420.73], EntityItem['item.item.monsterPlacer'/245, l='MpServer', x=250.31, y=78.00, z=-425.87], EntityCreeper['Creeper'/506, l='MpServer', x=234.50, y=22.00, z=-469.50], EntityCreeper['Creeper'/507, l='MpServer', x=233.50, y=22.00, z=-466.50], EntitySheep['Sheep'/508, l='MpServer', x=224.08, y=69.00, z=-474.31], EntityZombie['Zombie'/254, l='MpServer', x=247.40, y=65.00, z=-408.20], EntityBat['Bat'/255, l='MpServer', x=252.73, y=64.08, z=-402.23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 238422384 bytes (227 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCHIJAAAA	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar) 
	UCHIJAAAA	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft-1.9.4.jar) 
	UCHIJAAAA	counter_guns{1.0.1} [Counter Guns] (CounterGuns-1.10.2-1.0.1.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJAAAA	cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAAAA	guideBook{1.6.1} [Guide Book] (Guide-Book-Mod-1.10.2.jar) 
	UCHIJAAAA	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	MoreFurnaces{1.8.1} [More Furnaces] (MoreFurnaces-1.10-1.8.1.jar) 
	UCHIJAAAA	omlib{1.10.2-3.0.0-47} [OMLib] (omlib-1.10.2-3.0.0-47.jar) 
	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-60} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-60.jar) 
	UCHIJAAAA	reinforcedTools{1.4.1} [ReinforcedTools] (Reinforced-Tools-1.10.2.jar) 
	UCHIJAAAA	uncraftingTable{1.6} [Uncrafting Table] (UncraftingTable-1.10.2.jar) 
	UCHIJAAAA	valkyrienwarfare{0.86d} [Valkyrien Warfare] (valkyrienwarfare-1.10.2-0.8.6d-47.jar) 
	UCHIJAAAA	valkyrienwarfarecombat{0.1} [Valkyrien Warfare Combat] (valkyrienwarfare-1.10.2-0.8.6d-47.jar) 
	UCHIJAAAA	valkyrienwarfarecontrol{0.3b} [Valkyrien Warfare Control] (valkyrienwarfare-1.10.2-0.8.6d-47.jar) 
	UCHIJAAAA	valkyrienwarfareworld{0.0a} [Valkyrien Warfare World] (valkyrienwarfare-1.10.2-0.8.6d-47.jar) 
	UCHIJAAAA	XaeroMinimap{1.12} [Xaero's Minimap] (Xaeros_Minimap_1.12_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
ValkyrienWarfareBase CoreMod (valkyrienwarfare-1.10.2-0.8.6d-47.jar)
  ValkyrienWarfareBase.CoreMod.ValkyrienWarfareTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GTX 980M/PCIe/SSE2'
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980M/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

**Comment by Keridos** [comment]
Already fixed, and that is not a compat problem, was affecting all tier 5 bases. curseforge review is pending, should be available any moment.
