### ISSUE TITLE
Turrets Stop shooting on latest update

### ISSUE THREAD

**Issue by mrgreaper** [OpenModularTurretsTeam/OpenModularTurrets#282]
as issue title, updated thursday to 1.10.2-3.0.0.64 and my turrets are hiding in thier cases, refusing to pop out and shoot bad guys

**Comment by Keridos** [comment]
Can't reproduce this, need more info.

**Comment by Keridos** [comment]
And just for testing, can you try this build please? https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/65/artifact/build/libs/openmodularturrets-1.10.2-3.0.0-65.jar
