### ISSUE TITLE
VW Compatability

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#284]
Ideas for additional compatability with VW:

- [x] Certain Turrets can destroy blocks. 
- [x] Ability to aim Turrets manually (currently just via OpenComputers)
- [ ] let certain turrets aim at ships automatically?
- [x] #310 ,#312, #374

**Comment by Sunspot0411** [comment]
Hi Keridos, the VW team is now back and they are working on the 1.12 version, so would mind just take a look into this issue again? Thanks!

**Comment by Keridos** [comment]
They wrote the compatability for the mod.

**Comment by Sunspot0411** [comment]
Hi @Keridos, it seems they are either busy or do not care this issue for the moment. Would you mined point me out the code related to turret targeting for both 1.10.2 and 1.12.2? Wanna see if I could do something with it after comparing the difference between these 2 versions. Thanks!

**Comment by Keridos** [comment]
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.12/src/main/java/omtteam/openmodularturrets/tileentity/turrets/TurretHead.java#L348-L472

and 

https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.12/src/main/java/omtteam/openmodularturrets/util/TurretHeadUtil.java#L101-L173

**Comment by Sunspot0411** [comment]
Thanks!
