### ISSUE TITLE
How could I use computer of computercraft to commend a turret?

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#286]
Hi there, would you mind giving us some instructions on how to use a computer on a turret? I know this probablly does not count as an issue but I'm not sure where I could ask about it.

**Comment by Keridos** [comment]
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/master/src/main/java/openmodularturrets/tileentity/turretbase/TurretBase.java#L1040-L1189
