### ISSUE TITLE
Game crashes when a turret fires

### ISSUE THREAD

**Issue by GaleBlitzPrime** [OpenModularTurretsTeam/OpenModularTurrets#287]
Hi there, here's the crash report that came up when a railgun turret fired upon a creeper and crashed the game

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.11.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 2/13/17 12:45 AM
XRay version: 48
Description: Ticking block entity

java.lang.NoSuchMethodError: omtteam.omlib.util.compat.MathTools.sqrt_double(D)F
	at omtteam.openmodularturrets.tileentity.turrets.TurretHead.func_73660_a(TurretHead.java:401)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at omtteam.openmodularturrets.tileentity.turrets.TurretHead.func_73660_a(TurretHead.java:401)

-- Block entity being ticked --
Details:
	Name: minecraft:rail_gun_turret // omtteam.openmodularturrets.tileentity.turrets.RailGunTurretTileEntity
	Block type: ID #1060 (tile.rail_gun_turret // omtteam.openmodularturrets.blocks.turretheads.BlockRailGunTurret)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-56,65,372), Chunk: (at 8,4,4 in -4,23; contains blocks -64,0,368 to -49,255,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1060 (tile.rail_gun_turret // omtteam.openmodularturrets.blocks.turretheads.BlockRailGunTurret)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: A Brave New World
	All players: 1 total; [EntityPlayerMP['j_yepyo'/702, l='A Brave New World', x=-59.50, y=66.11, z=382.44]]
	Chunk stats: ServerChunkCache: 359 Drop: 0
	Level seed: 7868729979312982666
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-16,64,224), Chunk: (at 0,4,0 in -1,14; contains blocks -16,0,224 to -1,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 255895 game time, 48700 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 31648 (now: false), thunder time: 144642 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 74645560 bytes (71 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: Minecraft 1.11.2 MCP 9.38 Powered by Forge 13.20.0.2228 Optifine OptiFine_1.11.2_HD_U_B5 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCHIJAAAA	ivtoolkit{1.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	rpghud{3.3} [RPG-Hud] ([1.11] RPG-HUD 3.3.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r100} [Actually Additions] (ActuallyAdditions-1.11.2-r100.jar) 
	UCHIJAAAA	jei{4.2.0.210} [Just Enough Items] (jei_1.11.2-4.2.0.210.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	thedragonlib{1.11.2-2.1.0} [TheDragonLib] (TheDragonLib-1.11.2.jar) 
	UCHIJAAAA	armorplus{1.11.2-9.5.7.8-beta} [ArmorPlus] (armorplus-1.11.2-9.5.7.8-beta.jar) 
	UCHIJAAAA	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.11.2.jar) 
	UCHIJAAAA	cavern{1.6.2} [Cavern] (Cavern_1.11-v1.6.2.jar) 
	UCHIJAAAA	cfm{4.1.1} [MrCrayfish's Furniture Mod] (cfm-4.1.1-mc1.11.2.jar) 
	UCHIJAAAA	cvmm{1.0} [MrCrayfish's Vending Machine Mod] (cvmm-1.0-mc1.11.2.jar) 
	UCHIJAAAA	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCHIJAAAA	torohealthmod{1.11.2-8} [ToroHealth Damage Indicators] (Damage-Indicators-1.11.2.jar) 
	UCHIJAAAA	durabilityshow{4.1.0} [Durability Show] (Durability Show-1.11.2-4.1.0.jar) 
	UCHIJAAAA	embers{0.107} [Embers] (embers-0.107.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (Extra Utilities Mod-1.11.2.jar) 
	UCHIJAAAA	zerocore{1.11.2-0.1.0.2} [Zero CORE] (ZeroCore-1.11.2.jar) 
	UCHIJAAAA	bigreactors{1.11.2-0.4.5.25} [Extreme Reactors] (ExtremeReactors-1.11.2.jar) 
	UCHIJAAAA	ezwastelands{1.11-1.2} [EzWastelands] (ezwastelands-1.11-1.2.jar) 
	UCHIJAAAA	giacomosfoundry{1.3.7} [Giacomo's Foundry] (GiacomosFoundry1.11-1.3.7.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (InventoryTweaks-1.62-dev-75.jar) 
	UCHIJAAAA	ironchest{1.11-7.0.17.799} [Iron Chest] (IronChest-1.11.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJAAAA	justenoughbuttons{1.11.2-1.4.1} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.1.jar) 
	UCHIJAAAA	lightningcraft{2.8.1} [LightningCraft] (lightningcraft-2.8.1-[1.11.2].jar) 
	UCHIJAAAA	lucky{7.4.0} [Lucky Block] (LuckyBlock_1-11_v7-4-0.zip) 
	UCHIJAAAA	minecolonies{1.11-0.6.2306} [MineColonies] (minecolonies-universal-1.11-0.6.2306.jar) 
	UCHIJAAAA	mysticalagriculture{1.3.9} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.9.jar) 
	UCHIJAAAA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJAAAA	omlib{1.11.2-3.0.0-55} [OMLib] (omlib-1.11.2-3.0.0-55.jar) 
	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-85} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-85.jar) 
	UCHIJAAAA	packingtape{1.11.0-0.6.1} [Packing Tape] (PackingTape-1.11.0-0.6.1.jar) 
	UCHIJAAAA	harvestcraft{1.11.2b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2b.jar) 
	UCHIJAAAA	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11.2.jar) 
	UCHIJAAAA	prefab{1.2.0.3} [Prefab] (prefab-1.2.0.3.jar) 
	UCHIJAAAA	randomutilities{4.1.0} [Random Utilities] (Random Utilities-1.11.2-4.1.0.jar) 
	UCHIJAAAA	reccomplex{1.2.6.1} [Recurrent Complex] (RecurrentComplex-1.11.2.jar) 
	UCHIJAAAA	refinedstorage{1.3.5} [Refined Storage] (RefinedStorage-1.11.2.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCHIJAAAA	roguelike{1.6.2} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.2.jar) 
	UCHIJAAAA	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJAAAA	simplegrinder{3.060.R1112} [Simple Grinder] (SimpleGrinder-1.11.2.jar) 
	UCHIJAAAA	lteleporters{1.11.2-2.0.2} [Simple Teleporters] (SimpleTeleporters-1.11.2-2.0.2.jar) 
	UCHIJAAAA	supplydrop{1.0.0} [Supply Drop] (Supply Drop-1.11.2.jar) 
	UCHIJAAAA	techexpansion{1.1} [Tech Expansion] (techexpansion-1.4.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.11.2-1.2.0.jar) 
	UCHIJAAAA	theoneprobe{1.4.2} [The One Probe] (theoneprobe-1.1x-1.4.2.jar) 
	UCHIJAAAA	toroquest{1.11.2-2} [ToroQuest] (toroquest-1.11.2-2.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.11-1.1.1a.jar) 
	UCHIJAAAA	tumat{1.7.0} [TUMAT] (TUMAT-1.7.0.jar) 
	UCHIJAAAA	usefulrecipes{1.11-3.0.1} [UsefulRecipes] (usefulrecipes-3.0.1.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	wasteland_meteors{1.11-0.1} [Wasteland Meteors] (wasteland_meteors-1.11-0.1.jar) 
	UCHIJAAAA	waystones{3.0.5} [Waystones] (Waystones-1.11.jar) 
	UCHIJAAAA	wearablebackpacks{2.1.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.1.0.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.11.jar)
  
FMLPlugin (InventoryTweaks-1.62-dev-75.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['j_yepyo'/702, l='A Brave New World', x=-59.50, y=66.11, z=382.44]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B5
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by Keridos** [comment]
Download the latest omlib build.
