### ISSUE TITLE
Turret bases cannot be charged

### ISSUE THREAD

**Issue by vrogojin** [OpenModularTurretsTeam/OpenModularTurrets#288]
It seems I am unable to charge the turret base neither with Redstone Reactor addon, nor with Base Power Expander. Turrets will not work! Either I am doing something very wrong, or it is a bug. Is there any tutorial for this mod?

**Comment by Keridos** [comment]
Base Power expanders do not charge bases, they simply expand their storage. Found a bug that prevented redstone dust being put into the base, will be fixed next version. You should not really need any tutorial, almost all of the items have a tooltip that explains how they are being used.

**Comment by Keridos** [comment]
@vrogojin try out the newest build on curseforge, I added a lot of info to tooltips on several GUIs and items that should explain the basics of the game for newbies far better than it was before.

**Comment by vrogojin** [comment]
Thanks @Keridos. I will try it tonight. I am building an FPS game and need turrets for that. So far, I  managed to edit directly NBT tags for turret's base and set its charge level manually. Otherwise, it works perfectly. Very nice mod. Thanks!
