### ISSUE TITLE
External Mod Mobs not being targeted.

### ISSUE THREAD

**Issue by Verniel** [OpenModularTurretsTeam/OpenModularTurrets#29]
Feedback so far includes mobs from:

-Infernal Mobs Mod
-Invasion Mod
-Lycanites' mobs

**Comment by Teibidh** [comment]
Resurrection. Mobs from "Vampirism" mod are not being targeted.

**Comment by hagfelsh** [comment]
Ressurection here too: Grimoire of Gaia and Primitive Mobs aren't targeted.
