### ISSUE TITLE
[1.10.2-3.0.0-96] crashes dedicated server Forge 1.11.2 build 2231 on startup

### ISSUE THREAD

**Issue by kreezxil** [OpenModularTurretsTeam/OpenModularTurrets#290]
crash report:
https://gist.github.com/f65f9ef7872c41e3b1ddcdffa086cb50

fml server latest:
https://gist.github.com/bc4719991d23e1b13606e7e290d4b087

**Comment by DeadSix27** [comment]
Same issue on **1.10.2**, seems like sided-classes mistake? (client classes on server)

1.10 stacktrace: http://pastebin.com/F2122kgg

**Comment by Keridos** [comment]
Please try the latest releases for OMT and OMlib on curseforge please.
