### ISSUE TITLE
Limiting turret firing angles

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#291]
Could you make new settings that allow us to limit targeting area of a turret within certain angle range? Sometimes you don't want a turret shoot at any direction.

**Comment by Keridos** [comment]
This is a nice feature for the addon for OMT, gonna note that to be implemented there.

**Comment by Keridos** [comment]
https://github.com/OpenModularTurretsTeam/OMTControl/issues/2
