### ISSUE TITLE
It keeps crashing and I don't know why

### ISSUE THREAD

**Issue by Twaee3** [OpenModularTurretsTeam/OpenModularTurrets#292]
I don't have that many mods and it seems like OpenModularTurrets is the only one crashing. It crashes on start up.
http://pastebin.com/9SpiSmjS

EDIT: I have removed all other mods except for Open Turrets and it's library and it still crashes.
EDIT 2: It seems the place I downloaded them from (9minecraft.net) was outdated. It works now

**Comment by Keridos** [comment]
Do not try downloading mods from sources except their Minecraft Forum Thread or curseforge or Technic Launcher, Sites like 9minecraft.com always advertise mods being available for all versions to earn money from ads they place. If you are lucky you only get an outdated version but if you have bad luck you could get a virus from there.
