### ISSUE TITLE
repeated crashes

### ISSUE THREAD

**Issue by TheronEpic** [OpenModularTurretsTeam/OpenModularTurrets#293]
i recently installed this mod, and everything was working fine. i was testing it on my modded survival world and was using the tier 1 turret, but as soon as the turret activated (recieved power) the game crashed. i need to know how to fix this!
i was using openmodularturrets-1.10.2-3.0.0-98 on minecraft 1.11 forge.
if i find a way to fix it myself i will let you know.
it appears to only crash when the disposable item turret turns on.
[crash-2017-03-05_10.18.18-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/819596/crash-2017-03-05_10.18.18-server.txt)
here is the crash report for when it happened
ps omlib version omlib-1.11.2-3.0.0-60

**Comment by Keridos** [comment]
Paste the crash report somewhere please, we cannot help you with this at all with your report like this.

**Comment by TheronEpic** [comment]
it appears to only crash when the disposable item turret turns on.

**Comment by TheronEpic** [comment]
[crash-2017-03-05_10.18.18-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/819596/crash-2017-03-05_10.18.18-server.txt)
here is the crash report for when it happened
