### ISSUE TITLE
[1.7.10] Incompatible option dependencies

### ISSUE THREAD

**Issue by spannerman79** [OpenModularTurretsTeam/OpenModularTurrets#295]
On curseforge, listed on https://minecraft.curseforge.com/projects/openmodularturrets/files/2390538 the Optional Library's listed is [Open Modular Passive Defense](https://minecraft.curseforge.com/projects/open-modular-passive-defense) although the lowest mincraft version for that mod is 1.10 - not 1.7.10

**Comment by Keridos** [comment]
Yeah fixed that, that opnly applies to 1.10.2 and higher MC versions.

**Comment by spannerman79** [comment]
Opps looks like it happened again @Keridos   https://minecraft.curseforge.com/projects/openmodularturrets/files/2426169
