### ISSUE TITLE
Crash on Startup 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OpenModularTurretsTeam/OpenModularTurrets#296]
https://gist.github.com/P3rf3ctXZer0/5e87177df18560759134bc708c373f1b

**Comment by Keridos** [comment]
We got this crash reported about a dozen times and although I have described how to fix it in a huge font on the OMT curseforge page, no one seems to listen to that. Download the newest 1.10.2 builds please, the 1.11.2 builds are backwards compatible.
