### ISSUE TITLE
No items showing in creative menu

### ISSUE THREAD

**Issue by heyzeusmantoya** [OpenModularTurretsTeam/OpenModularTurrets#297]
Using this mod on an adventure map and when trying to place the items in creative mode the tab is active but no items showing inside the tab that are usable. Not sure if a bug or intended but wanted to check and see. Attached screenshots as well.
![2017-03-23_11 04 09](https://cloud.githubusercontent.com/assets/24821889/24254156/8a0b6ac2-0fb8-11e7-9ea9-342a4f8e1cad.png)

**Comment by dat3ngy** [comment]
I had the same problem, hopefully this is fixed soon.

**Comment by Keridos** [comment]
Will be fixed in the next update, was a bug in the code.

**Comment by dat3ngy** [comment]
@Keridos Alright, thanks for checking this out, really appreciated.
