### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by carstorm** [OpenModularTurretsTeam/OpenModularTurrets#299]
Got told to post this here, may be an issue with foamfix instead (unsure TBH) or may be an inseparability issue.

Crash Report on (SP world load): https://pastebin.com/vtgpi0aY

**Comment by Keridos** [comment]
I am fairly certain that this is caused by some mod replacing the turret with another blockstate but not removing the tile entity, I could add a check for that but that seems like an external bug tbh.

**Comment by Keridos** [comment]
Can you test with this please (and the latest omlib version from curseforge): https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/116/

**Comment by carstorm** [comment]
It works now.
