### ISSUE TITLE
Server Crash from Blue Gem helmet registering as null (v 1.5.7 for 1.7.10)

### ISSUE THREAD

**Issue by Dulciphi** [OpenModularTurretsTeam/OpenModularTurrets#300]
Description: Exception in server tick loop

java.lang.NullPointerException: Can't add null-object to the registry, name ExtraPlanets:blueGemHelmet.
	at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:363)

[crash report](https://paste.ee/p/xKvNP)

**Comment by VoltyFarstar** [comment]
Not sure what in the attached stacktrace made you think its OMT crashing the server. All I can see are references to ExtraPlanets.

**Comment by Dulciphi** [comment]
Oh good lord. Well I'm an idiot. Too many tabs open, sorry. I had your repo open to look into the feasibility of a mountable, player-powered (or NPC-powered) turret. 

To make it worse, I actually noticed I had the wrong repo, copied the text and pasted it to ExtraPlanets' repo. ...then got interrupted. I've come back and finished up the issue in your tab. Sorry :s
