### ISSUE TITLE
Crash when trying to Camo a Turret

### ISSUE THREAD

**Issue by CovertJaguar** [OpenModularTurretsTeam/OpenModularTurrets#301]
https://hastebin.com/ziqikosaci.pas

**Comment by Keridos** [comment]
Which block was that?

**Comment by CovertJaguar** [comment]
I asked, but no one is sure who was messing with it at the time or what was being used, sorry.

**Comment by VoltyFarstar** [comment]
Might be related to #306

**Comment by Keridos** [comment]
Yeah, now we just have to figure out what that means, probably color multiplier is called by the particle spawn system?

**Comment by Keridos** [comment]
Try this please @CovertJaguar https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/104/

**Comment by Keridos** [comment]
https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/106/ maybe this does the job

**Comment by Keridos** [comment]
I will close this issue now @CovertJaguar if it persist, feel free to post here and I will reopen it.

**Comment by CovertJaguar** [comment]
We only saw it that once, and not many people have turrets yet now that we flipped to survival. I'll let you know if it happens again.
