### ISSUE TITLE
Disabling a turret causes an NPE.

### ISSUE THREAD

**Issue by Axiom1999** [OpenModularTurretsTeam/OpenModularTurrets#303]
You're still referencing disabled turrets and is causing an NPE.

Here: I have the teleportation turret disabled.

https://pastebin.com/cWwjHfQa

**Comment by TheCodedOne** [comment]
simple fix as far as i can see just need to check the config before doing the TESR items https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.10.2/src/main/java/omtteam/openmodularturrets/init/ModTESRItems.java#L42-L43
