### ISSUE TITLE
"Add Trusted Player" textbox closes when inventory key is pressed

### ISSUE THREAD

**Issue by Lordmau5** [OpenModularTurretsTeam/OpenModularTurrets#304]
Newest version, right out of the oven (1.10.2).

Whenever I type some username with the letter "E", or *just* the letter "E", which is the default inventory key, this GUI closes itself:
![image](https://cloud.githubusercontent.com/assets/1345036/25071414/8456516c-22b6-11e7-9f82-2cd2d4be0c38.png)

I've rebound my inventory key and the issue persists.

Probably an oversight in the code when the textbox is focused, shouldn't be too difficult to fix :P

I've checked through the code though, this part in particular:
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.10.2/src/main/java/omtteam/openmodularturrets/client/gui/ConfigureGui.java#L144-L156

In which you *are* indeed checking if the textbox is focused. So it should work, but apparently it doesn't? :/

**Comment by Keridos** [comment]
See #302

**Comment by Lordmau5** [comment]
Ah gotcha - the issue was marked as closed and was present in the newest version of the mod, so yea :D
