### ISSUE TITLE
OMT will not target Gaia boss from Botania 

### ISSUE THREAD

**Issue by frenzye** [OpenModularTurretsTeam/OpenModularTurrets#307]

**Comment by Keridos** [comment]
This is intended as Vazkii will probably disable it within Botania even if we do support it.


On 19 April 2017 06:15:40 GMT+02:00, frenzye <notifications@github.com> wrote:
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/307

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by VoltyFarstar** [comment]
Agreed.
