### ISSUE TITLE
Turret Bases not accepting power from EnderIO conduits

### ISSUE THREAD

**Issue by Liiw** [OpenModularTurretsTeam/OpenModularTurrets#308]
Hello!

I am using OMT on a 1.10.2 SpongeForge server. I love the mod, it is an integral part of my gameplay, however there seems to be an issue with EnderIO power conduits. The turret bases do not accept power from EIO conduits. Power transfer methods from other mods (IE, Mekanism etc) work fine and it even works when I put a "buffer" cable from another mod between the EIO conduit and OMT turret base. 

I also noticed that when placing/breaking a powered conduit next to the base, the base's RF meter would increase by 12000 RF each time. Because of this, an EnderIO contributor suggested that perhaps this bug is on OMT's side. Could you please look into this matter?

**Comment by Keridos** [comment]
We will look into this.

**Comment by Liiw** [comment]
Thank you for your reply!

On both the client and server there are these versions installed:
EnderIO-1.10.2-3.1.180
EnderCore-1.10.2-0.4.1.65-beta
openmodularturrets-1.10.2-3.0.0-102
forge-1.10.2-12.18.3.2281

Also only on server there is spongeforge installed:
spongeforge-1.10.2-2281-5.2.0-BETA-2274

I am also including a logfile link which I attached to the issue I posted on the EnderIO issues section:

https://gist.github.com/Liiw/502ce4ea79da3c1815b90b60c325aaf9

**Comment by Keridos** [comment]
Will test this with the more up to date enderio version. Interesting though is that in my dev env with an older enderIO version it works fine.

**Comment by Bastiondar** [comment]
I'm also having this issue. I'm using the same versions of the mod that Liiw is using. No spongeforge though.  I've been using the tier 2 and tier 1 bases. What's weird is that when I break the conduit connection, the turret suddenly receives a small charge. Or when I connect a capacitor directly to the base, it will receive a charge for about 3 seconds, drawing 1k then dropping down to 0.

**Comment by Keridos** [comment]
Try this please: https://jenkins.ironhide.de/job/OMLib%201.10.2/64/

**Comment by Liiw** [comment]
That seems to have fixed it. I tested on a singleplayer world- placed down a turret base, a capacitor bank and an energy conduit between the two. Meter started filling up nicely. Excellent work!

I will close this issue until I have had the chance to also test it on the server, although I trust there to be no issues. Thank you!

**Comment by Keridos** [comment]
@Liiw how is it looking in SMP, really would like to push this to curseforge 👨

**Comment by Liiw** [comment]
Apologies for the delay, I will report with the results shortly.

**Comment by Liiw** [comment]
I can confirm that while having **omlib-1.10.2-3.0.0-64** installed on both the server and client, the turret bases accept power from EIO conduits. 

Updated server, logged in and did a test setup (base-conduit-capacitor bank). Power meter was filling. Thank you very much for this!
