### ISSUE TITLE
1.10.2 Railgun does not create projectiles when VW is installed

### ISSUE THREAD

**Issue by rokiyo** [OpenModularTurretsTeam/OpenModularTurrets#311]
With only the following installed:
forge1.10.2-12.18.3.2281
omlib-1.10.2-3.0.0-61
ompd-1.10.2-3.0.0.21
openmodularturrets-1.10.2-3.0.0-106
ValkyrienWarfareRevamped-1.10.2-0.8.7-127

The railgun itself aims at targets correctly, consumes ammo and produces sounds, but nothing is damaged when the turret fires. I even set railguns to destroy terrain and completely encased the turret in dirt walls. While firing at zombies none of the dirt was destroyed and nothing took any damage.

Removing VW and reloading the save causes those same turrets to immediately begin firing correctly, the zombies started taking damage and holes started appearing in the dirt.

EDIT: Note that these are turrets placed on the GROUND, using only vanilla and OMT blocks. This was just testing what happens when VW is simply present in the modpack.

**Comment by Keridos** [comment]
@BigBastard Probably something going crazy in the code of yours :rofl:
