### ISSUE TITLE
Apply upgrade with shift-clicking cause upgrade item destroyed

### ISSUE THREAD

**Issue by ZZaphodd** [OpenModularTurretsTeam/OpenModularTurrets#315]
0. Open turret base GUI
1. Put one upgrade on turret (Turret base tier 5, "Upgrade - efficiency")
2. Try to put 4 upgrade on turret by shift click on 4 stacked "Upgrade - efficiency",
3. I expected only 3 upgrades applied on turret base,
the turret base have 4 upgrades and only one remaining upgrade on my inventory which shift+clicked stack.
4. But the turret base have 3 upgrades and there's no more upgrade on shift+clicked stack.(2 upgrades gone)

version : Open modular Turrets 1.10.2-3.0.0-100
modpack : FTB Invasion 1.0.4

**Comment by Keridos** [comment]
Thanks, managed to reproduce it, fix will be out in next OMT release.
