### ISSUE TITLE
Computercraft/OpenComputers Integration?

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#32]
(Created in regard to previous conversation regarding this)

This will be quite the interesting endeavor. Thoughts?

- [x] OC Integration
- [x] CC Integration

**Comment by Keridos** [comment]
What methods should we implement?
And I additionally request OpenComputers Support.

**Comment by Poenjabiesous** [comment]
This is open for discussion on how we approach this. Do we designate targets, or do we let the base ask the computer if it should attack or not? Will we be able to setRange(), setFireRate(), etc? The idea is open for discussion. 

OpenComputers also sounds good.

**Comment by nightstalker6669** [comment]
getTarget(), getWhitelist() (for a table of players that are whitelisted on this turret) maybe a toggleTurret() to be able to switch the turret off and on? for getTarget() have it a table that gives x, y, z, distance that is relative to the turret itself. turretStatus() to show what the turret is doing (IE, firing, waiting, out of ammo etc etc) just some ideas i think would be neat to implement. and obviously for OpenComputers, and i guess computercraft :P

**Comment by Keridos** [comment]
Per Turret Alarm would be nice to have, yeah. The functions sound fine.
