### ISSUE TITLE
1.10.2-3.0.0-127 crashing server when player logs on

### ISSUE THREAD

**Issue by kreezxil** [OpenModularTurretsTeam/OpenModularTurrets#322]
These are all the same but they might differ slightly to help you figure it out. However, it looks like you let an @sided slip out of place because it appears to be looking for a client side class. But why wait until the player logs on?

https://gist.github.com/8a16feb5f1ee197602e6caf45f8e8c54
https://gist.github.com/4f64b094a6e22f70741950c28131a714
https://gist.github.com/ce91d890c1ae1a2248fedf5b09553531
https://gist.github.com/aa252999fc9fb68f6e952c08679190d5
https://gist.github.com/bb3d09d509f5131271a737f502e19c8d
https://gist.github.com/3abd1aa8985debd10186704325770b86
https://gist.github.com/30f43b8f76ecc97d2a6973ebf6326c1a
https://gist.github.com/a4b0260a47df097691896aee0e9c65e7
https://gist.github.com/78bc3ea7922e911c36fd0280c3c6c772
https://gist.github.com/eb9380d872cd725c70c0523dc6aeb4b5
https://gist.github.com/6b1dc8481605bf240198a01e4e1da32d

**Comment by Keridos** [comment]
This is not a sided issue at least not in the first crash. The code is neither abstract and is implemented. I literally have no idea why this is happening at all. Have you tried updating OpenComputers? Seems like the bug is caused by them. @fnuecke You have any idea what does this?

**Comment by Keridos** [comment]
https://jenkins.ironhide.de/job/OMLib%201.11.2/79/artifact/build/libs/omlib-1.11.2-3.0.0-79.jar
https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/135/artifact/build/libs/openmodularturrets-1.10.2-3.0.0-135.jar
