### ISSUE TITLE
Rework OC integration

### ISSUE THREAD

**Issue by kreezxil** [OpenModularTurretsTeam/OpenModularTurrets#323]
Now a player doesn't even need to log on for the server to crash.

Notes:
     something to do with a server tick loop
     reference #322 

crash report:
https://gist.github.com/c278785ce28ccbe0b4d6a63faf51354c

fml server latest:
https://gist.github.com/1a9e55357b3fc093fcb02d924f22ea2d

**Comment by Keridos** [comment]
WTF, @fnuecke, i might really need your help here.

**Comment by Keridos** [comment]
Can you try this omlib build please: https://jenkins.ironhide.de/job/OMLib%201.11.2/80/

**Comment by kreezxil** [comment]
omlib jenkins build 80 crashes dedicated server Forge 1.11.2 build 2298

Notes:
     no change

crash report:
https://gist.github.com/d019995322247a0ba4055636259806c0

fml server latest:
https://gist.github.com/4f6e5ee91d2891c57bf7dd172d996e40

**Comment by kreezxil** [comment]
I'm sorry, I mispoke just a tad bit. There is one change. The server wasn't crashing on its own, but only when the player logs in, that's what jenkins build 80 fixed. IE, it is officially reverted back to #322

**Comment by fnuecke** [comment]
> 1.10.2-3.0.0-135
> Forge 1.11.2

Is that allright?

Aside from that, in 1.11 OC's class transformer is [known to be a derp right now](https://github.com/MightyPirates/OpenComputers/issues/2371), I'd actually recommend switching to the capability based approach -- i.e. provide and `Environment` implementation as a capability for your tile entities. Just slightly more annoying because you'll need to init/dispose it in your TE's onLoad/invalidate/onChunkUnload and save/load it manually...

**Comment by Keridos** [comment]
Yeah the 1.10.2 code works on both 1.11.2 and 1.10.2 we are using compat layer code in OMLib to make the necessary transistions. Might have been an issue with modID mismatches, apparently opencomputers is not avaialable? Tried setting it to opencomputersapi|core but apparently that just crashes it at a different time.

**Comment by Keridos** [comment]
This should at least fix the crashing, but should disable OC support on 1.11.2: https://jenkins.ironhide.de/job/OMLib%201.11.2/81/

**Comment by phit** [comment]
could that build please be pushed to Curse for 1.11.2 until a solution was found

**Comment by phit** [comment]
[crash-2017-05-23_15.14.12-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1023475/crash-2017-05-23_15.14.12-server.txt)
latest version which is supposed to disable the OC integration is still crashing the server

**Comment by Keridos** [comment]
why on earth is that happening.

**Comment by Keridos** [comment]
Disabled OC integration in the v3.0.0-152 for now until I make the capability based approach.

**Comment by Keridos** [comment]
Thank you @Vexatos
