### ISSUE TITLE
Turret Doesn't Shot The Legs

### ISSUE THREAD

**Issue by kenijey** [OpenModularTurretsTeam/OpenModularTurrets#330]
well it's a problem in my server. turrets shots players only if it see the head, not legs. what i mean:
![2017-05-23_14 08 16](https://cloud.githubusercontent.com/assets/24831406/26351696/5e42cbae-3fc1-11e7-9bff-c312cd2222c3.png)
can this be fixed? it would be lovely. thanks.

**Comment by Keridos** [comment]
That is something within the target acquisition, we chat the line of sight against the eyes of the creature, if they are blocked by something, the turret cannot shoot. Design your base with that in mind :)

**Comment by kenijey** [comment]
so turrets can't never shot leggs ? :((

**Comment by Keridos** [comment]
It is way way harder on the server performance probably if we tried to change that, so yeah, that might never be the case in the near future.

**Comment by kenijey** [comment]
But players are coming by building blocks step by step and they are getting able to break the turret finally. How can i solve this problem? :(

**Comment by Keridos** [comment]
Make another turret that shoots at them from an angle.

**Comment by Keridos** [comment]
Or wait until we add some more stuff to OMPD that should fix that :)

**Comment by kenijey** [comment]
ok i'm waiting :D

**Comment by Forecaster** [comment]
Put the turrets out of reach... like above them...

**Comment by kenijey** [comment]
hope we see a solution for this :D thanks.
