### ISSUE TITLE
Initiation Launch Crash

### ISSUE THREAD

**Issue by Okimo** [OpenModularTurretsTeam/OpenModularTurrets#332]
openmodularturrets-1.10.2-3.0.0-150.jar
crash log: https://pastebin.com/TDLPLWhT

**Comment by rokiyo** [comment]
Could you please update to the latest version of OMLib and try again?

**Comment by Okimo** [comment]
Works fine Thanks 👍

**Comment by Keridos** [comment]
Please always use the newest omlib. No idea why this crashes, but I always set the required omlib version to the one that is not crashes with.
