### ISSUE TITLE
openmodularturrets-1.10.2-3.0.0-153 cant add more than one trusted player

### ISSUE THREAD

**Issue by sintaxcz** [OpenModularTurretsTeam/OpenModularTurrets#334]
No one can add more than 1 trusted player

**Comment by Keridos** [comment]
Gonna look into that

**Comment by Keridos** [comment]
Can you please type "/omdebug on" in the chat and then try again and tell me what it writes?

**Comment by sintaxcz** [comment]
With /omdebug on - after first trusted player add = Sucessfully added Name - second trusted player nothing happens and no message in chat or in console

**Comment by Keridos** [comment]
Cannot see any reason why this should stop working in the code, really need some testing with more than 2 accounts.

**Comment by sintaxcz** [comment]
With omlib 96 seems working multiple player sucessfuly added
