### ISSUE TITLE
openmodularturrets-1.10.2-3.0.0-156 missing mods it depends on

### ISSUE THREAD

**Issue by sintaxcz** [OpenModularTurretsTeam/OpenModularTurrets#335]
Include following mods and no mod name nothing / i have omlib-1.10.2.-3.0.0.-96 cant start this 156 version 153 vesion is ok

**Comment by sintaxcz** [comment]
158 version with omlib 100 same issue

**Comment by MokahTGS** [comment]
Confirmed.  OMT158 and OBLib100 are incompatible.

**Comment by Keridos** [comment]
See v101 of omlib :p
