### ISSUE TITLE
disposable ammo config

### ISSUE THREAD

**Issue by atari-lord** [OpenModularTurretsTeam/OpenModularTurrets#336]
I'm having trouble adding items to the whitelist provided in the config(aka disposableAmmoList). I wanted to add things like granite, diorite, andesite because they are worthless outside of decoration and I'm beginning to get a stockpile. Also things like compressed cobblestone/dirt because I heard they'll deal more damage, and also they are in abundance. I tried adding them per the instructions in the config file(modid:itemname), but when I get in game I can't put the items into the turret inventory. I started with compressed dirt and figured I was getting the mod id for extra utilities 2 wrong, but granite is minecraft and that still won't work. Any suggestions?

**Comment by Keridos** [comment]
Fairly sure that itemname might not be what you expect it to be. Try pressing F3 + H ingame and then hover over the items. You should see something like minecraft:stone then. If my memory serves me correct then diorite, granite are not called like that ingame, they are metatypes of stone. So you should try minecraft:stone simply, it should automatically add all variants of stone.

**Comment by atari-lord** [comment]
Ok, f3+h didn't help, but control+f3 did the trick. And it looks like I was putting in the correct mod and item name, in the correct format as well. What's strange is that minecraft:stone was already in the whitelist, but for some reason granite, andesite, and diorite still don't work.

**Comment by Keridos** [comment]
Gonna check that out.

**Comment by Keridos** [comment]
Found a bug in it, will be fixed next release, for now you need to add 2 items at once to make it work :-P
