### ISSUE TITLE
Throwable grenades not working/causes crash when used from off-hand

### ISSUE THREAD

**Issue by sharkck** [OpenModularTurretsTeam/OpenModularTurrets#340]
[crash-2017-06-09_19.33.13-client.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1065445/crash-2017-06-09_19.33.13-client.txt)

I tried to throw the grenade... it did nothing.  I said... well, let me try it in the offhand... I put it there, clicked, game froze and crashed with the above crash report.

**Comment by Keridos** [comment]
will fix the crash, they are not implemented.
