### ISSUE TITLE
Tier 4 Barrel Recipe Doesn't Work 1.7.10

### ISSUE THREAD

**Issue by MadderDad** [OpenModularTurretsTeam/OpenModularTurrets#341]
Using OpenModularTurrets-1.7.10-2.2.11-238, three diamonds across top, three diamonds on bottom, and the Tier 3 barrel in the mid/mid slot does not produce the Tier 4 barrel.

**Comment by Keridos** [comment]
Its not three diamonds at the bottom, its quartz....
