### ISSUE TITLE
[1.11.2 - version 1.10.2-3.0.0-158] Potato/Disposable item problems

### ISSUE THREAD

**Issue by VallenFrostweaver** [OpenModularTurretsTeam/OpenModularTurrets#342]
I am using a Tier 1 turret base in these examples below.

1st - Using potatoes in a disposable item turret allows it to fire them by default (no config changes) and it does 1 heart of damage. The Potato cannon turret does 1 heart of damage as well even though the turret states 1.5 hearts. Using a potato with a disposable item turret it has less range/accuracy than the potato cannon turret still so there is a disadvantage there. This isn't the main problem though as that may be as intended and I'm fine with that but thought it was worth a mention just in case.

2nd - When potatoes/disposable items (like cobble/planks, etc.) are used they will stay in the world and cannot be picked up. This may result in a lot of floating items all over that cannot be picked up. I can burn them, move them with water/blocks, etc. but cannot pick them up and they stay until the despawn limit otherwise. I don't think this one was as in intended.

**Comment by Keridos** [comment]
o.O @VoltyFarstar any idea on this?

**Comment by wjrogers** [comment]
I ran into the 2nd problem when I just fired up a fresh 1.11.2 profile to try out this mod. The bugged ItemStacks stay in the world over a save/reload, too.

**Comment by Keridos** [comment]
Should be fixed in latest releases.
