### ISSUE TITLE
Support for Mekanism's security settings

### ISSUE THREAD

**Issue by Avamander** [OpenModularTurretsTeam/OpenModularTurrets#344]
Would it be possible to add a custom upgrade/add-on to make turret respect (and replace) it's internal trusted list with Mekanism's?

**Comment by Keridos** [comment]
How is Mekanism doing that?
Is that a block or server commands?

**Comment by Avamander** [comment]
It's not one specific block neither am I aware of specific server commands, but it's basically a toggle added to the UI of every custom block mekanism has, it also has a control center and items that carry security settings (to be easily copied). You'll get a much nicer view how it works when you download it yourself and maybe watch this video I quickly found (https://www.youtube.com/watch?v=sc7AIBdeAkw).
