### ISSUE TITLE
Turret Base Disguise complicated metadata block rendering tessalation crash

### ISSUE THREAD

**Issue by CBSkarmory** [OpenModularTurretsTeam/OpenModularTurrets#348]
not a duplicate of ignoring metadata issue from 2015

When attempting to disguise a turret base as a block with more complicated metadata like a (Thermal Expansion) Cache, the game crashes.

Crash log: https://pastebin.com/tudaS18L

Repro steps: place turret base. Right click with Cache (empty).

Warning: this makes the world crash upon loading. Use mcedit to delete the offending block if you want the world to be playable again.

**Comment by Keridos** [comment]
That probably is not a bug in our mod but in the rendering system of said other mod.

**Comment by Avamander** [comment]
Similar to this one, DynMap doesn't understand disguised OMT's turret blocks and uses a black texture.

**Comment by Keridos** [comment]
I do not know how Dynmap does that. We simply copy the baked model from the camo block to use and use it to render it. So if the block has a default baked model, it should work fine ingame. However DynMap may try to render them some other way. Maybe a dynmap dev could pop up here and we could discuss how to fix that.
