### ISSUE TITLE
-Y config on turret base resets when chunks unloads

### ISSUE THREAD

**Issue by a-ion314** [OpenModularTurretsTeam/OpenModularTurrets#350]
As the title explains i found a problem where if you place a turret base and set the '-Y' coordinate option to something non-default, then leaving that area so that chunk unloads and coming back to it will have the -Y option reset back to its default value.

**Comment by Keridos** [comment]
Which version? Which Forge. Also pretty sure that bug was fixed quite a while ago. And latest versions do not have +y and -y anymore.
