### ISSUE TITLE
Crashing when loading the mod

### ISSUE THREAD

**Issue by LawsOfScience** [OpenModularTurretsTeam/OpenModularTurrets#351]
I just tried running this mod and well, crashed. I tried seeing if Forge was outdated but it still caught the exception. Here's the report.
(edit) Forgot to say I have the latest version of the required mod OMlib

[crash-2017-07-03_09.29.35-client.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1119664/crash-2017-07-03_09.29.35-client.txt)

**Comment by Keridos** [comment]
Your omt version is horribly outdated....
