### ISSUE TITLE
[1.10.2] Mekanism and Galacticraft cables refuse to connect

### ISSUE THREAD

**Issue by themechman** [OpenModularTurretsTeam/OpenModularTurrets#352]
I have mekanism, TE/TF and galacticraft installed. Unfortunately it seems that the only power cable I can connect is from TE/TF.

![2017-07-06_20 30 22](https://user-images.githubusercontent.com/2990361/27938126-fd6b0724-6289-11e7-9acb-1872a5a2a8a7.png)
Mekanism-1.10.2-9.2.2.301
CoFHCore-1.10.2-4.1.9.13-universal
ThermalDynamics-1.10.2-2.0.9.12-universal
ThermalExpansion-1.10.2-5.1.8.16-universal
ThermalFoundation-1.10.2-2.1.4.8-universal

**Comment by Keridos** [comment]
It is not clear which power system the other cables use. But we support RF/EU/Tesla/FE. And internal testing for those went fine.
