### ISSUE TITLE
[1.10.2] Floating rail turret

### ISSUE THREAD

**Issue by elijahlorden** [OpenModularTurretsTeam/OpenModularTurrets#353]
Rail Gun Turrets appear to float above the base when placed.  Screenshot attached.
![railturret](https://user-images.githubusercontent.com/13923468/28056132-bff021d2-65e9-11e7-97d8-87e48edf32a9.png)

**Comment by elijahlorden** [comment]
I realize WAILA says that is a T1 base, but I assure you it is a T5 base.

**Comment by Keridos** [comment]
That is intented.
