### ISSUE TITLE
[1.10.2] Unable to access turret in OpenComputers

### ISSUE THREAD

**Issue by elijahlorden** [OpenModularTurretsTeam/OpenModularTurrets#354]
I am attempting to write an OC control program for OpenModularTurrets, but it does not appear that OMT OC support is currently working.  After installing the serial port upgrade and placing an adapter next to the turret base, the Analyzer does not indicate that the base has a OC driver associated with it.

**Comment by Keridos** [comment]
Yeah we temporarily disabled it, but I think we have activated it again some time ago, let me check.

**Comment by Keridos** [comment]
See #323
