### ISSUE TITLE
[1.10.2] turret_base component not available

### ISSUE THREAD

**Issue by elijahlorden** [OpenModularTurretsTeam/OpenModularTurrets#361]
The turret_base component is now attaching to the Adapter successfully, but the component is still not available from the component list.  I am using the latest versions of OMT, OMLib, and OC for 1.10.2.  
![image](https://user-images.githubusercontent.com/13923468/28243231-58df1a20-6990-11e7-957e-8c7c63b32f0c.png)
![image](https://user-images.githubusercontent.com/13923468/28243232-63e12ae4-6990-11e7-94f8-29c2e980c770.png)

**Comment by elijahlorden** [comment]
Yes, the turret has the Serial Port addon installed.

**Comment by Keridos** [comment]
Can you please post the log here. It works fine for me in my dev environment.

**Comment by elijahlorden** [comment]
[fml-client-latest.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1150719/fml-client-latest.txt)

**Comment by Keridos** [comment]
Weird, it even tells you that lua integration is enabled.

**Comment by elijahlorden** [comment]
Any update on this?

**Comment by Keridos** [comment]
Cannot reproduce this here, works fine for me.

**Comment by elijahlorden** [comment]
In your dev environment?  Have you tried an actual install with the latest version available from Curse?

**Comment by Keridos** [comment]
Managed to fix it, still not sure why it did not work...

**Comment by Keridos** [comment]
Try this build here: https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/lastSuccessfulBuild/artifact/build/libs/openmodularturrets-1.10.2-3.0.0-196.jar

with this OMlib version: https://jenkins.ironhide.de/job/OMLib%201.10.2/lastSuccessfulBuild/
