### ISSUE TITLE
[1.10.2] turret_base compoenet...still...not available.

### ISSUE THREAD

**Issue by elijahlorden** [OpenModularTurretsTeam/OpenModularTurrets#362]
I'm sorry to bring this up again after a fix was supposedly uploaded to Curseforge, but I am still unable to access the turret_base component.  The issue is appearing exactly the same as it was before I updated the mod.  I can provide any additional information required in order to diagnose this.

**Comment by Keridos** [comment]
I managed to get it workin in my normal installation.

**Comment by Keridos** [comment]
Seems to be an issue within OC, closing this, update to  a dev build of OC.
