### ISSUE TITLE
[1.6.4] Resonant Turret Base not sync with ModularTurrets.cfg

### ISSUE THREAD

**Issue by Toderon** [OpenModularTurretsTeam/OpenModularTurrets#366]
The " _I:baseTierFourMaxIo=12500_ " in the ModularTurrets.cfg does not affect the Turret Base ingame.
The " _I:baseTierFourMaxCharge=10000000_ " does(!).
InGame, its still " _Max IO: 10_ ".

![omtbug-maxio](https://user-images.githubusercontent.com/30398150/28507087-6a0ca12c-7030-11e7-9b33-59ce05e95ebe.png)
_The only one i changed is the " _I:baseTierFourMaxCharge=10000000_ " from 10k to 25k for virtualization._

**Comment by Keridos** [comment]
The 1.6.4 version is not supported anymore.
