### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by Domenk01** [OpenModularTurretsTeam/OpenModularTurrets#367]
Good afternoon.
Immediately sorry for my English, I use an interpreter.
I play one project with a mod OpenModularTurrets-1.7.10-2.1.8-199, I installed 20 bases of turrets, after that, Minecraft began to consume 4+ Mbps of Internet.
This greatly complicates the game on the server with your mod, since my internet is rather weak ...

The question itself: has the problem described above been resolved on the latest version of your mod?

**Comment by Keridos** [comment]
Try latest version please.... We get bug reports or issues for people using ancient version quite often lately. Please, ALWAYS try the latest version released on curseforge, then see if the problem persists and then create an issue please
