### ISSUE TITLE
1.11.2 Industrialcraft2 and galacticraft cable won't connect.

### ISSUE THREAD

**Issue by Fungie2134** [OpenModularTurretsTeam/OpenModularTurrets#368]
![2017-08-09_22 02 34](https://user-images.githubusercontent.com/23421917/29141473-add65634-7d4e-11e7-9608-0337a8c24939.png)
All which can be said...
In 1.10.2 no problem were present.

Not that it work with thermal foundation : 
![2017-08-09_23 27 41](https://user-images.githubusercontent.com/23421917/29144753-68ef3bf6-7d5a-11e7-9581-511aafa32a7c.png)

**Comment by Keridos** [comment]
Will try this out.

**Comment by Fungie2134** [comment]
Thanks. I hope it will be fixed soon !

**Comment by Keridos** [comment]
Managed to at least fix IC2 cables.

**Comment by Fungie2134** [comment]
Thanks, if the issue continue... I will create another.
