### ISSUE TITLE
ComputerCraft Support / Features

### ISSUE THREAD

**Issue by MrXCharles** [OpenModularTurretsTeam/OpenModularTurrets#369]
So I've basically been hunting through the pages looking for a wiki on which commands you can use with ComputerCraft for this Mod for OMT 1.7.10 and couldn't seem to find one. I was wondering if somebody could point me in the direction of this if there is one - or in the case no such wiki exists, could anyone tell me if it is possible to use commands from ComputerCraft to Fire any of the Turrets?

Any help is much appreciated.

**Comment by Keridos** [comment]
Doesn't CC have support for showing all the commands? The names of the functions then should be fairly easy.
When I have time for it, I will probably make a wiki page with all the functions though.

**Comment by Keridos** [comment]
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/wiki/OC-CC-Functions
