### ISSUE TITLE
Projectiles shoots unknown direction

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#374]
Hi, I tried the 3.0.0-210 version on a Valkyrien Warfare ship, projectiles do not shoot on target but some unknown direction. Turrets does point on target though, it's just the projectiles do not function well.

**Comment by Sunspot0411** [comment]
![2017-08-25_03 44 33](https://user-images.githubusercontent.com/25239527/29685343-c9838c1c-8947-11e7-90b1-829f0bbf3635.png)
![2017-08-25_03 44 34](https://user-images.githubusercontent.com/25239527/29685344-c983eea0-8947-11e7-8ed8-3b37ae33127f.png)
![2017-08-25_03 44 36](https://user-images.githubusercontent.com/25239527/29685342-c982ea64-8947-11e7-807c-d3a87808c3ce.png)

**Comment by Keridos** [comment]
VW integration is totally bugged right now, we are waiting for the dev of VW to fix his mod. We cannot even load it in our dev environment.

**Comment by Keridos** [comment]
Closing this
