### ISSUE TITLE
openmodularturrets (3.0.0-214) requires omlib v3.0.0-127

### ISSUE THREAD

**Issue by scalda** [OpenModularTurretsTeam/OpenModularTurrets#377]
Hi the latest version of openmodularturrets (3.0.0-214) requires omlib v:3.0.0-127 which is not avalible on curse

[![Screenshot from Gyazo](https://gyazo.com/2543bdd16d7ccd792298505361debe36/raw)](https://gyazo.com/2543bdd16d7ccd792298505361debe36)

**Comment by Keridos** [comment]
Yeah will fix that, sorry.

**Comment by Keridos** [comment]
Uploaded it.

**Comment by sandalle** [comment]
Open Modular Turrets 1.10.2-3.0.0-214 loads fine with the upload OMLib 1.11.2-3.0.0-127, thank you. :)
