### ISSUE TITLE
turret base gui issue

### ISSUE THREAD

**Issue by pyscho974** [OpenModularTurretsTeam/OpenModularTurrets#378]
i know there was a closed thread on this but did not see anyone mention the actual reason it seems the gui does not work.. 

in sp  it all works great .. for servers that run bungee or a variation of that. it fails to give the gui that allows you to config targets or even break the base. 
in 1.7.10 this was bad with towny if you blew up the turret and towny would replace it.. causing the server to crash anytime someone would log back in where the towny replaced turret base was at.

from what ive read so far its due to the server in offline mode, which is a requirement for servers using bungee or waterfall to do its client authorization for servers with network hubs of multiple servers.

so im curious why there is not a work threw that lets it work threw this. is it just that its to time consuming to write the code to handle this.

am currently playing space astronomy 2 1.10.2 and this is how the issue appears to be happening.

**Comment by Keridos** [comment]
The 1.7.10 version actually has offline mode support and it *should* work by just checking against the stored name of the turret base. When towny replaces a turret base the problem just is that it does not initialize it properly. They store quite a bit of data and **require** an owner. If no owner is set when recreating it it will hard crash.

**Comment by pyscho974** [comment]
yes.. we had that issue on skyreachmc network.  was just a matter of setting the item id in towny to not replace it..  

was just seeing if was a way to get the gui to work with 1.10.2.    skyreach host several modded and vanilla mc servers

**Comment by Keridos** [comment]
in 1.10.2 offline mode should work
gonna investigate 1.7.10 though

**Comment by pyscho974** [comment]
know thread is closed just wanted to say thankyou for the time you took to look at it.. and we had trident running threw bungee with thermos.   seems that combination breaks its gui code.
