### ISSUE TITLE
Server Crashes When Player is Hit by Turret

### ISSUE THREAD

**Issue by Kaelthalon** [OpenModularTurretsTeam/OpenModularTurrets#379]
I believe the crash occurs when the player is wearing armor with thorn-like effects, then gets shot by a turret due to line of fire. The thorn-like effect comes from the mod Levels. Here is the pastebin of the crash report. Would it be possible to release a feature that prevents Friendly Fire?

https://pastebin.com/icyRXhWU

**Comment by Keridos** [comment]
Not our mod causing the crash, latest mod in the stacktrace is level. Friendly Fire is disabled for owners, for trusted players edit the config file.
