### ISSUE TITLE
1.12+ Port

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OpenModularTurretsTeam/OpenModularTurrets#380]
I cannot believe this has not been requested yet. I love your mod but I finally have the mod I was waiting on pushed forward; can you let me know wether you plan to port this to 1.12.1? I understand if you are busy or something it happens or maybe you are done modding but I was just wondering about port status.

/edit by Keridos:
- [x] OMlib for 1.12+
- [x] Changes planned (Recipe rewriting mainly, a few minor changes in when certain things are registered.

**Comment by Keridos** [comment]
Already planned. Currently waiting for the last features of 1.10/1.11 to be added, will do a port then, its planned since quite some time but currently I am fairly finished with what I wanted to do.

**Comment by P3rf3ctXZer0** [comment]
thank you @Keridos

**Comment by Boolyman** [comment]
Is there a beta build of it that we could use as filler in the mean time?

**Comment by Keridos** [comment]
No

**Comment by D3nnis3n** [comment]
Any News on this?

**Comment by Keridos** [comment]
Done!
