### ISSUE TITLE
Accidental Damage not Working

### ISSUE THREAD

**Issue by Kaelthalon** [OpenModularTurretsTeam/OpenModularTurrets#381]
I'm playing Craft of the Titans modpack on a server, which has the latest version of OMT (3.0-214). In the config file, the "Should player get hurt by accident" config is set to false. The owner and trusted players are still hurt by OMT turrets if they are in the line of sight of a targeted mob.

On a seperate note, I had mentioned this in a previous issue, but it was overlooked and closed. I'm hoping that if this issue is fixed, it'll prevent crashes due to the Levels mod for the time being. As of right now, OMT turrets are the only ones causing the crash, the IE turrets do not. According to the Levels issues page, there hasn't been much communication or progress to fix their mod. I'm looking into it at the moment to see if I can't figure out the onLivingHurt bug.

**Comment by Keridos** [comment]
Can you regenerate your config file? We changed the layout of the file a bit.

**Comment by Keridos** [comment]
Nevermind, found an issue.

**Comment by Keridos** [comment]
Fix should be released on curseforge!
