### ISSUE TITLE
Issue with ars magica 2 boss

### ISSUE THREAD

**Issue by AkaruC** [OpenModularTurretsTeam/OpenModularTurrets#382]
OMT version: 1.10.2-3.0.0-214
Forge version: 12.18.3.2488
AM2 version: 1.10.2-1.5.0-18 (not sure if relevant but can't hurt)
Crash log: https://pastebin.com/Mme72gu5

From what I'm seeing the boss tries to hurt/apply an effect to a part of the turret or the projectile it fires, which then causes a nullpointer to crash the server.

The boss in question is the water guardian, but it might be the same with other bosses that try to apply an effect on any entity around them.

**Comment by Keridos** [comment]
That is an ars magica bug.
