### ISSUE TITLE
[1.10.2] Issue with Turrets Causing damage to Entities

### ISSUE THREAD

**Issue by MJRLegends** [OpenModularTurretsTeam/OpenModularTurrets#383]
Ok so i got this bug reported to me, The issue report the player made to me is very detailed even with a video. 

See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/131

OpenModularTurrents Version: 3.0.0-214
OMLib Version: 3.0.0-127

Need any more information or testing please do message me here or my posted issue report 

Thanks for your time :P

**Comment by Keridos** [comment]
Can you try this please: https://jenkins.ironhide.de/job/OpenModularTurrets-1.10.2/lastSuccessfulBuild/artifact/build/libs/openmodularturrets-1.10.2-3.0.0-215.jar

**Comment by MJRLegends** [comment]
@Keridos Getting a NET::ERR_CERT_REVOKED error on that site, any ideas how i can allow it

**Comment by Keridos** [comment]
Eh, use Firefox or Edge, the sites certificate authority was removed from Chrome

**Comment by MJRLegends** [comment]
Will do thanks, i will test when i get home in like 5 hours

**Comment by MJRLegends** [comment]
Says i need OMLib 3.0.0-129 But i cant get it from your Jenkins as its saying the error now on Edge
![](https://i.gyazo.com/f924f057883eebecc516c42b69603ad2.png)

**Comment by MJRLegends** [comment]
**I've done some more testing with it:**

❌ = Failed/Didnt solve it
🆗 = Worked/Solved it

## Test 1 🆗 
I downgraded to 

**OMLib Version:** 3.0.0-119
**OpenModularTurrents Version:** 3.0.0-196

And it worked as intended
See https://gyazo.com/dc9a5340b1d43e56e2bd4be1be2e61b2
## Test 2 ❌ 
I then tried using

**OpenModularTurrents Version:** 3.0.0-214
**OMLib Version:** 3.0.0-127

and reset my config files for both mods and didn't work
## Test 3❌ 
I then tried using 

**OpenModularTurrents Version:** 3.0.0-210
**OMLib Version:** 3.0.0-126

and reset my config files for both mods and didn't work
## Test 4🆗 
I then tried using the mods on there own so just OpenModularTurrents & OMLib

**OpenModularTurrents Version:** 3.0.0-214
**OMLib Version:** 3.0.0-127

And it worked as intended
See https://gyazo.com/aed972286acd3744924e10669a1cd92c

So something is breaking it but idk what..... i will keep testing

**Comment by MJRLegends** [comment]
Ok after spending like 3 hours testing, i have found the mod causing me pain its this one https://minecraft.curseforge.com/projects/vanilla-tools adding it with 

OpenModularTurrents Version: 3.0.0-210
OMLib Version: 3.0.0-126

or 

OpenModularTurrents Version: 3.0.0-214
OMLib Version: 3.0.0-127

breaks the turrets, the mod is now out my pack, and i will make my own to do the stuff i need from that mod haha :D

**Comment by MJRLegends** [comment]
@Keridos Ok so i know the issue, The mod above is designed to stop vanilla swords and pickaxes, hoes, shovels, axes. 

By looking at your source code the reason its not working is because your using a fake player with a vanilla sword to kill them which is giving it no damage...

But dont worry i have made my own code for what this mod did and i've added it so its detecting FakePlayer so your turrets will work and vanilla tools will have no damage for just the player :D 

See: https://github.com/MJRLegends/Space-Astronomy-Tweaks/commit/86d99900a1aa932e6cdb0567c3f770b43bedeae6#diff-c3478b598f05848e20a3e7195e1e0432R72

Im going to call this closed since its not a issue on your side :D

**Comment by Keridos** [comment]
Thanks for the thorough testing. Yeah that explains stuff. The looting addon needs the fake player and a fake sword with looting on it.
