### ISSUE TITLE
Fake Drops Add-on cause damage to bug out

### ISSUE THREAD

**Issue by SwiftingDuster** [OpenModularTurretsTeam/OpenModularTurrets#384]
**Problem:**
Laser and rail gun turrets get its damage reduced to 1 if I place any amount (1-4) of fake drop add-on.

**Extra Info:**
1. Fake drop add-on seems to be a problem by itself. This happens without placing any other upgrade in the base.
2. Happens in both Single Player and Server I'm playing on. (Space Astronomy 2 Modpack)
3. Only tried and found the problem on Tier 5 Base.
4. *(Unrelated)* Speaking of fake drop add-on, rail guns apparently make mobs drop XP by itself but laser turrets do not even though they both drop loot. This was why I thought of placing fake drop add-ons in my laser turrets. I think this is a bug too?

**Versions:**
OMT 3.0.0-214
OMLib 3.0.0-127
Forge 12.18.3.2422

**Comment by Keridos** [comment]
Gonna test this in my dev environment. Thanks for reporting.

On 3 October 2017 05:52:15 GMT+02:00, Ting Wei <notifications@github.com> wrote:
>**Problem:**
>Laser and rail gun turrets get its damage reduced to 1 if I place any
>amount (1-4) of fake drop add-on.
>
>**Extra Info:**
>1. Fake drop add-on seems to be a problem by itself. This happens
>without placing any other upgrade in the base.
>2. Happens in both Single Player and Server I'm playing on. (Space
>Astronomy 2 Modpack)
>3. Only tried and found the problem on Tier 5 Base.
>4. *(Unrelated)* Speaking of fake drop add-on, rail guns apparently
>make mobs drop XP by itself but laser turrets do not even though they
>both drop loot. This was why I thought of placing fake drop add-ons in
>my laser turrets. I think this is a bug too?
>
>**Versions:**
>OMT 3.0.0-214
>OMLib 3.0.0-127
>Forge 12.18.3.2422
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/384

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
