### ISSUE TITLE
Crash in 1.10.2 with OMlib 127 & 129

### ISSUE THREAD

**Issue by Ouack23** [OpenModularTurretsTeam/OpenModularTurrets#386]
Hi,
didn't find any other issue with this bug even though multiple pastebins show the same java exception.

My game crashes with the following log : [https://pastebin.com/hf5sJsX2](https://pastebin.com/hf5sJsX2)

Forge 1.10.2-2511
Windows 10 x64
Java 1.8.151 x64
modlist in the log

Hope this helps,
Ouack23

**Comment by Keridos** [comment]
You are not using the latest 1.10.2 version. As the front page states, all 1.11.2 builds are compatible with 1.10.2
