### ISSUE TITLE
[MC 1.12.2] Cannot craft Sensor Tier 4+

### ISSUE THREAD

**Issue by sandalle** [OpenModularTurretsTeam/OpenModularTurrets#389]
I added Open Modular Turrets 1.12.2-3.0.0-221 to my [Minecraft 1.12.2 modpack](https://github.com/sandalle/nst-world-of-color) , but the Sensor (Tier 4) and Sensor (Tier 5) have no recipe (at least in [Just Enough Items](https://minecraft.curseforge.com/projects/just-enough-items-jei)).

I do have [No More Recipe Conflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict) installed, in case that is interfering.

Forge Mod Loader: 1.12.2-14.23.0.2542
OMLib: 1.12.2-3.0.0-131

**Comment by Keridos** [comment]
Yeah found the issue, fix incoming next few days.

**Comment by sandalle** [comment]
This appears to be fixed for me in Open Modular Turrets 1.12.2-3.0.0-227, thanks @Keridos . :)
