### ISSUE TITLE
2 issues found.

### ISSUE THREAD

**Issue by Moobien** [OpenModularTurretsTeam/OpenModularTurrets#390]
Hey guys just finally decided to play 1.12.2 and i have 1 bug to mention for the latest version on curseforge (1.12.2-3.0.0-221 omlib 1.12.2-3.0.0-131), the other issue i will mention i have seen a lot in the 1.11.2 versions.

1.12.2: i am guessing you want EVERYONE to use this mod as i am noticing it appearing in the tabs for a lot of other mods. Even the inventory destroy box thingy in creative mode has been changed to a t1 sensor.

1.11.2: i have noticed that some turrets simply cant hit smaller mobs such as bats or mini skeles/zombies. I can overcome this by putting in scatter upgrades.

https://imgur.com/a/fSBcU

**Comment by Keridos** [comment]
The first one is already fixed in dev versions and I have replaced the targeting code by something that should hit mobs that implement the wrong getEyeHeigth() function (I am looking at you, Mekanism).

**Comment by Moobien** [comment]
Sweet. You rock
