### ISSUE TITLE
In other creative tabs still

### ISSUE THREAD

**Issue by Zer0Lyfe** [OpenModularTurretsTeam/OpenModularTurrets#391]
![2017-11-23_10 15 11](https://user-images.githubusercontent.com/28994351/33156714-50d63cce-d037-11e7-9105-d0ee4ad571d7.png)

"1.12.2: I am guessing you want EVERYONE to use this mod as I am noticing it appearing in the tabs for a lot of other mods."
#390

**Comment by Keridos** [comment]
That is OMPD, not OMT, closing this here. Gonna be fixed in next OMPD release. OMT is fine.

**Comment by Zer0Lyfe** [comment]
oops sorry about that but thank you
