### ISSUE TITLE
Game crash on load (1.11.2)

### ISSUE THREAD

**Issue by Wizardon777** [OpenModularTurretsTeam/OpenModularTurrets#392]
**Mod version:** openmodularturrets-1.10.2-3.0.0-222
**Forge version:** 13.20.1.2530
**Minecraft version:** 1.11.2

**Description:**
After updating the mod to version "openmodularturrets-1.10.2-3.0.0-222", The game crashes on startup.

**Crash report:**
[crash-2017-11-23_20.46.33-client.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1501697/crash-2017-11-23_20.46.33-client.txt)

**Comment by Keridos** [comment]
On 24.11.17 13:57, Wizardon777 wrote:
> **Mod version:** openmodularturrets-1.10.2-3.0.0-222
> **Forge version:** 13.20.1.2530
> **Minecraft version:** 1.11.2
> 
> **Description:**
> After updating the mod to version "openmodularturrets-1.10.2-3.0.0-222", The game crashes on startup.
> 
> **Crash report:**
> [crash-2017-11-23_20.46.33-client.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1501697/crash-2017-11-23_20.46.33-client.txt)
> 
> 
Update forge, gonna add a dependency to forge. We build against 2550 or so.

**Comment by Keridos** [comment]
Gonna look into this. quite weird.
