### ISSUE TITLE
Crash on trying to place turret base?

### ISSUE THREAD

**Issue by Chronomera** [OpenModularTurretsTeam/OpenModularTurrets#393]
a custom pack i made has ran and loaded fine, so i started making a bit of a "spawn" area for safety and figured "Why not place a cool turret at spawn"
Trying to place a base freezes and crashes the game for no reason i could particularly understand.

[crash-2017-11-29_22.27.29-client.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1516774/crash-2017-11-29_22.27.29-client.txt)

**Comment by Keridos** [comment]
Should be fixed
