### ISSUE TITLE
[1.12.2] Crashes on forge 2576 and newer

### ISSUE THREAD

**Issue by DeadSix27** [OpenModularTurretsTeam/OpenModularTurrets#396]
Due to the changes made in this forge release:
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2576/forge-1.12.2-14.23.1.2576-changelog.txt

OMT crashes upon start with this stacktrace: https://gist.github.com/DeadSix27/49dbeeccb468c50184c4ed82aa167b78

Not sure how relevant that is, e.g whether forge has to act or you.

**Comment by Keridos** [comment]
Uh this is interesting, gonna dig into that, might take some time though.

**Comment by DeadSix27** [comment]
@Keridos This happens with both OMT and OMPD I think, but omlib alone starts fine.

**Comment by Keridos** [comment]
Fixed in latest release
