### ISSUE TITLE
TurretHead.setSide can load new chunks

### ISSUE THREAD

**Issue by mezz** [OpenModularTurretsTeam/OpenModularTurrets#397]
I am helping out a server which says chunks are being loaded all the time even without chunk loaders.

It seems like `TurretHead.setSide` and `WorldUtil.getTouchingTileEntities` do not check that the chunk is loaded when it is checking the blocks around it, so it can load new chunks and contributes to their issue.

**Comment by Keridos** [comment]
How do I check if a chunk is being loaded?

**Comment by mezz** [comment]
### To fix:

To avoid loading chunks, any time you check a tile entity or block in the world that is not at your position, you should check `World#isBlockLoaded()` or `World#isAreaLoaded` first.

The way I would solve it in your case would be to have `setSide()` check that the area around it is loaded and return a boolean like this: 
https://gist.github.com/mezz/c9569dafd5c11d30b3a6316faaaf3b20
In the `update()` logic you can return right away if `setSide()` returned false. When your turret is on chunk boundaries next to an unloaded chunk, entities and other things are inactive so it will not need to handle updating when it's there.

 ### To detect:

The way I found that the turrets are loading chunks was by using Player's Sampler mod. It's a utility mod that's available on [the same page as FastCraft](https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-25-note-all-posts-of-new-members-need-to-be-approved-firs/). It has a command (`/sampler loads show` to start and `/sampler loads hide` to stop) which create console logs with stack traces any time a chunk gets loaded by something.

The server I tried it on has some turrets right on chunk boundaries, so they are loading each other in some situations (along with some other mods with similar issues, I reported a few!).

**Comment by Keridos** [comment]
Thank you for the detailed explanation. I will add that in for the next curseforge release.
