### ISSUE TITLE
[1.12.2] Client Crash Tesselating block model Turret base lvl5 Laser

### ISSUE THREAD

**Issue by Morpheus1101** [OpenModularTurretsTeam/OpenModularTurrets#400]
Crash log @ https://gist.github.com/Morpheus1101/63c30b92ce09f6850780b85e943bfa0f

Forge *.2607
OMT v3.0.0.230

**Comment by Keridos** [comment]
That looks like either secret rooms or chickenbones mods doing weird stuff, the stacktrace does not even contain OMT classes or OMLib ones.

**Comment by Morpheus1101** [comment]
After removing the block an replacing it with the same again since this was on a SMP server i play on the issue hasnt re-occured and re-testing in SMP an SP i cant reproduce the issue at all to be able to properly test, so im closing this untill when/IF the issue ever seems to re-occur
