### ISSUE TITLE
Crash with Minecraft 1.12.2 (Modded)

### ISSUE THREAD

**Issue by Dorzar** [OpenModularTurretsTeam/OpenModularTurrets#402]
Hello! the crash it happens when I put a base for turrets, I close Minecraft and I reload the world.

[krothium-1518197672461.log](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/1711903/krothium-1518197672461.log)

**Comment by Keridos** [comment]
No OMT crash, read the crash log, there is zikarium reactors doing something strange.
