### ISSUE TITLE
OpenComputers control program

### ISSUE THREAD

**Issue by Moobien** [OpenModularTurretsTeam/OpenModularTurrets#403]
Just wondering, with the compatability for OpenComputers do any control programs exist for these turrets?

**Comment by Keridos** [comment]
Not sure about that, not yet heard something about that.

**Comment by Moobien** [comment]
Bugger. Eould be cool to have

**Comment by Keridos** [comment]
Leaving this open for people to join the conversation. Maybe when OMTC is a bit more finished I will start making a few example programs in a seperate repo.

**Comment by Moobien** [comment]
I had an idea for a new turret too. I have hundreds of arrows, one that can fire vanilla and modded arrows would be cool
