### ISSUE TITLE
OMT + Chisel 

### ISSUE THREAD

**Issue by Moobien** [OpenModularTurretsTeam/OpenModularTurrets#404]
Hey Keridos has there been any reported bugs when applying a chisel block as cammo for the turret base? For some reason mine turns completely invisible and i can see through it into the forest above my underground base

**Comment by Moobien** [comment]
Also a query, I can't seem to place turret bases less than 3 or so blocks apart from each other, is this by design?

**Comment by Keridos** [comment]
The placing restriction is a feature to not allow spamming a place with turrets. As for the chisel blocks, depends on how the chisel guys implement their chiseled blocks. I simply copy the rendered quads from the blockstate.

**Comment by Moobien** [comment]
Makes sense for not spamming.

**Comment by Keridos** [comment]
The thing is I have a lot of other bugs needing more attention, You could tag the chisel devs to take a look at this and help me here. I do not want to look through Chisels render system myself (because it probably is a lot of work)

**Comment by pyscho974** [comment]
see this is still an issue.  has this issue been linked to the chisel guys yet?  pack im playing seems any block so far that is not a vanilla block  has this issue tho. ill do further testing .  seems nether ex mod does not work either for camo options.   using 243 version dont see anything yet saying this has been addressed anywhere all the ores blocks work so not limited to only vanilla .. but anything that is linked with chisel i guess. assuming the nether ex basalt is linked to the chisel basalt somehow

**Comment by CptSpaceToaster** [comment]
I'm fairly certain the project moved over here: https://github.com/Chisel-Team/Chisel
No harm... but I think you're pinging the wrong project.

**Comment by pyscho974** [comment]
@CptSpaceToaster  is why i asked if it had been  mentioned yet to the chisel team. due to its still a issue with camo the base to a chisel block.  i wasnt able to find it on there github  for chisel team as a link or refernce so they knew about it

**Comment by pyscho974** [comment]
@CptSpaceToaster  sorry your right.. its pinged to the wrong group where the issue is at.  im no sure how to ping like that tho.

**Comment by tterrag1098** [comment]
Sorry, but plenty of other mods manage to render chisel models just fine. They are, after all, just baked models. Same as anything else. This is not a chisel issue.

**Comment by Keridos** [comment]
https://github.com/OpenModularTurretsTeam/OMLib/issues/14
