### ISSUE TITLE
Request - Lunar Cells

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [OpenModularTurretsTeam/OpenModularTurrets#405]
Okay so sometimes it not fun to have to get build pipes etc and in some cases its hard could you add a lunar cell upgrade which would charge RF at night?

**Comment by Keridos** [comment]
we could theoretically do that, but limit the energy harvested by it

**Comment by P3rf3ctXZer0** [comment]
As long as I can change defaults via config but thank you for this :)

**Comment by Keridos** [comment]
We will make another mod for generating power soon.
