### ISSUE TITLE
Cant Configure Turret Base

### ISSUE THREAD

**Issue by Daaaniel0631** [OpenModularTurretsTeam/OpenModularTurrets#406]
I have Forge server and i have some mods on the server, but when I try to configure the turret it does not show me the offer with confugation as in single-player, please help and advice what it might be

**Comment by Keridos** [comment]
Duplicate of a lot of issues, search through the closed issues please.

**Comment by Keridos** [comment]
Duplicate of a lot of issues, search through the closed issues please.
