### ISSUE TITLE
Sounds still unacceptably loud 1.7.10.

### ISSUE THREAD

**Issue by cyris69** [OpenModularTurretsTeam/OpenModularTurrets#407]
Since it appears this has never been done here is my ogg files tones down to acceptable levels.

To replace:
Use 7z for your archive program, find the OMT jar, right click and open archive.
Find the sound files (OpenModularTurrets-1.7.10-xxxxxxx.jar\assets\openmodularturrets\sounds\) and delete them. Unzip the file in the link then drag the ogg files into the same area you just deleted the original sounds. Profit and no longer go deaf <3
http://www.mediafire.com/view/k9d1j8kf6xa5ht1/OMT_Sounds.zip

**Comment by P3rf3ctXZer0** [comment]
@cyris69 go to config and turn it down also why the hell are you on 1.7.10 and the very minimum 1.10.2 is the standard.

**Comment by Keridos** [comment]
If this is wanted, just make a PR
