### ISSUE TITLE
1.12.2 -- EnderIO item conduits not connecting

### ISSUE THREAD

**Issue by Teibidh** [OpenModularTurretsTeam/OpenModularTurrets#410]
I know EIO beta just came out, but, I'm converting away from the three mods I was using to replace it in 1.12.2 and much to my dismay item conduits aren't connecting to bases natively. I don't recall having to do anything special to make this work previously, but I do now.

**Comment by Keridos** [comment]
WIll checkin with the EIO devs to see what needs to be done

**Comment by tyler489** [comment]
Item conduits connect to things that use IInventory or IItemHandler capability

**Comment by Keridos** [comment]
Having the code for that ready, it might just delete old inventory data. Had to change quite a bit more than anticipated. Testing would be great for that, will include a link in here once it is ready.
