### ISSUE TITLE
1.12.2 -- Recipes bugged

### ISSUE THREAD

**Issue by Teibidh** [OpenModularTurretsTeam/OpenModularTurrets#411]
When "enderio" is set for the recipe method in config, or when "auto" is set with EnderIO installed, the recipes for turrets with EnderIO components are not displayed in JEI. I can't say with any certainty whether or not the recipes work as I don't know them offhand and am not willing to stand up an older version of MC to get them to validate.

**Comment by Keridos** [comment]
Will look into this

**Comment by tyler489** [comment]
Several Of the Resource names and metadata has changed in 1.12
i would recommend using oredict names instead of resource names.

**Comment by zortag** [comment]
Setting mekanism as recipe set not works too. the only workaround i found is using vanilla recipes

**Comment by Keridos** [comment]
I have seen that Forge now has a similar loading mechanism from pre 1.12 in 1.12.2 Will overhaul the recipe system completely the next days.
