### ISSUE TITLE
Extra Utilities 2 Transfer Pipes Not Filling Ammo Slots

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [OpenModularTurretsTeam/OpenModularTurrets#412]
Minecraft version: 1.12.2
OpenModularTurrets version: 1.12.2-3.0.0-236
Extra Utilities 2 version: 1.12-1.7.4

I was planning to outfit my base with a number of railgun turrets, and connect them to Extra Utilities 2 transfer pipes, as they can simultaneously transmit RF and items. The idea was that the pipes would be able to power and autofill the turrets simultaneously. However, after extensive testing in creative mode, I have confirmed that the turret base simply will not accept item input from transfer pipes. However, it will still accept power from them. Is this a bug, or are transfer pipes not fully supported?

**Comment by Keridos** [comment]
Probably the same bug as with the EnderIO conduits.

**Comment by AwesomeAnimationGamer** [comment]
Ah, Ok. So it's not fixable then? It's alright if it's not, I can work around it

**Comment by Keridos** [comment]
See at the enderIO bug #410 
Is probably the same bug, I will fix that. Closing this in favor of the other Issue.
