### ISSUE TITLE
Laser Rework

### ISSUE THREAD

**Issue by Knito58** [OpenModularTurretsTeam/OpenModularTurrets#416]
//edited by Keridos to turn this into an overview for the laser rework.
Lasers should be a beam, not a projectile.

- [x] Targeting calculations
- [x] Rendering Logic
- [x] Rework Damage calculation and apply it directly (extra damage when low armor)

//original (adjusted grammar)
A target which is hit by a laser bolt should never suffer a mass impact and never become pushed away from the laser.

**Comment by Knito58** [comment]
And when we are at it: It does not make sound either. Targets hit by a laser will never know from where they are targeted because they cannot hear the shot. But I will not insist in this as every laser in every star wars episode generates some noise - even in airless space.

**Comment by Keridos** [comment]
This is entirely not how lasers work.
Photons hitting something makes an impact, google solar sails for proof. Also a laser hitting you makes part of you spontaneoously switch phase from solid/liquid to gaseous or even plasma. That expands this matter and can create a sound. 

/update: And even sound in vacuum is a thing. See https://www.youtube.com/watch?v=l8MljsHpYRk

**Comment by Knito58** [comment]
The sun would have destroyed all of its planets millions of years ago if there were any impact of solar light mass notable by any other than highly scientific instruments. Zombies are no scientists at all. And as you said: Material may vaporate and may or may not do something similar to a "rocket boost effect". But not on earth. And the sound is created when the laser bolt leaves the turret, not on impact.
Ok, in real world there's water in the air which will evaporate and make a "sssssssssst" noise when the beam passes and you get your ear close to it.

Edit: I watched the video and on first sight there seems to be evidence for sound in vacuum. But now: His vacuum box is very small. The material is connected to something which has contact with the rest of the scenario. Compressional waves are for sure conducted and get hearable by transferring vibrations to the hull of the vacuum box. Also there is impact of exploded materials on the inside of the box which can be heared on the outside. Oveall: His vacuum box is too small to prove anything. And you and I we know that sound is transmitted through air, so what?

And heres a video of a vacuum experiment with a peeep-peeeep device in it - no explosion at all. When the air is removed, theres no sound at all.

https://www.youtube.com/watch?v=goqdjnWywgI

I love her: https://www.youtube.com/watch?v=BpgPXZh1WEQ

**Comment by Knito58** [comment]
Concealed laser turrets without noise and no push-back would be awesome in PvP: Your friends are dead before they are aware where the turrets are sitting. Atm the impact pushes them out of the danger zone. And they automatically turn into the direction from where they were hit / pushed.

**Comment by Keridos** [comment]
Will remove the pushback or at least greatly lower it, but the noise will stay for now.

/edit: Also Cody's video explains why you hear sounds pretty well. Because the impact/explosion creates gas that can very well transmit sound, because the sound everybody hears is just atoms banging against something. Also this is a good video debunking space myths, by an actual astronaut: https://www.youtube.com/watch?v=t6rHHnABoT8

And you did not seem to have googled solar sail at all, via E=mc² every photon does have a virtual mass. This enables it to actually create a measurable impact. Cody also has a video about that.

**Comment by Knito58** [comment]
Yay thank you! 

Noisy space:
I agree that as long as you are hit by exploding gas in space you will hear the boom. He also explains that the sun is an nuclear explosion which takes place for millions of years. He sais that we cannot hear it because the sound - which actually is there - is not transmitted because the transmitting matter for sound waves is missing. Else we would become deaf as the sun is very loud. I believe that if you can go near enough to the sun, there where still enough matter is, one may hear it. And probably die.

I am very happy about your intention to lower the pushback. Lasers are my favourite turrets, even now whith pushback. 

Greetings, 
Konitor

**Comment by Keridos** [comment]
@Knito58 I used this issue to list all the things we will implement for a complete rework of the laser turret.

**Comment by Knito58** [comment]
Thank you. I'm already pleased about the reduced knockback. But wow! A (probably) red laser beam!
I'll stay tuned.

**Comment by Keridos** [comment]
The knockback is apparently quite impossible to fix unless we implement a custom damaging function ourselves.
Because being hit by something with attackEntityFrom(anything) seems to knock you back.

**Comment by Knito58** [comment]
But the knockback value can be changed. Weapons with knockback enchantment can knock a mob further away. If we think of it, it is just a number. Higher number pushes further, lower number pushes less. Maybe theres even a negative knockback possible which wourld attract the mob.

Only thinking....

**Comment by Knito58** [comment]
New weapon suggestion (laser type):

The BTP Laser. BTP = Backwards Travelling Particles. This beam is projected towards the target and becomes weaker the farer away from source it is. The particles on the beam travel back to source and apply a negative knockback to the target which becomes pulled versus the more damaging zone where the laser is stronger.

How about that idea?

**Comment by Knito58** [comment]
And the beam's colour would be poison green...

**Comment by Brycey92** [comment]
So... a tractor beam?

**Comment by Knito58** [comment]
Not really. A tractor beam would not damage the target. This one deals more damage the nearer the target comes.
The particels get shot away to [infinity] and there they are harmless because they are diffused. When travelling backwards to the origin they become denser and more and more damaging. The target gets slightly pushed nearer to the origin and takes more and more damage.
This is so because of some totally abstract physical laws which will be discovered in about 50 years and which will describe teleporting and homing quark particles (T&HQPs) which is not possible in real world yet but hey - this is minecraft and we have trees parking in mid-air.

It is an idea about a negative laser - a weapon with negative pushback that nobody has until now. 
Deadly!

**Comment by Brycey92** [comment]
Ah, that sounds way cooler!
