### ISSUE TITLE
[fixed, using wrong OMlib version] Upgrades do not persist after server reboot

### ISSUE THREAD

**Issue by Axylxys** [OpenModularTurretsTeam/OpenModularTurrets#418]
This is a major issue i'm having. Turret addons and upgrades vanish entirely whenever the server is rebooting. 

This is happening with latest 1.12 version (247), on tier 5 base with Laser turrets. Damage addon, fake player loot addon, fire rate/range/accuracy or even concealing the turret, everything goes away after reboot.

Turrets are not linked to anything special (getting their energy from a Flux point from Flux networks mod) and chunkloaded.

Edit: after quick testing the same issue happens with all bases and several turret types and energy sources. So it doesn't seem linked to anything else.

Edit bis: Found the issue, i didn't update OMlib from 140 to 143. Updating it fixed the issue, it could be worth adding an update checker when the game launch if the library is outdated :)

**Comment by Keridos** [comment]
Yeah should be working now in newest OMT build, accidentally commented out the line that did the version checking some time in my dev env.
