### ISSUE TITLE
Mod No Longer On Curse

### ISSUE THREAD

**Issue by Boolyman** [OpenModularTurretsTeam/OpenModularTurrets#419]
Open Modular Turrets is a big part of my recent pack release.  But now I am getting a notice that your mod is no longer availalble on Curse?  Is this temporary?  It would require a big rewrite of my quest book if thats the case.

**Comment by dmf444** [comment]
https://minecraft.curseforge.com/projects/openmodularturrets

OMT is still there....

Are you getting this from the twitch launcher?

**Comment by Boolyman** [comment]
Yes, its not exporting OMT with the rest of my pack... saying it will be rejected because the mod isnt available on curse any more

**Comment by dmf444** [comment]
Not 100% sure, but it may be because you've used a version that's been archived or deleted? Make sure that it's the latest version of the mod.

**Comment by Boolyman** [comment]
It is the latest.

**Comment by Keridos** [comment]
Nope, it is not, I archived build 247 because it had a serious problem with a server crash regarding expanders.
