### ISSUE TITLE
Turret Base Tiers and Recipe Rebalancing

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#42]
At this moment we have wooden tier, then tier one to four. Should we not change that to Tier one to five? I find this difference irritating. 
- [x] rework Turret Tiers

**Comment by Poenjabiesous** [comment]
I too have noticed my OCD haggling me by the fact that there isnt a "middle" rf base tier. We can add another if needed. PS: I'm in Vietnam on business atm, will push my fixes I have so far changes once I get home.

**Comment by Keridos** [comment]
You might need to merge my latest 2 commits into that. I changed a bit regarding item rendering and added a whole bunch of new classes.

**Comment by Keridos** [comment]
Also we need some changes for recipes. Diamonds required for even a tier1 sensor is not good imo. We need a bit more progressive recipes to make it a bit more accessible for early game.
