### ISSUE TITLE
ic2 energy compatibility

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#433]
all 1.11.2 versions do not receive ic2 energy

**Comment by ccinv** [comment]
1.7.10 versions do not receive eu as well
have the same problem as same as #252 ,it seems Version 2.2.2-220 did break something
And I didn't install Gregtech or other mods.
IC2 version 2.2.8-810-experimental

**Comment by Keridos** [comment]
1.7.10 is not supported anymore
@Sunspot0411 did you try the newest 1.11.2 release?

**Comment by Sunspot0411** [comment]
OK i just tried the newest version, it does work. gonna close this issue
