### ISSUE TITLE
when turret is pushed by piston the game crashes

### ISSUE THREAD

**Issue by mantorok4866** [OpenModularTurretsTeam/OpenModularTurrets#434]
I recently wanted to find out what would happen if I push a turret platform with a disposable turret on top
with a slime block and piston, the game froze, then crashed.  after reloading the game, the world loads and it appears that the turret base moved and the turret head dropped into an item. heres the crash log:
The game crashed whilst tesselating block model
The game crashed whilst tesselating block model
Error: java.lang.NullPointerException: Tesselating block model

**Comment by Keridos** [comment]
Ok, turret bases should not be movable by pistons

**Comment by Keridos** [comment]
Fix is now on curseforge!
