### ISSUE TITLE
No projectile animation for Railgun

### ISSUE THREAD

**Issue by ZXQWAS** [OpenModularTurretsTeam/OpenModularTurrets#435]
I haven't tried anything other than the railgun yet, but I don't see any projectile animation for it. While it has a nice model which reflects addons, it has some light rainbow steam over it, it has a very nice sound effect, there's no projectile animation, it feels missing.

**Comment by Keridos** [comment]
Are you aware at how fast a railgun shoots? Probably at more than 1/10th of lightspeed, that would be a minimum of 30,000 km/s. You won't see the shot at all probably, maybe a trace of smoke, but that is it.

The "missing" projectile is intended :-)

**Comment by ZXQWAS** [comment]
There's a smoke and a flash at least: https://www.youtube.com/watch?v=58MmOpSm4LY
There's usually some blast effect on the impact as well. This sort of works well with https://minecraft.curseforge.com/projects/mob-dismemberment, creating those splashy sounds all around (or whereever else that sound comes from), but I feel there could be more.
Also I was talking about the vortex-ey trails in most other games with railguns. Your choice, ofc.
