### ISSUE TITLE
Mod Conflict with ReWIRED's kinetic deflector

### ISSUE THREAD

**Issue by raindropworks** [OpenModularTurretsTeam/OpenModularTurrets#439]
Built a defense system using rail gun turrets.  Works perfectly against normal armor, but the ReWIRED mod features a kinetic deflector (that `Stops Incoming Projectiles at the cost of power`, https://minecraft.curseforge.com/projects/rewired).  It seems when the rail gun fires at a player using this specific implant, something is done to the ferro slug that the server doesn't like, causing it to immediately crash.
[crash-2018-08-25_20.45.57-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/2321048/crash-2018-08-25_20.45.57-server.txt)

**Comment by Keridos** [comment]
This crash because there is probably a missing null pointer check in ReWIRED.
Gonna leave this open until it is fixed, though.

**Comment by raindropworks** [comment]
I'll try to open a report with them as well then

**Comment by raindropworks** [comment]
ReWIRED is putting out a mod update shortly.  I'll test it when it drops and if it's working then I can close this one out

**Comment by raindropworks** [comment]
Got the new updates from both of you, should fix this issue, thanks!
