### ISSUE TITLE
Thaumcraft conflict

### ISSUE THREAD

**Issue by raindropworks** [OpenModularTurretsTeam/OpenModularTurrets#440]
Outside my base I have a base set up with five laser turrets set to just attack mobs.  Had another user come nearby that was using some sort of spell function, that is visually shown as bats.  Near as I can tell online they're literally called 'spell bats'.  I don't know much about them, but apparently the turrets saw bats and treated them as targets, trying to let loose a barrage on them.  One shot triggered the same kind of error I saw in #439 earlier today (we think a shot went wide and hit the player instead).

I'm not sure how to recreate the issue as I don't know the first thing about how Thaumcraft works, so not sure if this is something that can be fixed (i.e. a blacklist) or it it would require Thaumcraft to use different entities that don't report as mobs

**Comment by Keridos** [comment]
Well it probably hit the player when the crash reports look the same.

**Comment by raindropworks** [comment]
Yeah, which I know that has it's own fix coming, but I was more trying to figure out about it shooting at the spell bats in general.  It's definitely not an ideal, or expected behavior, since the bats in this case are friendly to a player, but depending on how it's coded, your system may not be able to tell the difference

**Comment by Keridos** [comment]
Well we do differentiate between players, mobs and passive mobs (such as bats or cows).
And if the mods incorporate EnumCreatureType checks correctly our mod should be able to tell the difference fine.

**Comment by raindropworks** [comment]
So I should poke the Thaumcraft group about that?  It seems there are some passive spell bats that buff the caster, and others that will attack other players.  If I'm following right, they changed the EnumCreatureType for all spell bats, instead of just the offensive ones?

**Comment by Keridos** [comment]
No, I did not say anybody changed anything. I just did state how OMT differentiates between mobs etc.

**Comment by raindropworks** [comment]
Oh, wait, that's right ... because bats would be mobs, not neutrals
