### ISSUE TITLE
There should be a config option to allow concealing turrets without the addon

### ISSUE THREAD

**Issue by Brycey92** [OpenModularTurretsTeam/OpenModularTurrets#442]
In 1.7.10, there used to be an option in each turret base to hide the turrets when they were inactive. In 1.12.2, there is no such option.

**Comment by Brycey92** [comment]
I just discovered that this is a turret addon now, so this is no longer important, but consider it a feature request for there to be a mod config option to either provide a GUI or require the turret addon.

**Comment by Brycey92** [comment]
Does the implementation of this conceal all turrets, or allow users to configure the setting for each turret?

**Comment by Keridos** [comment]
eh globally so far.
<- lazy, something else would mean I need to do GUI stuff.
