### ISSUE TITLE
Rework player authentication

### ISSUE THREAD

**Issue by Brycey92** [OpenModularTurretsTeam/OpenModularTurrets#443]
Turrets don't target opped players, no matter their gamemode, and there isn't any configuration in the OMT config to change this behavior. I currently have `Enable OPs to access all owned blocks` set to true in the OMLib config, but I need this to administrate my server.

The reason I need this configuration option is that several mods (including OMLib) require admins to have OP to perform certain administrative functions. On my server, and I'm sure many others, the admins (OPs) also play in survival. Without turrets targeting opped players, admins have an unfair advantage in PvP in survival.

/edit by Keridos:

We need to implement another way to authenticate players, currently the result can just be true, if allowed or false, if not. For targeting it should be owner/trusted, not trusted and OP, with the latter being that the player can access because of OP. This way we can differentiate between real owner and OPs in targeting.

**Comment by Keridos** [comment]
Ok , this is a bit tricky to fix
