### ISSUE TITLE
Upgrade effects should be configurable per turret

### ISSUE THREAD

**Issue by Brycey92** [OpenModularTurretsTeam/OpenModularTurrets#444]
Currently, only damage upgrades are configurable per turret. The others (accuracy, efficiency, range, and rate of fire) are only configurable globally. This prevents turrets from being configured to each have different ranges of upgradability.

For instance, I want to be able to make rate of fire upgrades have less effect on the laser turret.

**Comment by Keridos** [comment]
Commit on this repo is ready, not just pushed yet.
