### ISSUE TITLE
Multiblock howitzers that powered by man?

### ISSUE THREAD

**Issue by 012phuong** [OpenModularTurretsTeam/OpenModularTurrets#446]
You guys should add a multiblock structures like a 105mm howitzer or Katyusha rockets salvoes which can fire manually or through command (like ICBM rocket designator but for artillery) so we will have a better way to protect our land or attack other players land

**Comment by Keridos** [comment]
That will probably be added in the far future. We do have plans for manual control and multiblock turrets, but that is MC 1.13 or maybe even later.

**Comment by Keridos** [comment]
See #423
