### ISSUE TITLE
Turrets not allowing access after changing Minecraft name.

### ISSUE THREAD

**Issue by ThePuzzlemaker** [OpenModularTurretsTeam/OpenModularTurrets#447]
Problem: When a player changes their Minecraft name, all turrets they have access to are now denied, even if they own the turret. This appears to be caused by using player names for ownership and permissions.

_Possible Solution: A way to fix this would be to use UUIDs rather than player names; player names can change, but UUIDs do not unless you switch accounts._

OpenModularTurrets Version: 1.12.2-3.0.1-264

**Comment by Keridos** [comment]
Only if offline mode is enabled in the config. We do use UUIDs otherwise.

https://github.com/OpenModularTurretsTeam/OMLib/blob/1.12/src/main/java/omtteam/omlib/util/PlayerUtil.java#L102-L114
