### ISSUE TITLE
Turrets Crash with Lord Craft

### ISSUE THREAD

**Issue by Cazadorsniper** [OpenModularTurretsTeam/OpenModularTurrets#448]
Every time a turret shoots the game crashes, happens in singleplayer and multiplayer,  not sure mod which is causing the issue so posting this here too. 

https://pastebin.com/HShTjcjB

Turrets work completely fine without Lord Craft.

**Comment by Keridos** [comment]
Caused by Lord Craft, added info on its issue tracker.

**Comment by Cazadorsniper** [comment]
Ok thanks, just wanted to make sure.
