### ISSUE TITLE
Owner registration problem on breaking bases.

### ISSUE THREAD

**Issue by spylor** [OpenModularTurretsTeam/OpenModularTurrets#453]
In the config I have indicated that bases shouldn't be breakable by anyone but the owner and hardness is -1.
I'm playing on forge 1.12.2 - 14.23.5.2768 and openmodularturrets-1.12.2-3.0.1-264.
When a base is broken by the owner or anyone else before the placer (owner) "opens" it, it will break and spawn back right away but the owner will become a generic 'owner' and the base will no longer be accessible by the placer or anyone else. The same thing happens if the placer doesn't 'open' the base before placing a turret on it.

**Comment by Keridos** [comment]
Oh yeah I think I encountered that while testing around with new features some time ago, seems to be a regression.

/update: Could not reproduce the breaking base bug. That bases are breakable though they should not be is fixed though.
