### ISSUE TITLE
Turret behaviour buggy

### ISSUE THREAD

**Issue by NanoCats** [OpenModularTurretsTeam/OpenModularTurrets#454]
Relastivistic turret does not seem to do anything.
Turrets shoot weirdly on short distances.

From the OP:

-Turret behavior can be kinda buggy, I placed a turret on the ground next to some enemies and it shot a few through walls, and was unable to hit an enemy at POINT BLANK range (Targets closer than 2 blocks will NOT be killed by most sentry guns)

-Relativistic turret doesn't seem to do anything

**Comment by Keridos** [comment]
Which version?

AS for the drop turrets, I know that, range incositency I for not have not yet seen, and also the turrets not hitting at point blank is an issue.

**Comment by NanoCats** [comment]
Version is the current latest available (openmodularturrets-1.12.2-3.0.1-264.jar)


Here's a short recording of the issue with the range upgrades. After I stopped recording I found the range of the sentry gun went up despite the range upgrades having been removed. 

Here are some clips of the issue in action [1](https://gfycat.com/PowerfulUnderstatedGnat) [[2]](https://gfycat.com/TidyPoshBats)

The sentries don't seem to generate anything in the log.


P.S, I can't shift click to fill ammo inventories

**Comment by Keridos** [comment]
Ok, gonna start working on those. Thanks for reporting!

**Comment by Keridos** [comment]
Splitted this issue so I can better track the bugs.

**Comment by Keridos** [comment]
Its all fixed now, the relativistic turret slows and weakens enemies btw.
