### ISSUE TITLE
You have problems with compatibility 

### ISSUE THREAD

**Issue by KiraLinux** [OpenModularTurretsTeam/OpenModularTurrets#461]
with the mod primitive mobs, the turrets do not kill all hostile mobs

1.12.2-forge1.12.2-14.23.5.2806
omlib-1.12.2-3.0.1-162
ompd-1.12.2-3.0.0-36
primitivemobs-1.2.3
multimob-1.0.4

**Comment by Keridos** [comment]
I am fairly sure that primitive mobs is not tagging their mobs correctly then.
