### ISSUE TITLE
question with source code

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#462]
Hi, i downloaded the zip of 1.10.2/1.11.2 branch source code and try to run setupdecompwork space, but it does not work. mind telling me what went wrong?

**Comment by Sunspot0411** [comment]
ok i find it is because a lot of maven repositories are missing. that's ok, i'm not trying to change anything with the mod but just want to know in build.gradle of 1.10.2 branch which ones of the repositories are related to
 
compileOnly "ValkyrienWarfareRevamped:valkyrienwarfare:${config.valkyrienwarfare_version}:dev"

in dependencies

is it ivy {
        url "http://ae-mod.info/builds"
        layout "pattern", {
            artifact "[module]-[revision](-[classifier])(.[ext])"
        }?

**Comment by Keridos** [comment]
Just comment out VW

**Comment by Sunspot0411** [comment]
thank you! i have one more question about the setting up of vw local dependency, how was 

ValkyrienWarfareRevamped:valkyrienwarfare:${config.valkyrienwarfare_version}:dev

local dependency set up at the begining?

**Comment by Keridos** [comment]
? VW compatability is disabled because the dev went away and it has been severely broken.
