### ISSUE TITLE
NullPointerException wipes entire VM's RAM

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [OpenModularTurretsTeam/OpenModularTurrets#470]
#### What happens:
When changing dimension by interacting with Dimensional Doors' blocks(the fabrics) , the game halted, and RAM usage was wiped to only 50ish MB. This is a severe issue as my modpack usually takes around 5GB in world

**NOTE:** Not sure will this happen when changing to other dimensions , as DDLimbo is the first dimension I entered after Overworld

#### What you expected to happen:
Simply goes to yet another Limbo in DD

#### Steps to reproduce:
1. Somehow goes into DD's Limbo
2. Interact with monoliths/eternal fabrics
____
#### Affected Versions (Do *not* use "latest"):

- OMT: 3.0.1
- OMLib: 3.0.1
- Minecraft: 1.12.2
- Forge: b2824
- SpongeForge? n
- Optifine? y
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 
https://pastebin.com/DnuMu1Cq

**Comment by Keridos** [comment]
Well, that looks interesting, let me check what happened there. Could you please try to reproduce this with the latest curseforge alphas (the 3.1.0 ones)?

We do not actually do anything with other mods ram, my best guess is that the game crashed and somehow did not shut down the VM correctly.

**Comment by Pythonic-Rainbow** [comment]
@Keridos I will try it in this week, and btw the halt actually doesn't happen everytime, it happens twice with the same `NullPointerException` in `latest.log` (because the VM just halts but not game crash), so I think it is not a random issue. Anyways will catch you up when I tested it

**Comment by Pythonic-Rainbow** [comment]
@Keridos u guys discovered this? or its still need more info? If I still can't replicate this in the coming months, I will inform here and completely closes this

**Comment by Keridos** [comment]
No could not reproduce it.
