### ISSUE TITLE
Game Crashes on load up

### ISSUE THREAD

**Issue by SirAron111** [OpenModularTurretsTeam/OpenModularTurrets#473]
#### Issue Description:
Game crashes on loadup

#### What happens:
Crash on game loading

#### What you expected to happen:
Starting the game normaly

#### Steps to reproduce:

1.get the new versions
2.run it up (in dimension zero modpack in case some mods conflict caused it)
3.watch it crash
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT:openmodularturrets-1.12.2-3.1.0-324.jar
- OMLib:omlib-1.12.2-3.1.0-221.jar 
- Minecraft:1.12.2
- Forge:14.23.5.2825
- SpongeForge? yes/no
- Optifine? yes also witouth
- Single Player and/or Server? All

https://pastebin.com/XYXVzsTK

**Comment by Keridos** [comment]
Do you have hwyla installed?
Nevermind, found out what it was.

**Comment by Keridos** [comment]
Fixed and released on Curseforge
