### ISSUE TITLE
Collection of small rendering fixes

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#474]
- [x] Damage addon tearing issue
- [x] jei gui extra areas (drawDefaultBackround())
- [x] render addons only on valid turrets
- [x] fix expander gui rendering

**Comment by SirAron111** [comment]
I don’t know if this is the gui bugs talked about in here but I have some pictures of such bugs (don’t have a picture of it but I can confirm that the damage addon shows on the turrets that don’t do dmg (like the teleporting one and the freezing one which looks a bit strange))

![2019-05-03_16 38 59](https://user-images.githubusercontent.com/39855956/57145807-46c76100-6dc4-11e9-9880-af1fc651a11b.png)
![2019-05-03_16 39 11](https://user-images.githubusercontent.com/39855956/57145809-46c76100-6dc4-11e9-9a98-7140973cb3fb.png)

These are pictures of the standard turret gui once you hover over something it gives you the red item field on the right and the other one is from looking in a turret inventory expander.

**Comment by SirAron111** [comment]
Happens with and without texture pack
