### ISSUE TITLE
Setup Guide

### ISSUE THREAD

**Issue by TFSpectre** [OpenModularTurretsTeam/OpenModularTurrets#478]
A setup guide would be helpful, I have the 1.12.2 version and the OMLib for the version but the mod is not available from the crafting table when looking it up, there is nothing for the mod listing, it is on the server and client. I’m using the All the Mods 3 setup on the server, it is unlocked and the mod added on the client.

**Comment by Keridos** [comment]
that is not a problem on our end, something is wrong with your modpack. Just drop it in the mods folder on BOTH server and client and go.
