### ISSUE TITLE
Minecraft 1.12.2 (Modded) Crash.

### ISSUE THREAD

**Issue by JulCee** [OpenModularTurretsTeam/OpenModularTurrets#479]
Please i got crash, when i open inventory with J.E.I and put the item to the Turret then i got a crash...

here the Crash-report:
https://pastebin.com/TJVLLZYd

how to fix it???

**Comment by Keridos** [comment]
Fix is incoming

**Comment by JulCee** [comment]
> 
> 
> Fix is incoming

Thanks you :)
