### ISSUE TITLE
Server crashes when an enemy player comes near an active laser turret.

### ISSUE THREAD

**Issue by mentimjojo** [OpenModularTurretsTeam/OpenModularTurrets#482]
#### Issue Description:
The latest version of OMT and OMlib crashes the server when an enemy player comes in range of an active laser turret. The turret is using multiple addons.

#### What happens:
Server crashes.

#### What you expected to happen:
Player getting shot.

#### Steps to reproduce:

1. Let a player come to a turret that is active against other players.
2. Done, server is crashed again.
3.
____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.1.3-354
- OMLib: 1.12.2-3.1.3-243
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2836-universal
- SpongeForge? No.
- Optifine? No.
- Server.

##### Crash 1:
https://pastebin.com/3ykU5vQf

##### Crash 2 (We were testing if this was really the issues for the server crash)
https://pastebin.com/ysYf9DUc

**Comment by Keridos** [comment]
This still is weird, please try this build and see if that works. https://jenkins.ironhide.de/job/OMTTeam/job/OMLib-1.12-3.1.x/244/

**Comment by Keridos** [comment]
Fixed in latest CF Release

**Comment by mentimjojo** [comment]
Hi. Awesome work! Thank you.
