### ISSUE TITLE
Rewrite of Targeting System

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#483]
Make the turrets way smarter and modularize the targeting system.
- [x] basic layout, 1 function to get best entity, 1 function to filter every invalid entity
- [x] priority system 5 priorities, each one can get a value assigned to it (maxhp, hpremaining, distance, armor, player)
- [x] add custom entity filtering function to TurretHeads
- [x] ~~add in UI to manage this~~ (OMTControl)

**Comment by SirAron111** [comment]
Can’t wait for this to work currently the turrets have some mobs they don’t attack like from primitive mobs mod or grimoir of gaia

**Comment by Keridos** [comment]
This won't change that. I will prolly just add a config based list of mobs you can change to add mobs.

**Comment by AkiraKitsune** [comment]
what about adding an in game ui that allows you to config the mobs, kind of like how you use /summon to spawn mobs like witches.

even if hard to code, this may make it easier for those who are unsure of how to use or access the config file.

**Comment by Keridos** [comment]
Forge already adds in a config GUI for mods, OMT etc. support this as well.
It is in the mod list menu under mod options.

**Comment by AkiraKitsune** [comment]
ok, thank you for telling me that.
