### ISSUE TITLE
Placing/breaking tile entities next to turrets breaks them.

### ISSUE THREAD

**Issue by TheUnderTaker11** [OpenModularTurretsTeam/OpenModularTurrets#487]
#### Issue Description:
Placing a tile entity next to a turret will sometimes break it (depending on the tile entity) and breaking said tile entity next to the turret will almost always break the turret.

#### What happens:
Turrets break when tile entities are placed/broken next to them.

#### What you expected to happen:
Turrets don't break unless you do it in GUI

#### Steps to reproduce:

1. Place a tier 5 turret base with laser turret on it.
2. Place a vanilla chest next to the laser turret itself (aka adjacent)
3. Watch as the turret will break when you place and/or break the vanilla chest.
____
#### Affected Versions (Do *not* use "latest"): 

- OMT: openmodularturrets-1.12.2-3.1.3-355
- OMLib: OpenModsLib-1.12.2-0.12.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2838 I think
- SpongeForge? no
- Optifine? Yes but isn't client issue
- Single Player and/or Server? Only tested on server, not on SP.

#### Your most recent log file where the issue was present: 
[latest.log](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/3415348/latest.log)

This is the server log.

**Comment by Keridos** [comment]
Cannot reproduce this.

Probably is some other mod causing this.

**Comment by TheUnderTaker11** [comment]
Aw dang, well that sucks cause I have no clue what mod would do this!

**Comment by Keridos** [comment]
Try a binary search -> remove half of the mods, if error persists, try the other half. Repeat until you have found the culprit.
