### ISSUE TITLE
Grenade turret crashes my game

### ISSUE THREAD

**Issue by matty45** [OpenModularTurretsTeam/OpenModularTurrets#488]
#### What happens:
Grenade turret fires at mobs and suddenly causes the game to crash.

#### What you expected to happen:
I expected the grenade turret to fire at the mobs normally.

#### Steps to reproduce:

1. Place a tier 3 turret base.
2. Place grenade turret ontop of the base.
3. Fill it with ammo
4. Let it fire at mobs.
...

____
#### Affected Versions :

- OMT: openmodularturrets-1.12.2-3.1.3-355
- OMLib: omlib-1.12.2-3.1.3-246
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? SP

#### Your most recent log file where the issue was present: 
https://paste.dimdev.org/iganerazoj.mccrash

**Comment by Keridos** [comment]
Thanks for the report, can confirm this. Next patch will fix this, still have not fully worked it out yet though.

**Comment by Keridos** [comment]
Fixed with v3.1.4
