### ISSUE TITLE
Redstone Reactor with extender crashes server

### ISSUE THREAD

**Issue by Rofle44** [OpenModularTurretsTeam/OpenModularTurrets#489]
#### Issue Description:

So when i load up any turrets with addons and upgrades it chrashes the game after that. 
even without any mobs

#### What happens:

The game crashes and whenever i load it up again it immediatly crashes again. (i lost 3 survival worlds already...)

#### What you expected to happen:

normally it  wouldnt crash

#### Steps to reproduce:

1.build a turret (erectin´ a sentry)
2.put 3 inventory extender level 5 and fill it up with a redstone reactor, recycler, any upgrade (i used faster firing), redstone
3.watch the game crash
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 3.1.0-335
- OMLib: 3.1.0-232
- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- SpongeForge? no
- Optifine? yes
- Single Player ? yes

#### Your most recent log file where the issue was present: 

[---- Minecraft Crash Report ----

WARNING: coremods are present:
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  CXLibraryCore (CXLibrary-1.12.1.jar)
  MMFMLCorePlugin (Multi-Mine-Mod-1.12.2.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  TickrateChanger (TickrateChanger-Mod-1.12.2.jar)
  ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  HCASM (Hammer-Core-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/19/19 7:23 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at omtteam.openmodularturrets.util.TurretHeadUtil.getSpecificItemStackItemFromBase(TurretHeadUtil.java:375)
	at omtteam.openmodularturrets.tileentity.TurretBase.updateRedstoneReactor(TurretBase.java:144)
	at omtteam.openmodularturrets.tileentity.TurretBase.func_73660_a(TurretBase.java:402)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at omtteam.openmodularturrets.util.TurretHeadUtil.getSpecificItemStackItemFromBase(TurretHeadUtil.java:375)
	at omtteam.openmodularturrets.tileentity.TurretBase.updateRedstoneReactor(TurretBase.java:144)
	at omtteam.openmodularturrets.tileentity.TurretBase.func_73660_a(TurretBase.java:402)

-- Block entity being ticked --
Details:
	Name: openmodularturrets:turret_base // omtteam.openmodularturrets.tileentity.TurretBase
	Block type: ID #1076 (tile.turret_base // omtteam.openmodularturrets.blocks.BlockTurretBase // openmodularturrets:turret_base)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-1291,5,183), Chunk: (at 5,0,7 in -81,11; contains blocks -1296,0,176 to -1281,255,191), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Actual block type: ID #1076 (tile.turret_base // omtteam.openmodularturrets.blocks.BlockTurretBase // openmodularturrets:turret_base)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -6888572568468724619
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-1226,4,167), Chunk: (at 6,0,7 in -77,10; contains blocks -1232,0,160 to -1217,255,175), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 184565 game time, 123506 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 61516 (now: false), thunder time: 6761 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1694978984 bytes (1616 MB) / 3221225472 bytes (3072 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version           | Source                                        | Signature                                |
	|:------ |:--------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                         | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                         | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | obfuscate                   | 0.2.6             | minecraft.jar                                 | None                                     |
	| LCHIJA | voxelmap                    | 1.9.10            | VoxelMap-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | bdlib                       | 1.14.3.12         | BdLib-1.12.2.jar                              | None                                     |
	| LCHIJA | betterbuilderswands         | 0.13.2            | Better-Builders-Wands-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | betterthanmending           | 1.1.1             | Better-Than-Mending-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | blockarmor                  | 2.4.10            | Block-Armor-Mod-1.12.1.jar                    | None                                     |
	| LCHIJA | cfm                         | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                        | None                                     |
	| LCHIJA | clumps                      | 3.1.2             | Clumps-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | codechickenlib              | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cookingforblockheads        | 6.4.71            | CookingForBlockheads_1.12.2-6.4.71.jar        | None                                     |
	| LCHIJA | craftablegunpowder          | 1.12.2            | CraftableGunpowder.jar                        | None                                     |
	| LCHIJA | yarrmateys_cutemobmodels    | 1.0.16            | Cute-Mob-Models-Remake-Mod-1.12.jar           | None                                     |
	| LCHIJA | cxlibrary                   | 1.6.1             | CXLibrary-1.12.1.jar                          | None                                     |
	| LCHIJA | cyclopscore                 | 1.4.0             | CyclopsCore-1.12.2-1.4.0.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | deltaruneitemsmod           | 0.0.1             | Deltarune items mod.jar                       | None                                     |
	| LCHIJA | dimdoors                    | 3.0.9+287         | Dimensional-Doors-Mod-1.12.2.jar              | None                                     |
	| LCHIJA | everlastingabilities        | 1.5.1             | EverlastingAbilities-1.12.2-1.5.1.jar         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | extraanvils                 | @VERSION@         | Extra-Anvils-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | shadowmc                    | 3.8.0             | ShadowMC-1.12.jar                             | None                                     |
	| LCHIJA | extrarails                  | 1.3.0             | Extra-Rails-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | fastleafdecay               | v14               | FastLeafDecay-Mod-1.12.1.jar                  | None                                     |
	| LCHIJA | ichunutil                   | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | gravitygun                  | 7.0.0             | Gravity-Gun-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | hammercore                  | 2.0.4.2           | Hammer-Core-1.12.2.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | placebo                     | 1.6.0             | Placebo-1.12.2.jar                            | None                                     |
	| LCHIJA | hydrogel                    | 1.1.0             | HydroGel-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | improvableskills            | 3.6.1r            | Improvable-Skills-Mod-1.12.2.jar              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | ironchest                   | 1.12.2-7.0.67.844 | Iron-Chests-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | jei                         | 4.15.0.283        | jei_1.12.2-4.15.0.283.jar                     | None                                     |
	| LCHIJA | fluidtank                   | 4.2               | Large-Fluid-Tank-Mod-1.12.2.jar               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | fluidtank_ae2               | 4.2               | Large-Fluid-Tank-Mod-1.12.2.jar               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | fluidtank_theoneprobe       | 4.2               | Large-Fluid-Tank-Mod-1.12.2.jar               | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LCHIJA | lasermod                    | 0.0.1-Patch1      | lasermod-0.0.1-Patch-1.jar                    | None                                     |
	| LCHIJA | lblades                     | 1.0.2             | LegendaryWeapons-V1.0.2.jar                   | None                                     |
	| LCHIJA | refraction                  | 1.9               | refraction-1.12.2-1.9.11.jar                  | None                                     |
	| LCHIJA | forgelin                    | 1.8.2             | Shadowfacts-Forgelin-1.12.2.jar               | None                                     |
	| LCHIJA | librarianlib                | 4.19.2            | librarianlib-1.12.2-4.19.2-release.jar        | None                                     |
	| LCHIJA | longfallboots               | 1.2.1a            | Long-Fall-Boots-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | lucky                       | 7.6.0             | Lucky-Block-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | mantle                      | 1.12-1.3.3.55     | Mantle-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | morefurnaces                | 1.10.5            | More-Furnaces-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | multimine                   | 1.6.1             | Multi-Mine-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | multimob                    | 1.0.5             | multimob-1.0.5.jar                            | None                                     |
	| LCHIJA | omlib                       | 3.1.0-232         | OMLib-1.12.2.jar                              | None                                     |
	| LCHIJA | ompd                        | 3.1.0-61          | Open-Modular-Passive-Defense-Mod-1.12.2.jar   | None                                     |
	| LCHIJA | openmodularturrets          | 3.1.0-335         | OpenModularTurrets-Mod-1.12.2.jar             | None                                     |
	| LCHIJA | primitivemobs               | 1.2.3a            | Primitive-Mobs-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | randomenchantments          | @VERSION@         | Random-Enchants-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | reforged                    | 0.7.5             | Reforged-Mod-1.12.jar                         | None                                     |
	| LCHIJA | rofles_amazing_pickaxes_mod | 1.0.0             | Rofles Amazing Pickaxes 1.12.2 Mod v 1.3.jar  | None                                     |
	| LCHIJA | rofles_amazing_swords       | 1.0.0             | Rofle´s Amazing Swords 1.12.2 Mod v 1.5.jar   | None                                     |
	| LCHIJA | ropebridge                  | 2.0.5             | ropebridge-1.12-2.0.7.jar                     | None                                     |
	| LCHIJA | silentlib                   | 3.0.13            | Silent-Lib-1.12.2.jar                         | None                                     |
	| LCHIJA | scalinghealth               | 1.3.37            | Scaling-Health-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | somanyenchantments          | 0.4.0             | So-Many-Enchantments-Mod-1.12.2.jar           | None                                     |
	| LCHIJA | supertnt                    | 1.0.1             | SuperTNT-1.12.2-1.0.1.jar                     | None                                     |
	| LCHIJA | tesla                       | 1.0.62            | Tesla-API-1.12.2.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | tickratechanger             | 1.0.14            | TickrateChanger-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | torchmaster                 | 1.7.1.74          | TorchMaster-Mod-1.12.2.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | trashslot                   | 8.4.6             | TrashSlot-Mod-1.12.1.jar                      | None                                     |
	| LCHIJA | uncrafted                   | 3.0.1             | Uncrafted-Mod-1.12.1.jar                      | None                                     |
	| LCHIJA | uncraftingtable             | 1.8-beta6         | Uncrafting-Table-Mod-1.12.1.jar               | None                                     |
	| LCHIJA | valkyrielib                 | 1.12.2-2.0.6b     | ValkyrieLib-1.12.2.jar                        | None                                     |
	| LCHIJA | waterstrainer               | 3.2.0             | Water-Strainer-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | cgm                         | 0.10.0            | Working-Gun-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | xlfoodmod                   | 1.12.2-1.8.0      | XL-Food-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | xp_ore                      | 1.0.0             | XP Ore 1.12.2 Mod v 3.jar                     | None                                     |
	| LCHIJA | xray                        | 1.4.0             | xray-1.12.2-1.5.0.jar                         | None                                     |
	| LCHIJA | librarianliblate            | 4.19.2            | librarianlib-1.12.2-4.19.2-release.jar        | None                                     |

	Loaded coremods (and transformers): 
LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
CXLibraryCore (CXLibrary-1.12.1.jar)
  cubex2.cxlibrary.CoreModTransformer
MMFMLCorePlugin (Multi-Mine-Mod-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
TickrateChanger (TickrateChanger-Mod-1.12.2.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
HCASM (Hammer-Core-1.12.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 215 names; 240 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.6.1r

	List of loaded APIs: 
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.2.1.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.283.jar
		* refraction_api (5) from refraction-1.12.2-1.9.11.jar
		* ScalingHealthAPI (2) from Scaling-Health-Mod-1.12.2.jar
		* valkyrielib.api (1.12-2.0.1a) from ValkyrieLib-1.12.2.jar
		* WIT-API (2) from Scaling-Health-Mod-1.12.2.jar
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge']

**Comment by Keridos** [comment]
Yeah will check on that, guess the redstone reactor is causing the issue here. Btw: Forge at least had a setting where you could just remove crashing tile entities. This would delete the base from the game but make the world playable again.

**Comment by Keridos** [comment]
Fixed with v3.1.4
