### ISSUE TITLE
Unable to add trusted players in the turret GUI.

### ISSUE THREAD

**Issue by Josh65-2201** [OpenModularTurretsTeam/OpenModularTurrets#491]
#### Issue Description:
When I go on the gui and type a players name it will not show up above on the list.

#### Steps to reproduce:
1. Open turrets gui
2. Go on configure 
3. Go on trusted players
4. Type player name
5. Click the plus icon

#### Affected Versions:
- OMT: 3.1.3-335
- OMLib: 3.1.3-246
- Minecraft: 1.12.2
- Forge: 14.23.5.2846
- SpongeForge?: no
- Optifine?: yes
- Single Player: yes

**Comment by Keridos** [comment]
Cou can only add valid players to the trusted players list.
