### ISSUE TITLE
Computercraft commands

### ISSUE THREAD

**Issue by Shalvan** [OpenModularTurretsTeam/OpenModularTurrets#495]
Hello,

how can i use computer craft with this mod ?
what are the commands i can paset in computer craft to change parameters of the turret ie. turn it on/off , add/remowe players form white list etc.

those are my first steps in this mod, and with the programming in minecraft, my experience are only with C++ 

thank You in advance

**Comment by Keridos** [comment]
Almost got it, just not create an issue, look at the https://github.com/OpenModularTurretsTeam/OpenModularTurrets/wiki instead :)

Specifically https://github.com/OpenModularTurretsTeam/OpenModularTurrets/wiki/OC-CC-Functions
