### ISSUE TITLE
OC Cable not connecting to turret base

### ISSUE THREAD

**Issue by 45freehold** [OpenModularTurretsTeam/OpenModularTurrets#497]
What happens:

Cables from OC do not connect to OMT turret base anymore.

What you expected to happen:

To connect OpenComputers cable straight to the turret base, as it used to be in previous versions. Now only works via an adapter.

Steps to reproduce:

1. Try to connect OC cable to OMT Turret base

____
Affected Versions (Do *not* use "latest"):

- OMT: 3.1.4-356
- OC: 1.7.5-192
- OMLib: 3.1.3-246
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no 
- Server

**Comment by Keridos** [comment]
The cable actually never did that. an adapter was always needed to use the turret base as it technically is not part of the network itself, it just exposes some functions.
