### ISSUE TITLE
Turret rendering on VS ship won't update

### ISSUE THREAD

**Issue by Sunspot0411** [OpenModularTurretsTeam/OpenModularTurrets#501]
#### Issue Description:

Turrets won't change there facing direction while firing when placed on a VS ship. Such an issue does not exist when placed on the normal world.

#### What happens:
If a turret is placed on a VS ship, they face upward all the time even if they are firing at a target not above them. 

#### What you expected to happen:
Let turrets facing direction render correctly on ship

#### Steps to reproduce:

1. Create a VS ship
2. Place an OMT turret on that ship and give it some target to shoot.
3. You will find facing direction of the turret does not change at all.
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.1.5-360
- OMLib: 1.12.2-3.1.3-246
- Minecraft:1.12.2
- Forge: 1.12.2-14.23.5.2825
- SpongeForge? no
- Optifine? yes
- Single Player and Server?

**Comment by Keridos** [comment]
Fixed via 83c30c29d07b712caec0b80822319a1a28468216
