### ISSUE TITLE
Game Crashing Upon Placement of Turret Base

### ISSUE THREAD

**Issue by BigBoi1** [OpenModularTurretsTeam/OpenModularTurrets#504]
#### Issue Description:

This crash is possibly directly related to other mods in my custom built mod pack, but the source of the crash is from this mod so I am posting this here in hopes that at the very least somebody could point me in the right direction of where to go if the crash stems from another mod. As the title says, the game crashes immediately after I place a turret base block. A mod list will be at the bottom of this post. This mod pack of mine is kind of haphazardly put together, and I'm currently working on solving issues to make it work and run good, so sorry if I did some stupid things that might seem obvious to you that could cause issues. Any help is appreciated.

#### What happens:

Game crashes as soon as I click to place a turret base block.

#### What you expected to happen:

Well, I expected to place a block as I have before

#### Steps to reproduce:

There aren't exactly steps to reproduce, as it happens when I place a block.

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.1.6-362 (Most recent for game version as of post)
- OMLib: 1.12.2-3.2.0-250 (Most recent for game version as of post)
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2847
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single Player

#### Your most recent log file where the issue was present: 

https://paste.dimdev.org/oduqihenut.mccrash

#### Mod List - Including Core Mods (If you need any specifics about mod versions, etc., let me know, there's nearly 100 so I don't want to find every specific mod version/detail for all the mods when for almost all, if not all, that info is irrelevant):

![Mod List 1](https://user-images.githubusercontent.com/45153931/74075810-7efa7080-49e2-11ea-8140-24759d4c69cb.PNG)
![Mod List 2](https://user-images.githubusercontent.com/45153931/74075812-81f56100-49e2-11ea-9431-45d15004802b.PNG)
![Mod List 3](https://user-images.githubusercontent.com/45153931/74075814-83bf2480-49e2-11ea-90db-d43c02392193.PNG)

**Comment by Keridos** [comment]
You are using wrong version of OMLib, either use 3.2.0 both or 3.1.6
