### ISSUE TITLE
Turrets seems can not attack ender dragon 

### ISSUE THREAD

**Issue by kingstick029** [OpenModularTurretsTeam/OpenModularTurrets#507]
Even laser gun can not deal damage to the dragon while it stay still . I think it is the problem about recognizing the hitbox of the dragon. Wish one day can kill the dragon with the turrets

**Comment by ghost** [comment]
This is weird, the laser turret can target the naga (Twilight Forest) which is also a boss, and kills it pretty fast.

**Comment by Keridos** [comment]
Well, both issues are weird, and I will look into them but not really linked 😄

**Comment by Keridos** [comment]
Eh I found a simple reason, ender dragon can only be damaged with rockets, preferable homing ones, you have to enable homing and the ability for them to target the ender dragon manually.

/quick edit: Does the laser even attempt to shoot the dragon?
