### ISSUE TITLE
[Suggestion] 1.12.2 omt

### ISSUE THREAD

**Issue by TheGiantBean** [OpenModularTurretsTeam/OpenModularTurrets#508]
I think it would be really cool to add integration between electroblob's wizardry and the disposable item turret. In electroblob's you have the choice to be able to cast a spell once using a scroll of the desired spell. Some scrolls can be used by dispensers which I thought is epic. So I immediately thought of the disposable item turret and wondered if it would work. Unfortunately, it doesn't even when set it so in the config. It technically does shoot the scroll to do damage but, doesn't cast the spell as I expected.
Looking forward to your response!

**Comment by Keridos** [comment]
Without looking at the source of that mod I cannot tell if that would be easy. It is quite likely that if I just try something blind things will crash horribly. Sorry to tell you, but I have no time to do any additional integration beyond what currently is supported/announced. 1.14 update and v4 of OMT are kind of both big projects to tackle currently.
