### ISSUE TITLE
World chrashes when dropping base without turret. Game crashes when dropping turret without turret.

### ISSUE THREAD

**Issue by Rofle44** [OpenModularTurretsTeam/OpenModularTurrets#509]
#### Issue Description:

The world crashes when you drop the base without turret. The game crashes when you drop turret without turret

#### What happens:

The world or game shuts down.

#### What you expected to happen:

Normally the base/turret should drop as expected.

#### Steps to reproduce:

1.Place base
2.Open base gui
3.press either drop base or drop turret button
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 3.1.6-362
- OMLib: 3.1.4-249
- Minecraft: 1.12.2
- Forge:  1.12.2-14.23.5.2838
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? Single player

#### Your most recent log file where the issue was present: 

[launcher_log.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/4303667/launcher_log.txt)
[latest.log](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/4303668/latest.log)
[debug.log](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/4303669/debug.log)
[2020-03-08-7.log.gz](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/4303670/2020-03-08-7.log.gz)

**Comment by Rofle44** [comment]
sorry for the sheer amount of log's i don't know which one i had to send

**Comment by Keridos** [comment]
Are you playing in offline mode?

**Comment by Keridos** [comment]
Fixed via 747d94393c9a9358e8950a2969ff3874f90a46fc
