### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by Rofle44** [OpenModularTurretsTeam/OpenModularTurrets#510]
I have some turret ideas i'd like to share since i really love this mod :) 

Tesla Turret:
uses energy to hit enemies with lightning bolt which "can" hurt multiple mobs

Fluid Turret:
Uses different fluis to shoot enemies away from base.
Lava can hurt entitys.

Speaker Turret:
Uses sonic waves to weaken, hurt or slow down entitys.
(also makes a good boombox)

Flamethrower Turret:
Sets entitys on fire

That's it
Thank your for your attention :)

**Comment by Keridos** [comment]
We already have a slowing turret and a turret that sets things on fire ;-)
And a tesla turret is planned, waiting on assets for that at the moment.
