### ISSUE TITLE
Crash Upon Opening World

### ISSUE THREAD

**Issue by AYYYYYYMD** [OpenModularTurretsTeam/OpenModularTurrets#516]
#### Issue Description:

During Blood Moons, the game usually crashes a few times with this exact error, but now it just crashes instantly.

#### Steps to reproduce:

1. stick a turret inventory expander in a turret mount
2. have a blood moon
3. wait.
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.1.7-367 (also still crashes with **v370**)
- OMLib: 1.12.2-3.1.4-249
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? Yes
- Single Player 
#### Your most recent log file where the issue was present: 

[https://paste.dimdev.org/bedaviyozu.mccrash]

**Comment by Keridos** [comment]
fix will be in the next 3.2.0 release, which may still be one or 2 days out.

**Comment by Keridos** [comment]
This is fixed on 3.1.7 now, next 3.2.0 alpha will have the same fix
