### ISSUE TITLE
Turrets missing on reload

### ISSUE THREAD

**Issue by craft90** [OpenModularTurretsTeam/OpenModularTurrets#519]
#### Issue Description:

Something must have broken in the recent update regarding the turret models. The turret goes invisible when the chunks reloads. Either when relogging into the save (tested on a singleplayer world) or when teleporting between chunks. I imagine it might occur on return to home base aswell though I haven't tested that. F3 reload doesn't fix the issue. 

By the way, the issue persist even with just Open Modular Turrets, OMlib and Open Passive Defenses. So it's not a cross-mod compatibility issue. The issue wasn't there in the older version either so it must be a recent bug,

#### What happens:

I noticed when I played around with a Stargate mod that my base defense turret (a laser turret on a level 5 base) went invisible. The turret was still there (its hitbox blocked my path) and seemed to remain operational (there was no sign of issue in the base interface). It seemed to still defend aswell, the issue seemingly to be only visual.

Only way to fix the issue is to chose the "drop turret" option and re-place the turret.

#### What you expected to happen:

Well I didn't expect the turret to go invisible on reload. Neither a force reload of the chunks or further teleport helped (I did notice though that each time I teleported in the turret made a break/placing sound and particles appeared.)

#### Steps to reproduce:

1. Start a new world.
2. Place a level 5 base and a laser turret on top.
3. Stack it with: 1 solar panel, 4 dmg boost, 4 range mods, 1 efficiency.
4. Reload the save (quit to main menu and then rejoin)
5. Turret is now invisible.
____
#### Affected Versions (Do *not* use "latest"):

- OMT: 3.1.7-368
- OMLib: 3.1.4-249
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Single player.

**Comment by Keridos** [comment]
Curseforge should have a new release in a few minutes. And thanks for the detailed report.

**Comment by craft90** [comment]
You're welcome! I'm glad it was of help for you to fix the issue.
