### ISSUE TITLE
[openmodularturrets]: Tried to add duplicate mob to mob list: ArmorStand

### ISSUE THREAD

**Issue by MarshTheBacca** [OpenModularTurretsTeam/OpenModularTurrets#520]
#### Issue Description:

It says in the server console this:
[openmodularturrets]: Tried to add duplicate mob to mob list: ArmorStand
I know it's probably harmless but it would ease my mind if my console had fewer warnings. It happens on both my custom modpack (MarshTheModpack) and a blank forge server with just OMT and OMLib installed.

#### What happens:
OMT tries to create a duplicated mob (armor stand)

#### What you expected to happen:
I expect there to be no attempt to create a dublicate mob as vanilla 1.12.2 already has an armor stand

#### Steps to reproduce:

1. Run a blank 1.12.2 forge server with OMT and OMLib
2. Look in log and see that warning
____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.1.8-369
- OMLib: 1.12.2-3.1.4-249
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847
- SpongeForge? yes/no: no
- Optifine? yes/no: no
- Single Player and/or Server?: server

#### Your most recent log file where the issue was present: 

https://pastebin.com/A8TX8Ed2

**Comment by Keridos** [comment]
That is nothing to worry about. And it doesnt attempt to create anything at all. Please do only report issues that either have some effect ingame or spam your logs heavily.
