### ISSUE TITLE
Crash when placing stuf on red outline on hidden turret base

### ISSUE THREAD

**Issue by SirAron111** [OpenModularTurretsTeam/OpenModularTurrets#524]
### What happens:

Game Crash when placing stuff on turret base. like expander or the like. maybe has to do with having the turrets hiding function active in configs and forgetting what place has a turret on it and tring to place something on that spot.

#### What you expected to happen:

No crash.

#### Steps to reproduce:

1. try to add or place something onto turretbase
2. sometimes crash
3. no profit
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT:openmodularturrets-1.12.2-3.1.11-372.jar           
- OMLib:omlib-1.12.2-3.1.4-249.jar 
- Minecraft: 1.12.2
- Forge: Forge 14.23.5.2847 
- SpongeForge? yes/no (NO)
- Optifine? yes/no (Yes and No teste happens with both cases)
- Single Player and/or Server? (Single and Multi Player)

Using the releas versions. i am actuallyhoping and waiting that not only this bug gets fixed but also the Turret targeting list gets expanded so they actually attack mobs from the primitive mobs mod as well and not always ignore them.

#### Your most recent log file where the issue was present: 

[crash-2020-06-20_21.37.04-client.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/4808002/crash-2020-06-20_21.37.04-client.txt)

**Comment by Keridos** [comment]
Will fix the crash but there simply is no targeting list for the turrets.

-------- Original Message --------
