### ISSUE TITLE
Crash with Valkyrien Skies

### ISSUE THREAD

**Issue by AYYYYYYMD** [OpenModularTurretsTeam/OpenModularTurrets#525]
#### Issue Description:

When a VS ship is assembled/disassembled with a OMT turret on it, Minecraft crashes. Only happens if the turret base has a turret attached to it. This does not happen if the turret is added after the ship is assembled, but the game crashes the same way when the ship is disassembled, unless the turrets are removed from the turret base.

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.1.11-372
- OMLib: 1.12.2-3.1.4-249
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? LAN Server

#### Your most recent log file where the issue was present: 

[https://pastebin.com/djDnY7ps]

**Comment by Keridos** [comment]
Same as #528. Please check if this fixes it: https://jenkins.ironhide.de/job/OMTTeam/job/OpenModularTurrets-1.12-3.1.x/373/
