### ISSUE TITLE
Grenade launcher fire rate

### ISSUE THREAD

**Issue by ghost** [OpenModularTurretsTeam/OpenModularTurrets#526]
#### Issue Description:
Grenade launcher fire rate is incorrectly displayed in config and cant be changed
#### What happens:
Fire rate is 40 by default in config. In game fire rate is 2 shoots/second. Changes in config dont apply to the game.
#### What you expected to happen:
Changeable fire rate. Fire rate 40 should be 0.5 shoots/second, not 2/s.
#### Steps to reproduce:
1. Place a base and grenade launcher turret on it
2. Check its fire rate
3. Open config and change grenade turret's baseFireRare to something else
4. Replace turret
5. Check its fire rate
____
#### Affected Versions:

- OMT: 3.1.11-372
- OMLib: 3.1.4-249
- Minecraft: 1.12.2
- Forge: 4.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? single player

**Comment by Keridos** [comment]
Could've sworn I fixed that one some time ago...
