### ISSUE TITLE
Vanish issue

### ISSUE THREAD

**Issue by BPXXBLINKERS** [OpenModularTurretsTeam/OpenModularTurrets#527]
I am a server manager for a server network and we have a conflict between Modular turrets and our Vanish that we use to monitor players for rule breaking or investigations. The vanish makes it appear as if we have logged off and invisible in every way. However when we go near a turret and get shot at showing our presence. Is there a way to fix this that is known of, if not can I get permission to have our developer take a look at the code to try to fix it?

**Comment by Keridos** [comment]
Yeah sure, the best way to go about this is probably to check if the player is "fake" logoff or the invisible part. Do not want another dependency for the mod rather. I am rather busy IRL so I do not know when I might get around to doing that. But if your dev wants to take a look at this, the best place to start is probably this: https://github.com/OpenModularTurretsTeam/OpenModularTurrets/blob/1.12/src/main/java/omtteam/openmodularturrets/turret/TurretTargetingUtils.java#L181

**Comment by BPXXBLINKERS** [comment]
Awesome thanks man you're the best. I'll let you know if we find anything

**Comment by Keridos** [comment]
Also: you can enter creative mode, turrets ignore creative mode players.
