### ISSUE TITLE
Game crashes after using Enderio bin to fill turret through hopper

### ISSUE THREAD

**Issue by AkiraKitsune** [OpenModularTurretsTeam/OpenModularTurrets#528]
#### Issue Description:

Turrets cause crashing after a certain amount of tics due to feeding items into it through a hopper

#### What happens:
The game shuts down and then proceeds to spit out a crash report

#### What you expected to happen:
ammo is meant to continuously feed into the turrent without crashing the game

#### Steps to reproduce:

1.place a turret such as a rocket turret
2.place a hopper on the side
3.use the endeerio creative bin to fill the hopper and feed to the turret
4.wait a few mins
5.crash
...

____
#### Affected Versions (Do *not* use "latest"):

-Enderio: 5.2.59
-EnderCore: 0.5.76
- OMT:3.1.1.1-372
- OMLib:3.1.4-249
- Minecraft:1.12.2
- Forge:14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player and/or Server? single player

#### Your most recent log file where the issue was present: 
i'm hoping it alright to attach the report, as i don't have any accounts on sites such as pastebin

[2020-08-11-4.log](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/5062539/2020-08-11-4.log)

**Comment by AkiraKitsune** [comment]
All I ask is that you still allow the hopper to feed ammo after fixing the bug, it makes it easier then using inventory expanders or feeding it manually.

**Comment by AkiraKitsune** [comment]
thank you and I hope to see this mod continuing for the foreseeable future 👍

**Comment by Keridos** [comment]
Can you please test this: https://jenkins.ironhide.de/job/OMTTeam/job/OpenModularTurrets-1.12-3.1.x/373/

**Comment by Keridos** [comment]
Fixed version 3.1.12 is released on Curseforge.
