### ISSUE TITLE
disposable turret ignoring recycler addon and behavior

### ISSUE THREAD

**Issue by AkiraKitsune** [OpenModularTurretsTeam/OpenModularTurrets#529]
#### Issue Description:
recycler feature not functioning at all when used on disposable turrets
#### What happens:
items are used as if the addon was never added to the turret

#### What you expected to happen:
item negate and addition should take effect and possibly save ammunition

#### Steps to reproduce:

1.create disposable turret
2.fill with ammo of choice
3.add recycler addon to turret
4.results should show at this point
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT:3.1.11-372
- OMLib:3.1.4-249
- Minecraft:1.12.2
- Forge:14.23.5.2838
- SpongeForge? no
- Optifine? yes
- Single Player

#### Your most recent log file where the issue was present: 
cannot provide a log for this issue, apologies

**Comment by AkiraKitsune** [comment]
this has been a lingering issue for as long as I can remember, if you can find a fix, that would make me feel a lot happier.

**Comment by Keridos** [comment]
Actually Id like to not create items since I cannot properly define a single item that should be created.

/edit: Nevermind that. it works now
