### ISSUE TITLE
Turret Base Crank suffocates when at head level

### ISSUE THREAD

**Issue by SkyLord-Volmir** [OpenModularTurretsTeam/OpenModularTurrets#530]
#### Issue Description:
Basic Turret Base Crank causes suffocation when placed at eye level and approached.

#### What happens:
Player takes damage when inside the block space of the crank when it's at eye level.

#### What you expected to happen:
Not take suffocation damage when next to my potato cannon :P 

#### Steps to reproduce:

1. Place turret base 1 block above floor (what I'm calling "eye level")
2. Pace the crank on the side.
3. Walk up to the crank.
4. Be damaged

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 3.1.11-372
- OMLib: 3.1.4-249
- Minecraft:1.12.2
- Forge: 14.23.5.2847
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Server.

Technically, yes, I'm on a server, but I don't think whether a block suffocates you can be related to that.
Pack version: MCEternal 1.3.7.1
I also added RandomTweaks 2.8.2.0 to my client.

**Comment by Keridos** [comment]
https://jenkins.ironhide.de/job/OMTTeam/job/OpenModularTurrets-1.12-3.1.x/373/ if you are interested.
