### ISSUE TITLE
Crash with OMT and Extra Utils. Unloadable world

### ISSUE THREAD

**Issue by Xplodin** [OpenModularTurretsTeam/OpenModularTurrets#532]
#### Issue Description:

Extra utils and OMT cause crash together

#### What happens:

my server crashes after loading the world

#### What you expected to happen:

the world to load

#### Steps to reproduce:

1. something about extra utils and omt dont work well
2. connect something from extra utils to omt
3. somehow crash and cant load
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: openmodularturrets-1.12.2-3.1.11-372.jar
- OMLib: omlib-1.12.2-3.1.4-249.jar
- Minecraft: 1.12.2
- Forge: 2847
- SpongeForge? yes
- Optifine? no
- Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here]
[crash-2020-09-02_01.23.40-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/5159255/crash-2020-09-02_01.23.40-server.txt)

**Comment by Keridos** [comment]
This actually seems to be caused from the same source as #528. Closing this.

**Comment by Keridos** [comment]
Can you please test if this fixes it: https://jenkins.ironhide.de/job/OMTTeam/job/OpenModularTurrets-1.12-3.1.x/373/
