### ISSUE TITLE
java.lang.NullPointerException 

### ISSUE THREAD

**Issue by lllMohandarlll** [OpenModularTurretsTeam/OpenModularTurrets#534]
Seems like the tier 5 turret base somehow hates the industrial renewal gold energy cables...
The entire server crash if a player loads the interested chunk where the turret lays, this didn't happen immediately though, some bad interaction occurred during time, probably with these cables

Sadly it's not something easy to reproduce
All I can tell is that the interested turret had 4 Damage Boost upgrade modules, 2 Scatter Shot and 1 Fake Drop
 
____
#### Affected Versions (Do *not* use "latest"): 

- OMT: openmodularturrets-1.12.2-3.1.11-372
- OMLib: omlib-1.12.2-3.1.4-249
- Minecraft: 1.12.2
- Forge:  14.23.5.2854
- SpongeForge? no
- Optifine? yes (but of course only on the client side)
- Server

#### Your most recent log file where the issue was present: 

[pastebin/gist/etc link here] 
I can't get the server log of that day for some reason, I may update the issue if I manage to get it somehow
here is the crash report though

https://pastebin.com/1GnkEv4S

**Comment by Keridos** [comment]
Please update to 3.1.12, see if it persists and close the issue if it
doesnt. This issue should be fixed in there.

**Comment by lllMohandarlll** [comment]
Oh my... sorry, I was sure I was on the latest but as I see you guys are pretty active on development, I'm not used to this fast-delivery new releases xD
sorry again, my bad 
I'm gonna update it right now, and let you know if the problem eventually happens again in the future :)

**Comment by Keridos** [comment]
Any update on this?

**Comment by lllMohandarlll** [comment]
So far so good, I guess at this time it could be definetly considered fixed, you did well on closing :)
