### ISSUE TITLE
Link broken on Curforge site

### ISSUE THREAD

**Issue by NightOps007** [OpenModularTurretsTeam/OpenModularTurrets#535]
#### What happens:
After clicking the here link to Open Modular Passive Defence from the Open Modular Turrets Curseforge mod page, I get a not found page.

#### What you expected to happen:
Be redirected to the Open Modular Passive Defence mod page on Curseforge site.

#### Steps to reproduce:

1. open browser to curseforge to the Open Modular Turrets mod page
2. find the link that's suppose to take you to Open Modular Passive Defence mod page
3. click it
...

____
#### Affected Versions (Do *not* use "latest"):

- OMT: N/A
- OMLib: N/A
- Minecraft: N/A
- Forge: N/A
- SpongeForge?  N/A
- Optifine?  N/A
- Single Player and/or Server? N/A (maybe single player?)

#### Your most recent log file where the issue was present: does this post count?

![pastebin/gist/etc link here](https://i.imgur.com/JRRPJuf.png)

P.S. I found the actual page it should be linked to: https://www.curseforge.com/minecraft/mc-mods/ompd
But I had fun "making an issue out of it" ~_~
And it seems logical to fix it anyways. If no one were to tell you, how would you ever know? -_*

**Comment by Keridos** [comment]
Thanks, fixed!
