### ISSUE TITLE
Primitive mobs not being targeted,  config for mobs?

### ISSUE THREAD

**Issue by snowyleopardcc** [OpenModularTurretsTeam/OpenModularTurrets#536]
Mobs from `Primitive Mobs` are not being targeted,  I saw you are planning a config for forced targeting,  is there an ETA for this?

What happens:  Minecraft mobs are being targeted fine.  Non minecraft mobs are not.  No config option available other than mob blacklist which is set to armor stand by default.

Thanks,
CC

**Comment by Keridos** [comment]
External issue, bug primitive mobs author to merge this PR: https://github.com/Daveyx0/PrimitiveMobs/pull/293
