### ISSUE TITLE
Electrical Steel with EnderIO

### ISSUE THREAD

**Issue by Ole0110** [OpenModularTurretsTeam/OpenModularTurrets#541]
Hello, I have a question.
Why did I have to craft the Turret Tier 2 with Electrical Steel when I use the mod Ender IO in my modpack? I can also not use Cobblestone as ammo in the Tier 1 Turret.
Why i that so and can I set it to default settings?

**Comment by Keridos** [comment]
That is the default setting. You need to set it to non default.
