### ISSUE TITLE
Redstone Reactor Addon Recipe?

### ISSUE THREAD

**Issue by BaxAndrei** [OpenModularTurretsTeam/OpenModularTurrets#542]
#### Issue Description:

I can`t craft Redstone Reactor Addon (No recipe avaiable in JEI)

#### What happens:

Fresh install.

#### What you expected to happen:

Maybe this mod have another mod depend and I don`t have that mod installed?
____
#### Affected Versions (Do *not* use "latest"):

- OMT: 3.1.12-378
- OMLib: 3.1.4-249
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- SpongeForge?: no
- Optifine?: no
- Single Player and/or Server?: single

**Comment by Shr1mps** [comment]
how did you solve it?, what was the recipe?

**Comment by BaxAndrei** [comment]
> how did you solve it?, what was the recipe?

I didn't find the recipe, but I gave up the modpack. If after so long I didn't get an answer I said I'd better close the ticket.
