### ISSUE TITLE
Info on required changes for 1.16 Port

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#545]
Update: 1.16 will be a full rewrite, including new models/textures and a change of License to MIT for code,  CC-BY-SA-NC for art,

**Comment by LemADEC** [comment]
Have a few more:
http://greyminecraftcoder.blogspot.com/2020/05/minecraft-by-example.html
https://gist.github.com/williewillus/30d7e3f775fe93c503bddf054ef3f93e (1.15 primer)
https://github.com/MinecraftForge/MinecraftForge/pull/5564 (ExtendedBlockState rendering)
