### ISSUE TITLE
Potato cannon (Potatoes issue)

### ISSUE THREAD

**Issue by I3estOFF** [OpenModularTurretsTeam/OpenModularTurrets#550]
#### Issue Description:
Can't pick up fired potatoes.
After cannon shoot entity, potatoes stays on dirt and can't be picked up.

#### What happens:
Can't pick up potatoes

#### What you expected to happen:
Pick up potatoes

#### Steps to reproduce:

1.Shoot sth with potato cannon
2.try pick up potato
____
#### Affected Versions (Do *not* use "latest"):

- OMT: openmodularturrets-1.12.2-3.1.12-378
- OMLib: omlib-1.12.2-3.1.4-249
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2854
- SpongeForge? no
- Optifine? yes
- Single Player

**Comment by Keridos** [comment]
Erm, that is intended, tbh, the potato probably is smashed after hitting
anything. I could make it disappear faster though

**Comment by I3estOFF** [comment]
May be you can add config option to set time of dissapear?

For bigger modpacks like mine (260 mods) every laying item can cause decrease of fps
I have mods that add hordes of zombies, after that hundreds of potatoes are laying on dirt  haha
Thats great feature that they are smashed and are laying on floor but option to set time of dissapearing would be great :)))

**Comment by Keridos** [comment]
This seems to be a bug related to zombies picking up the item.
The items should disappear after 2 seconds but I guess a zombie picking them up makes them stay longer when the zombie dies.
