### ISSUE TITLE
[Suggestion] Light Source Addon

### ISSUE THREAD

**Issue by BeigeAnimal** [OpenModularTurretsTeam/OpenModularTurrets#551]
it'd be nice if there was an addon for the turret's base to emit light, main reason I ask is because I had a base idea with street lights with turrets on them having them.

**Comment by Keridos** [comment]
The higher tier bases already can do that in the settings. 2 sliders, one is opacity, e.g. how much light can pass through it? and the other is how bright itself emits light.
