### ISSUE TITLE
Hello, dear developers, I want to move your OpenModularTurrets to the MCBBS website in China.

### ISSUE THREAD

**Issue by VigilLC** [OpenModularTurretsTeam/OpenModularTurrets#559]
Hello, dear developers, I want to move your OpenModularTurrets to the MCBBS website in China. So that more players can play the latest version of OpenModularTurrets, the current version of OpenModularTurrets on the MCBBS website stays at version 3.0.0, so I hope to update it. The specific website is www.mcbbs.net
I hope you can allow me to move OpenModularTurrets to the MCBBS website, thank you very much!

**Comment by Keridos** [comment]
If you do not profit financially from that, you can technically do it. The License allows for it. But beware, you must point to the source files (.java) somewhere. Also: If we find someone getting money from this mod we will issue a takedown strike. The Github does not properly show this, but I got permission to put all the assets under the CC-BY-NC-SA License. Basically credit author, non commercial and share alike.

/edit: on a side note, if that page had an english translation I might update the mod there too but as far as I can see it does not support englisch.

**Comment by VigilLC** [comment]
Thank you for your permission! I promise that no one will profit from it. You can always go to the MCBBS website to check the OpenModularTurrets mod I transport. After I release the OpenModularTurrets mod, the specific connection will be sent to you!
Thank you again for your permission! I wish you good health!
