### ISSUE TITLE
[SUGGESTION] 1.19.2 and 1.20.1 mod update request 

### ISSUE THREAD

**Issue by Zorro8183** [OpenModularTurretsTeam/OpenModularTurrets#563]
Would you be updating OpenModularTurrets to 1.19.2 and/or1.20.1? this seems like it would be a cool mod to try but it's not been updated and we use 1.19.2 on our servers with the possibility of going to 1.20.1.

**Comment by NewAgeSoldier** [comment]
I would also love to see this mod updated to the latest versions, as the mod sits close to home for me.... It would be a real shame if this mod was just forgotten.... I am also trying to ask other mods to update as 1.20 seems to be the perfect time for older mods to rise up from the dead :)

**Comment by Sokrama** [comment]
I also think that mod should be updated to the newest versions of minecraft,because this mod is incredible and gives your multiplayer gaming so much more possibilities.

**Comment by Keridos** [comment]
see https://github.com/orgs/OpenModularTurretsTeam/projects/1
