### ISSUE TITLE
1.7.10 no GUI menu

### ISSUE THREAD

**Issue by Colnars** [OpenModularTurretsTeam/OpenModularTurrets#567]
Please, can anybody help? I instelled this mod on my server 1.7.10, but when click on turret base, I do not see config menu. What I have to do to correct this?

And scond question... Is it posible to use this mod on server agains players?

Thank you!

**Comment by Keridos** [comment]
You probably have not online mode server. Enable online mode compatibility in openmodularturrets config. And yes, it is usable in PvP.

**Comment by Colnars** [comment]
> You probably have not online mode server. Enable online mode compatibility in omlib config. And yes, it is usable in PvP.

You mean in config. File name openmodularturrets.cfg
Line B:"Enable offline mode support?(warning, makes turrets fairly unsafe)"=false
I wrote there false.

Or you mean in server.properties - online-mode

Please, I read all posts what had google. You - my last hope.

**Comment by Keridos** [comment]
server.properties controls the minecraft server. online mode = true means you need to have a minecraft account to play on it. offline-mode-support in openmodularturrets needs to be set to true if the server.properties online-mode is set to false.

**Comment by Keridos** [comment]
Ah and place down another base to test if it works.

**Comment by Colnars** [comment]
I have:
server.properties 
online-mode=false

openmodularturrets.cfg
B:"Enable offline mode support?(warning, makes turrets fairly unsafe)"=true

And I still can not see buttons with configurate when I opening turret.
I have all permisions and OP. In single game I can see that buttons.

**Comment by Keridos** [comment]
> I have: server.properties online-mode=false
> 
> openmodularturrets.cfg B:"Enable offline mode support?(warning, makes turrets fairly unsafe)"=true
> 
> And I still can not see buttons with configurate when I opening turret. I have all permisions and OP. In single game I can see that buttons.

That should work. Test a freshly placed turrets. And remember you have to restart the server/client if you change the config.

**Comment by Colnars** [comment]
YES! Now it's working. I restarted client add openmodularturrets.cfg
B:"Enable offline mode support?(warning, makes turrets fairly unsafe)"=true

in client configs just to be sure.

Thank you! And happy new year! And I wish you everyting good!
