### ISSUE TITLE
Feature Request: Recipe support

### ISSUE THREAD

**Issue by Badcholo** [OpenModularTurretsTeam/OpenModularTurrets#59]
It would be very nice to have this mod without having to download all the other stuff like Cofh core, Thermal expansion, thermal foundation. Making the items or recipes compatible with Mekanism would be amazing. I understand it is an add on to thermal, but it would be nice to use it without it.

/edit by Keridos: 
- [x] TE Recipes
- [x] EnderIO Recipes
- [x] Mekanism Recipes

/edit by Poenjabiesous
- [x] Vanilla Recipes (Which should be the default if none of the other mods are detected)

**Comment by Keridos** [comment]
This is a bit like #41. We are already planning a bit for this but since I am the only one who seems to be active atm and I am working on 2 mods it might take a while.

**Comment by Poenjabiesous** [comment]
Yes, I do agree to some extent. The lower tiers can be made cheaper to be more accessible early game, but I don't want the turrets to be spammable; i.e, made so cheap that everyone can have 100 turret bases sitting around their base lagging up the server. 

Lets talk weighting the recipes over the weekend.

**Comment by Poenjabiesous** [comment]
I'll do the Mek + EnderIO recipes after we have agreed on balanced recipes.

**Comment by Keridos** [comment]
Let me do the enderIO stuff, I regularly play with EnderIO on my private server.

**Comment by Keridos** [comment]
We should really do a priority system, I'd suggest top priority for EnderIO, then mekanism, then Thermal Expansion then Vanilla. That way we only have one recipe set active instead of 4 when all mods are installed.

**Comment by Poenjabiesous** [comment]
TE recipes done, I changed them up a bit. I made the overall recipes a bit more expensive, but turret bases are crafted with TE's energy cells, in stead of the previous tiers' base, to balance out the procurability/payoff vs. vanilla recipes.

**Comment by Poenjabiesous** [comment]
Okay, only recipes we still need is the EnderIO ones. @Keridos, you mentioned that you would like to do them? I can do them as well if you are a bit busy.

**Comment by Keridos** [comment]
I currently do not work much on mods to be honest, if you got the time and want to do them, go ahead. I need to look into the NEI stuff aswell, keep ignoring that since a few weeks.

**Comment by Poenjabiesous** [comment]
Sure, will do them.

**Comment by Keridos** [comment]
Thank you. Now it looks as if this is the last issue for the 2.0.0 release.

**Comment by Poenjabiesous** [comment]
Done.

**Comment by Keridos** [comment]
I am gonna make sure the mod is relatively bug free with a bit of testing with nightssta69 in the next few days. Release when finished testing, ok?

**Comment by Poenjabiesous** [comment]
I was busy testing the last 2 weeks with about 25 other people on the Explosive Networks public PvP server :) Rest assured everything has been thoroughly tested. I even added custom death messages per projectile; no one wants to see a death message like death.attack.laser :)

**Comment by Poenjabiesous** [comment]
I put up a preliminary v2.0.0 release last night on curse after I was satisfied with the EnderIO recipes.

**Comment by Keridos** [comment]
Ah ok, so I can assume that everything works fine?

**Comment by Poenjabiesous** [comment]
I believe so, yes.
