### ISSUE TITLE
New turret idea's/blueprints brainstorm

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#6]
Hi Guys

I'm opening up this thread to discuss new ideas for additional weaponized and utility turrets, as I feel this will be a big growth point in the project. State new ideas as per the following example:

1. Name
2. Weaponized/Utility
3. Tier 0/1/2/3/4
4. Description

**Comment by Scarjit** [comment]
1. Stun Tower
2. Weapon
3. Tier 3/4
4. A non-lethal tower, wich stuns/slows entity's. Should not be to OP, if the Tower is slow firing.

**Comment by Poenjabiesous** [comment]
@Scarjit, will play with the idea of a entity disabling turret. Thanks for your input.

**Comment by teamMK** [comment]
Maybe a flamethrower turret

**Comment by Keridos** [comment]
Hm, the teleporter turret and the stun tower seem really nice. Maybe add one in for 1.4?

**Comment by nightstalker6669** [comment]
teleporter turret could be fun to play with.

**Comment by Poenjabiesous** [comment]
New turrets that I will add for 1.4:

1. Potato Cannon (Tier 0):

Minor range and damage improvements over the Disposable Item Turret, but can only use potatoes as ammo.

2. Incendiary Turret (Tier 1)

Less range than the machine gun turret, but targeted entities are set ablaze in an AOE radius around impact.

3. Relativistic Turret (Tier 2)

Slows all targetable entities in range. Effect becomes stronger the closer the target is to the turret. Does not consume ammo.

4. Teleporter Turret (Tier 3)

Will teleport all targetable entities in range (with a minimum range) to the block above itself.

**Comment by Keridos** [comment]
OK looks good, I write this in the top coment now, so we can keep track of stuff.

**Comment by gunnerwolf** [comment]
Name: Freeze/Stun Turret
Type: Utility
Tier: 3/4
Description: Freezes a single target for a short time, damage upgrade increases freeze length
Maybe make it not target frozen mobs so once it's frozen a mob it moves on to the next mob

**Comment by Poenjabiesous** [comment]
Closing this ticket, all new turrets for V2.0.0 are done and dusted.
