### ISSUE TITLE
Server administration tools

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#67]
This would include server-side config for server administrators to have much more control over how the mod is used on a specific server.

-Should turret bases only be place-able in claimed areas (not sure about the implementation of this one, feel free to comment)?

-Edit by Poenjabiesous:

- [x] Specific turrets->Enabled/Disabled
- [x] Global targeting restrictions

**Comment by Keridos** [comment]
I would say a config option for the first. Not sure what you want to say with the second one.
And the third one could be a config option as well. Maybe even a button in the GUI.

**Comment by Keridos** [comment]
When doing the first one, maybe make it check if all bases are valid on serverstart in case somebody messed around with MCEdit etc.

**Comment by Keridos** [comment]
What about the number of bases per player?

**Comment by Poenjabiesous** [comment]
I thought alot about that one, coming to the conclusion that that type of responsability shouldnt lie within the mod, but rather with grief prevention mods, as there are quite a few out there that adds that functionality. But this is open for discussion.

**Comment by Keridos** [comment]
Ok, then we can close this.
