### ISSUE TITLE
Turret Scattershot

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#91]
Suggestion: Add in possibilities for Turret Specialization, f.ex different Crystals for the Laser, one for short one for Longrange or A scattershot for it. Or Shotgun modification for the machine gun: Slower shooting, but multiple bullets per shot.

When we make servers delete all their previous TileEntities we could aswell implement more "breaking" stuff.

- [x] Scattershot upgrade - Adds 2 projectiles to a shot, at the cost of massive decrease in accuracy and +2 ammo. Any turret can use this upgrade.

**Comment by Poenjabiesous** [comment]
New Upgrades:

- [ ] Scattershot upgrade - Shoots 5 projectiles in a single shot, at the cost of massive decrease in accuracy and 5 ammo. Any turret can use this upgrade.

**Comment by Poenjabiesous** [comment]
Done

**Comment by Poenjabiesous** [comment]
What exactly will the crystal upgrade do? We already have range + accuracy upgrades?

**Comment by Keridos** [comment]
I'd suggest things like halving range but doubling damage or similar things.

**Comment by Poenjabiesous** [comment]
Ah. That can be done. Idk about changing projectile color though.

**Comment by Poenjabiesous** [comment]
The java Tesselator/GL isn't my strong suite.

**Comment by Keridos** [comment]
I'll take a look into that, I am pretty sure there is a way to color stuff in there.

**Comment by Keridos** [comment]
I propose the laser crystals to a later point, we should have enough content for the next update.
