### ISSUE TITLE
Thaumcraft integration?

### ISSUE THREAD

**Issue by Poenjabiesous** [OpenModularTurretsTeam/OpenModularTurrets#96]
Some players don't like the techy side of modded minecraft, and I would like to cater for them as well. Why not Thaumcraft?

We can do one of the following:

-An addon for a base that converts piped Potentia essentia into RF.

-A new turret base (Tier 5) that only accepts Potetia essentia, and uses that as a power source (where 1 essentia would translate into +- 500RF, so that we don't need to change config)

Thoughts?

**Comment by Keridos** [comment]
:+1:

**Comment by Poenjabiesous** [comment]
Done.
