### ISSUE TITLE
Transfer Repository to Team Organization?

### ISSUE THREAD

**Issue by Keridos** [OpenModularTurretsTeam/OpenModularTurrets#98]
I noticed that I cannot add webhooks to the repository because it is still owned by you @Poenjabiesous. Can we maybe create an organization ( I already made one), where you can be admin if you want so I can edit the repository too? Wanted to add in support to show commits and Issues in our IRC Channel but I need to add in webhooks for that.

**Comment by Poenjabiesous** [comment]
Lets do it.

**Comment by Keridos** [comment]
You should have an invite.

**Comment by Keridos** [comment]
And you should be able to transfer the Repository to the team in the settings somewhere.

**Comment by Poenjabiesous** [comment]
I dont seem to be able to transfer ownership of the  the repo to the orginization. What rights do you need to do it?

**Comment by Keridos** [comment]
I think you can transfer it to me and I could do that if you want.

**Comment by Keridos** [comment]
Any update on this?

**Comment by Keridos** [comment]
Test123
