### ISSUE TITLE
Turrets cannot detect entity through Grass or Double Tallgrass

### ISSUE THREAD

**Issue by surferconor425** [OpenModularTurretsTeam/OpenModularTurrets#99]
When a mob is hidden behind either of them they cannot be detected by the turret.
Mod Version: https://www.ironhide.de/jenkins/job/OpenModularTurrets/80/
![2015-05-21_20 47 23](https://cloud.githubusercontent.com/assets/1810150/7757480/9f3ffae0-fffa-11e4-922b-1eb5902a1d8b.png)

**Comment by tossaponk** [comment]
This is from the fact that the current turret targeting function using default minecraft block tracing function. This function will stop tracing on any block whether it's is solid or not.

To fix this, we might need to implement the tracing function ourselves which will ignore non solid block. But it may significantly impact targeting performance if not implemented correctly.

**Comment by Poenjabiesous** [comment]
I am concerned about the overhead of such an operation. Essentially, this is multiple raytraces- where the amount is equal to how many non-solid blocks are between the turret and the target, if we do the offset-on-hit method. But, also said, I cant think of another way to implement this. What does vanilla skeletons do in regard to target-behind-grass-block targeting?

**Comment by tossaponk** [comment]
I don't think they can see player through double tall grass though. But from the reading of their AI code revealed that they cached the target when they see the player. That's probably why they continue to shoot even if player ran behind tall grass.

**Comment by Poenjabiesous** [comment]
Works like a charm. Commiting it now. Thanks @tossaponk!
